import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

// Sperax USD (USDs) is a yield-bearing, 100%-collateral-backed stablecoin on Arbitrum.
// https://docs.sperax.io/master
// https://docs.sperax.io/buyback-contract
//  1. Yield: collateral (USDC/USDT/DAI...) is deployed into strategies (Aave, Compound,
//     Stargate...) which earn interest + rewards. Harvested yield is swapped into freshly
//     minted USDs and distributed via the YieldReserve's `USDsSent` event, split by
//     `buybackPercentage` (currently 30%):
//       - 30% -> SPABuyback: buys back and burns SPA (revenue, accrues to SPA holders)
//       - 70% -> Dripper -> Vault.rebase(): rebased to USDs holders (supply-side revenue)
//
//  2. Mint/redeem fees: charged in USDs on Vault mint/redeem and deposited directly into
//     the SPABuyback contract. Emitted as the `feeAmt` field of the Vault Minted/Redeemed
const USDS = "0xD74f5255D557944cf7Dd0E45FF521520002D5748";
const YIELD_RESERVE = "0xfD14C8ef0993fd9409f7820BA8BA80370529d861";
const VAULT = "0x6Bbc476Ee35CBA9e9c3A59fc5b10d7a0BC6f74Ca";

const abi = {
  usdsSent: "event USDsSent(uint256 toBuyback, uint256 toDripper)",
  minted: "event Minted(address indexed wallet, address indexed collateralAddr, uint256 usdsAmt, uint256 collateralAmt, uint256 feeAmt)",
  redeemed: "event Redeemed(address indexed wallet, address indexed collateralAddr, uint256 usdsAmt, uint256 collateralAmt, uint256 feeAmt)",
};

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyHoldersRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyUserFees = options.createBalances();

  const [yieldLogs, mintLogs, redeemLogs] = await Promise.all([
    options.getLogs({ target: YIELD_RESERVE, eventAbi: abi.usdsSent }),
    options.getLogs({ target: VAULT, eventAbi: abi.minted }),
    options.getLogs({ target: VAULT, eventAbi: abi.redeemed }),
  ]);

  yieldLogs.forEach((log: any) => {
    dailyFees.add(USDS, log.toBuyback, METRIC.ASSETS_YIELDS);
    dailyFees.add(USDS, log.toDripper, METRIC.ASSETS_YIELDS);

    // 30% cut used to buy back and burn SPA, protocol revenue accruing to SPA holders.
    dailyRevenue.add(USDS, log.toBuyback, METRIC.TOKEN_BUY_BACK);
    dailyHoldersRevenue.add(USDS, log.toBuyback, METRIC.TOKEN_BUY_BACK);

    // 70% dripped to the Vault and rebased to USDs holders, supply-side revenue.
    dailySupplySideRevenue.add(USDS, log.toDripper, "USDs Holder Rebase");
  });

  // Mint/redeem fees (USDs) go straight to the buyback contract.
  mintLogs.concat(redeemLogs).forEach((log: any) => {
    dailyFees.add(USDS, log.feeAmt, METRIC.MINT_REDEEM_FEES);
    dailyUserFees.add(USDS, log.feeAmt, METRIC.MINT_REDEEM_FEES);
    dailyRevenue.add(USDS, log.feeAmt, METRIC.MINT_REDEEM_FEES);
    dailyHoldersRevenue.add(USDS, log.feeAmt, METRIC.MINT_REDEEM_FEES);
  });

  return { dailyFees, dailyUserFees, dailyRevenue, dailyHoldersRevenue, dailySupplySideRevenue };
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  fetch,
  adapter: {
    [CHAIN.ARBITRUM]: { start: "2024-01-15" },
  },
  methodology: {
    Fees: "Yield harvested on the USDs collateral basket (strategy interest + rewards) plus USDs mint/redeem fees.",
    UserFees: "USDs mint and redeem fees paid by users.",
    Revenue: "30% of the yield plus 100% of mint/redeem fees, used to buy back and burn SPA.",
    HoldersRevenue: "30% of the yield plus 100% of mint/redeem fees, used to buy back and burn SPA, accruing value to SPA holders.",
    SupplySideRevenue: "70% of the yield rebased to USDs holders via the Dripper and Vault.",
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: "Yield generated by the USDs collateral deployed into DeFi strategies.",
      [METRIC.MINT_REDEEM_FEES]: "Fees charged in USDs when users mint or redeem USDs.",
    },
    UserFees: {
      [METRIC.MINT_REDEEM_FEES]: "Fees charged in USDs when users mint or redeem USDs.",
    },
    Revenue: {
      [METRIC.TOKEN_BUY_BACK]: "30% of yield used to buy back and burn SPA.",
      [METRIC.MINT_REDEEM_FEES]: "Mint/redeem fees deposited to the buyback contract.",
    },
    HoldersRevenue: {
      [METRIC.TOKEN_BUY_BACK]: "30% of yield used to buy back and burn SPA.",
      [METRIC.MINT_REDEEM_FEES]: "Mint/redeem fees deposited to the buyback contract.",
    },
    SupplySideRevenue: {
      "USDs Holder Rebase": "USDs rebased to holders.",
    },
  },
};

export default adapter;
