import { FetchOptions, FetchResultV2, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

const TPOOL_REWARD_DECIMAL_ADJUSTMENT = 10n ** 12n;

// Flare USDX token used as the reward asset when reading T-Pool accumulated yield.
const FLARE_USDX = "0x4a771cc1a39fdd8aa08b8ea51f7fd412e73b3d2b";
// Clearpool USDX T-Pool contract on Flare; source for on-chain totalRewards(USDX).
const FLARE_TPOOL = "0xfe2907dfa8db6e320cdbf45f0aa888f6135ec4f8";

// Public T-Pool ABI method used to read the USDX reward accumulator from Flare RPC.
const TPOOL_ABI = "function totalRewards(address _rewardAsset) view returns (uint256 accumulated, uint256 withdrawn)";

const toBigInt = (value?: string | number | bigint | null) => BigInt(value?.toString() ?? "0");

const getTpoolAccumulatedRewards = async (api: FetchOptions["api"]) => {
  // On-chain source: T-Pool reward accumulator for USDX yield distributed to depositors.
  const rewards = await api.call({
    target: FLARE_TPOOL,
    abi: TPOOL_ABI,
    params: [FLARE_USDX],
  });

  return toBigInt(rewards.accumulated ?? rewards[0]);
};

const fetchFlare = async (options: FetchOptions): Promise<FetchResultV2> => {
  const dailyFees = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const [startRewards, endRewards] = await Promise.all([
    getTpoolAccumulatedRewards(options.fromApi),
    getTpoolAccumulatedRewards(options.toApi),
  ]);

  if (endRewards > startRewards) {
    // The accumulator uses 18 decimals, while USDX balances are reported with 6 decimals.
    const tpoolYield = (endRewards - startRewards) / TPOOL_REWARD_DECIMAL_ADJUSTMENT;
    dailyFees.add(FLARE_USDX, tpoolYield, METRIC.ASSETS_YIELDS);
    dailySupplySideRevenue.add(FLARE_USDX, tpoolYield, METRIC.ASSETS_YIELDS);
  }

  return {
    dailyFees,
    dailyRevenue: 0,
    dailyProtocolRevenue: 0,
    dailySupplySideRevenue,
  };
};

const adapter: SimpleAdapter = {
  version: 2,
  methodology: {
    Fees: "RWA yield generated by Clearpool T-Pool on Flare, using the USDX reward accumulator.",
    Revenue: "No protocol revenue is counted because the public T-Pool ABI does not expose protocol fee collection.",
    ProtocolRevenue: "No protocol revenue is counted.",
    SupplySideRevenue: "USDX yield distributed to T-Pool depositors. FLR incentive rewards are excluded.",
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: "Daily change in T-Pool accumulated USDX rewards.",
    },
    SupplySideRevenue: {
      [METRIC.ASSETS_YIELDS]: "USDX yield attributable to T-Pool depositors.",
    },
  },
  adapter: {
    [CHAIN.FLARE]: {
      fetch: fetchFlare,
      start: "2024-05-20",
    },
  },
};

export default adapter;
