import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

const TPOOL_REWARD_DECIMAL_ADJUSTMENT = 10n ** 12n;

const chainConfig: any = {
    [CHAIN.FLARE]: {
        "TPOOL": "0xfe2907dfa8db6e320cdbf45f0aa888f6135ec4f8",
        "USDX": "0x4a771cc1a39fdd8aa08b8ea51f7fd412e73b3d2b",
        start: "2024-05-20",
    },
};
const TPOOL_ABI = "function totalRewards(address _rewardAsset) view returns (uint256 accumulated, uint256 withdrawn)";

const fetch = async (options: any) => {
    const config = chainConfig[options.chain];
    const dailyFees = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();
    const readRewards = async (api: any) => {
        const rewards = await api.call({
            target: config.TPOOL,
            abi: TPOOL_ABI,
            params: [config.USDX],
        });
        return BigInt((rewards.accumulated ?? rewards[0]).toString());
    };

    const [startRewards, endRewards] = await Promise.all([readRewards(options.fromApi), readRewards(options.toApi)]);

    const tpoolYield = (endRewards - startRewards) / TPOOL_REWARD_DECIMAL_ADJUSTMENT;
    dailyFees.add(config.USDX, tpoolYield, METRIC.ASSETS_YIELDS);
    dailySupplySideRevenue.add(config.USDX, tpoolYield, METRIC.ASSETS_YIELDS);

    return {
        dailyFees,
        dailyRevenue: 0,
        dailyProtocolRevenue: 0,
        dailySupplySideRevenue,
    };
};

const adapter = {
    version: 2,
    pullHourly: true,
    fetch,
    adapter: chainConfig,
    methodology: {
        Fees: "RWA yield generated by Clearpool T-Pool on Flare, using the USDX reward accumulator.",
        Revenue: "No protocol revenue is counted because the public T-Pool ABI does not expose protocol fee collection.",
        ProtocolRevenue: "No protocol revenue is counted.",
        SupplySideRevenue: "USDX yield distributed to T-Pool depositors. FLR incentive rewards are excluded.",
    },
    breakdownMethodology: {
        Fees: {
            [METRIC.ASSETS_YIELDS]: "Daily change in T-Pool accumulated USDX rewards.",
        },
        SupplySideRevenue: {
            [METRIC.ASSETS_YIELDS]: "USDX yield attributable to T-Pool depositors.",
        },
    },
    allowNegativeValue: true,
};

export default adapter;
