// Use
export enum CHAIN {
  ARBITRUM = "arbitrum",
  AVAX = "avax",
  BLAST = "blast",
  BOBA = "boba",
  BSC = "bsc",
  CELO = "celo",
  ETHEREUM = "ethereum",
  FANTOM = "fantom",
  HARMONY = "harmony",
  HECO = "heco",
  OKEXCHAIN = "okexchain",
  OPTIMISM = "optimism",
  POLYGON = "polygon",
  RONIN = "ronin",
  XDAI = "xdai",
  AURORA = "aurora",
  MOONRIVER = "moonriver",
  TRON = "tron",
  MOONBEAN = "moonbeam",
  KLAYTN = "klaytn",
  JUNO = "juno",
  KCC = "kcc",
  WAN = "wan",
  CARDANO = "cardano",
  LITECOIN = "litecoin",
  BITCOIN = "bitcoin",
  BITCOIN_CASH = "bitcoincash",
  DOGECHAIN = "dogechain",
  ENERGI = "energi",
  VELAS = "velas",
  ELASTOS = "elastos",
  TEZOS = "tezos",
  METIS = "metis",
  SOLANA = "solana",
  IOTEX = "iotex",
  KARDIA = "kardia",
  TOMBCHAIN = "tombchain",
  CONFLUX = "conflux",
  TERRA = "terra",
  METER = "meter",
  GODWOKEN = "godwoken",
  GODWOKEN_V1 = "godwoken_v1",
  FUSE = "fuse",
  SX = "sx",
  ELROND = "elrond",
  DEFICHAIN = "defichain",
  CUBE = "cube",
  STACKS = "stacks",
  STEP = "step",
  SYSCOIN = "syscoin",
  CRONOS = "cronos",
  VISION = "vision",
  KARURA = "KARURA",
  SMARTBCH = "smartbch",
  KAVA = "kava",
  HEDERA = "hedera",
  CALLISTO = "callisto",
  EOS = "eos",
  BITTORRENT = "bittorrent",
  ONTOLOGY_EVM = "ontology_evm",
  ICON = "icon",
  CLV = "clv",
  ULTRON = "ultron",
  STELLAR = "stellar",
  ALGORAND = "algorand",
  TELOS = "telos",
  TOMOCHAIN = "tomochain",
  BITGERT = "bitgert",
  FINDORA = "findora",
  FUNCTIONX = "functionx",
  ENERGYWEB = "energyweb",
  MIXIN = "mixin",
  THORCHAIN = "thorchain",
  MILKOMEDA = "milkomeda",
  FLOW = "flow",
  FUSION = "fusion",
  CANTO = "canto",
  APTOS = "aptos",
  NEO = "neo",
  PHANTASMA = "phantasma",
  XDC = "xdc",
  STARKNET = "starknet",
  MOONBEAM = "moonbeam",
  WAVES = "waves",
  CARBON = "carbon",
  THUNDERCORE = "thundercore",
  VECHAIN = "vechain",
  WAX = "wax",
  MAP = "map",
  ARBITRUM_NOVA = "arbitrum_nova",
  INJECTIVE = "injective",
  ORAI = "orai",
  TON = "ton",
  OBYTE = "obyte",
  CORE = "core",
  RPG = "rpg",
  WEMIX = "wemix",
  ZKSYNC = "zksync",
  ERA = "era",
  DFK = "dfk",
  POLYGON_ZKEVM = "polygon_zkevm",
  ACALA = "acala",
  SORA = "sora",
  COSMOS = "cosmos",
  OAS = "oas",
  HYDRA = "hydra",
  ENULS = "enuls",
  SUI = "sui",
  EVMOS = "evmos",
  PULSECHAIN = "pulse",
  ONUS = "onus",
  OASIS = "oasis",
  MANTLE = "mantle",
  ICP = "icp",
  LINEA = "linea",
  BASE = "base",
  NEON = "neon_evm",
  OP_BNB = "op_bnb",
  HYDRADX = "hydradx",
  OSMOSIS = "osmosis",
  SEI = "sei",
  ERGO = "ergo",
  SHIMMER_EVM = "shimmer_evm",
  MEER = "meer",
  SCROLL = "scroll",
  RADIXDLT = "radixdlt",
  LIGHTLINK_PHOENIX = "lightlink_phoenix",
  EON = "eon",
  MANTA = "manta",
  NEAR = "near",
  EOS_EVM = "eos_evm",
  ROLLUX = "rollux",
  MODE = "mode",
  PERSISTENCE = "persistence",
  JBC = "jbc",
  ZKFAIR = "zkfair",
  ZETA = "zeta",
  ASTAR_ZKEVM = "astrzk",
  FILECOIN = "filecoin",
  FRAXTAL = "fraxtal"
}

// Don´t use
const ARBITRUM = "arbitrum";
const AVAX = "avax";
const BOBA = "boba";
const BSC = "bsc";
const CELO = "celo";
const ETHEREUM = "ethereum";
const FANTOM = "fantom";
const HARMONY = "harmony";
const HECO = "heco";
const OKEXCHAIN = "okexchain";
const OPTIMISM = "optimism";
const POLYGON = "polygon";
const RONIN = "ronin";
const XDAI = "xdai";
const AURORA = "aurora";
const MOONRIVER = "moonriver";
const BITCOIN = "bitcoin";
const LITECOIN = "litecoin";
const DOGE = "doge";
const ZKSYNC = "zksync";
const MANTLE = "mantle";
// Don't use
export {
  ZKSYNC,
  ARBITRUM,
  AVAX,
  BOBA,
  BSC,
  CELO,
  ETHEREUM,
  FANTOM,
  HARMONY,
  HECO,
  OKEXCHAIN,
  OPTIMISM,
  POLYGON,
  RONIN,
  XDAI,
  AURORA,
  MOONRIVER,
  BITCOIN,
  LITECOIN,
  DOGE,
  MANTLE
};
