import { Dependencies, FetchOptions, FetchResult, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import { queryDuneResult } from "../../helpers/dune";


const SwapEvent = "event ElfomoTrade(uint256 indexed quoteId, uint256 indexed partnerId, address executor, address receiver, address fromToken, address toToken, uint256 fromAmount, uint256 toAmount)";
const ELFOMOFI_SWAP_ADDRESS = "0xf0f0F0F0FB0d738452EfD03A28e8be14C76d5f73"

// Dune query that decodes the VaultMetrics events and spreads each report's fees/yield evenly across
// its accrual period, producing one row per (day, ref_token) with amortized amounts in token base
// units. https://dune.com/queries/7560737
const DUNE_QUERY_ID = "7560737"

interface IDuneRow {
    day: string;
    ref_token: string;
    fee_protocol: string | number;
    fee_curator: string | number;
    yield_lps: string | number;
}

const fetch = async (options: FetchOptions): Promise<FetchResult> => {
    const dailyVolume = options.createBalances();

    const swapLogs = await options.getLogs({
        target: ELFOMOFI_SWAP_ADDRESS,
        eventAbi: SwapEvent,
    })

    for (const log of swapLogs) {
        dailyVolume.add(log.fromToken, log.fromAmount);
    }

    if (options.chain !== CHAIN.BASE) {
        return { dailyVolume };
    }

    const dailyFees = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();
    const dailyRevenue = options.createBalances();
    const dailyProtocolRevenue = options.createBalances();

    const rows = (await queryDuneResult(options, DUNE_QUERY_ID)) as IDuneRow[];

    // The Dune query returns one row per (day, token) holding that whole day's amortized fees.
    // We attribute to the current fetch window only its share of the day, prorated by overlap, so
    // fees follow the same time-window as volume
    const DAY = 86400;
    const { startTimestamp, endTimestamp } = options;

    for (const row of rows) {
        const dayStart = Math.floor(new Date(`${row.day}T00:00:00Z`).getTime() / 1000);
        const overlap = Math.min(endTimestamp, dayStart + DAY) - Math.max(startTimestamp, dayStart);
        if (overlap <= 0) continue;

        const token = row.ref_token;
        // exact integer proration: raw * overlap / DAY (raw amounts are uint256 base units)
        const slice = (raw: string | number) => (BigInt(raw) * BigInt(overlap) / BigInt(DAY)).toString();

        const feeProtocol = slice(row.fee_protocol);
        const feeCurator = slice(row.fee_curator);
        const yieldLps = slice(row.yield_lps);

        dailyFees.add(token, yieldLps, METRIC.ASSETS_YIELDS);
        dailyFees.add(token, feeProtocol, METRIC.ASSETS_YIELDS);
        dailyFees.add(token, feeCurator, METRIC.ASSETS_YIELDS);

        dailySupplySideRevenue.add(token, yieldLps, METRIC.ASSETS_YIELDS);
        dailySupplySideRevenue.add(token, feeCurator, METRIC.CURATORS_FEES);

        dailyRevenue.add(token, feeProtocol, METRIC.PERFORMANCE_FEES);
        dailyProtocolRevenue.add(token, feeProtocol, METRIC.PERFORMANCE_FEES);
    }

    return {
        dailyVolume,
        dailyFees,
        dailySupplySideRevenue,
        dailyRevenue,
        dailyProtocolRevenue,
    }
}

const methodology = {
    Volume: "Volume is calculated from the fromAmount of all ElfomoTrade events on the Elfomofi swap contract.",
    Fees: "Total yield generated by Elfomofi vaults. Sum of yield distributed to LPs, performance fees captured by the protocol, and performance fees directed to curators.",
    Revenue: "Performance fees captured by the Elfomofi protocol.",
    ProtocolRevenue: "Elfomofi protocol's share of vault performance fees.",
    SupplySideRevenue: "Yield distributed to vault LPs plus performance fees directed to vault curators. Curators are independent operators that manage vault strategies on behalf of LPs.",
}

const breakdownMethodology = {
    Fees: {
        [METRIC.ASSETS_YIELDS]: "Gross yield generated by Elfomofi vaults.",
    },
    Revenue: {
        [METRIC.PERFORMANCE_FEES]: "Performance fees captured by the Elfomofi protocol.",
    },
    ProtocolRevenue: {
        [METRIC.PERFORMANCE_FEES]: "Performance fees captured by the Elfomofi protocol.",
    },
    SupplySideRevenue: {
        [METRIC.ASSETS_YIELDS]: "Yield distributed to vault LPs.",
        [METRIC.CURATORS_FEES]: "Performance fees directed to vault curators.",
    },
}

const adapter: SimpleAdapter = {
    version: 2,
    pullHourly: true,
    methodology,
    breakdownMethodology,
    dependencies: [Dependencies.DUNE],
    adapter: {
      [CHAIN.BASE]: {
        fetch,
        start: "2026-01-06",
      },
      [CHAIN.BSC]: {
        fetch,
        start: "2026-03-15",
      },
    },
  };

  export default adapter;
