import { FetchOptions, FetchResult, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";


const SwapEvent = "event ElfomoTrade(uint256 indexed quoteId, uint256 indexed partnerId, address executor, address receiver, address fromToken, address toToken, uint256 fromAmount, uint256 toAmount)";
const VaultMetricsEvent = "event VaultMetrics(uint256 indexed vaultId, address indexed refTokenAddress, uint256 prevRate, uint256 newRate, uint256 newPreFeeRate, uint256 newHighWaterMarkRate, uint256 prevTimestamp, uint256 newTimestamp, int256 lastPeriodPreFeeAPRInBps, uint256 feeProtocolInRefToken, uint256 feeCuratorInRefToken, uint256 yieldToLPsInRefToken, uint256 protocolSharesMinted, uint256 curatorSharesMinted, uint256 totalAssetsInRefToken)"
const ELFOMOFI_SWAP_ADDRESS = "0xf0f0F0F0FB0d738452EfD03A28e8be14C76d5f73"
const ELFOMOFI_VAULTS_MANAGER = "0xE34CD3682AF9C04303386499FBa215B38Eff6106"

const fetch = async (options: FetchOptions): Promise<FetchResult> => {
    const dailyVolume = options.createBalances();

    const swapLogs = await options.getLogs({
        target: ELFOMOFI_SWAP_ADDRESS,
        eventAbi: SwapEvent,
    })

    for (const log of swapLogs) {
        dailyVolume.add(log.fromToken, log.fromAmount);
    }

    if (options.chain !== CHAIN.BASE) {
        return { dailyVolume };
    }

    const dailyFees = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();
    const dailyRevenue = options.createBalances();
    const dailyProtocolRevenue = options.createBalances();

    const vaultLogs = await options.getLogs({
        target: ELFOMOFI_VAULTS_MANAGER,
        eventAbi: VaultMetricsEvent,
    })

    for (const log of vaultLogs) {
        dailyFees.add(log.refTokenAddress, log.yieldToLPsInRefToken, METRIC.ASSETS_YIELDS);
        dailyFees.add(log.refTokenAddress, log.feeProtocolInRefToken, METRIC.ASSETS_YIELDS);
        dailyFees.add(log.refTokenAddress, log.feeCuratorInRefToken, METRIC.ASSETS_YIELDS);

        dailySupplySideRevenue.add(log.refTokenAddress, log.yieldToLPsInRefToken, METRIC.ASSETS_YIELDS);
        dailySupplySideRevenue.add(log.refTokenAddress, log.feeCuratorInRefToken, METRIC.CURATORS_FEES);

        dailyRevenue.add(log.refTokenAddress, log.feeProtocolInRefToken, METRIC.PERFORMANCE_FEES);
        dailyProtocolRevenue.add(log.refTokenAddress, log.feeProtocolInRefToken, METRIC.PERFORMANCE_FEES);
    }

    return {
        dailyVolume,
        dailyFees,
        dailySupplySideRevenue,
        dailyRevenue,
        dailyProtocolRevenue,
    }
}

const methodology = {
    Volume: "Volume is calculated from the fromAmount of all ElfomoTrade events on the Elfomofi swap contract.",
    Fees: "Total yield generated by Elfomofi vaults. Sum of yield distributed to LPs, performance fees captured by the protocol, and performance fees directed to curators.",
    Revenue: "Performance fees captured by the Elfomofi protocol.",
    ProtocolRevenue: "Elfomofi protocol's share of vault performance fees.",
    SupplySideRevenue: "Yield distributed to vault LPs plus performance fees directed to vault curators. Curators are independent operators that manage vault strategies on behalf of LPs.",
}

const breakdownMethodology = {
    Fees: {
        [METRIC.ASSETS_YIELDS]: "Gross yield generated by Elfomofi vaults.",
    },
    Revenue: {
        [METRIC.PERFORMANCE_FEES]: "Performance fees captured by the Elfomofi protocol.",
    },
    ProtocolRevenue: {
        [METRIC.PERFORMANCE_FEES]: "Performance fees captured by the Elfomofi protocol.",
    },
    SupplySideRevenue: {
        [METRIC.ASSETS_YIELDS]: "Yield distributed to vault LPs.",
        [METRIC.CURATORS_FEES]: "Performance fees directed to vault curators.",
    },
}

const adapter: SimpleAdapter = {
    version: 2,
    pullHourly: true,
    methodology,
    breakdownMethodology,
    adapter: {
      [CHAIN.BASE]: {
        fetch,
        start: "2026-01-06",
      },
      [CHAIN.BSC]: {
        fetch,
        start: "2026-03-15",
      },
    },
  };

  export default adapter;
