import { FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import coreAssets from "../../helpers/coreAssets.json";

const weth = coreAssets.ethereum.WETH
const avEth = '0x9469470C9878bf3d6d0604831d9A3A366156f7EE'
const savEth = '0xDA06eE2dACF9245Aa80072a4407deBDea0D7e341'
const MINT_AND_REDEEM_CONTRACT = '0x09becF6E5e297825D19aA14eD6081A03524532D7'


const REDEEM_ABI = 'event Redeem(address indexed redeemer,address indexed benefactor,address indexed beneficiary,address collateral_asset,uint256 collateral_amount,uint256 avantcoin_amount)'

const fetch = async (_t: number, _c: any, options: FetchOptions) => {
    const dailyFees = options.createBalances();
    const dailyRewards = options.createBalances();
    const dailyRevenue = options.createBalances();
    const dailyRedeemFees = options.createBalances();
    const logs = await options.getLogs({
        eventAbi: REDEEM_ABI,
        target: MINT_AND_REDEEM_CONTRACT,
    })
    logs.forEach((log) => {
        const fee = Number(log.avantcoin_amount) - Number(log.collateral_amount);
        if (fee > 0) {
            dailyRedeemFees.add(weth, fee);
        }
  });
    dailyFees.addBalances(dailyRedeemFees, METRIC.MINT_REDEEM_FEES);
    const daily_rewards = await options.getLogs({
      eventAbi: 'event RewardsReceived (uint256 amount)',
      topic: '0xbb28dd7cd6be6f61828ea9158a04c5182c716a946a6d2f31f4864edb87471aa6',
      target: savEth,
    })
    daily_rewards.forEach((log) => {
      dailyRewards.add(avEth, log.amount);
      dailyRevenue.add(avEth, Number(log.amount) / 9)
    });
    dailyFees.addBalances(dailyRewards, METRIC.ASSETS_YIELDS);

    return {
        dailyFees,
        dailyRevenue: dailyRevenue,
        dailyUserFees: dailyRedeemFees,
        dailySupplySideRevenue: dailyRewards
    }
}
const adapters = {
  adapter: {
    [CHAIN.ETHEREUM]: {
      fetch: fetch,
      start: '2025-08-11',
    }
  },
  methodology: {
    Fees: "Redeem fees + yield distribution",
    Revenue: "10% of the net profits generated by the protocol strategies",
    UserFees: "Redeem fees from users",
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: 'The net profits generated by the protocol strategies.',
      [METRIC.MINT_REDEEM_FEES]: 'Users pay a 0.05% fee when redeeming avETH.',
    }
  },
};
export default adapters;