import request, { gql } from "graphql-request";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";

import { CHAIN } from "../../helpers/chains";

const SUBGRAPH_URL = "https://subgraphspot2.bean.exchange/subgraphs/name/bean-spot-premainnet-v01";

const fetch = async (_a: number, _b: any, options: FetchOptions) => {
  const dailyVolume = options.createBalances();

  const query = gql`
    {
      lbpairHourDatas(
        where: {
          date_gte: ${options.startTimestamp}
          date_lte: ${options.endTimestamp}
        }
      ) {
        volumeUSD
        feesUSD
      }
    }
  `;

  interface DayData {
    volumeUSD: string;
    feesUSD: string;
  }

  const { lbpairHourDatas } = await request<{ lbpairHourDatas: DayData[] }>(SUBGRAPH_URL, query);

  let totalVolumeUSD = 0;
  let totalFeesUSD = 0;

  lbpairHourDatas.forEach((day) => {
    const vol = Number(day.volumeUSD || 0);
    const fee = Number(day.feesUSD || 0);
    totalVolumeUSD += vol;
    totalFeesUSD += fee;
  });

  dailyVolume.addUSDValue(totalVolumeUSD);

  return {
    dailyVolume,
    dailyFees: totalFeesUSD > 0 ? totalFeesUSD : undefined,
    dailyRevenue: totalFeesUSD > 0 ? totalFeesUSD * 0.2 : undefined,
    dailyProtocolRevenue: totalFeesUSD > 0 ? totalFeesUSD * 0.2 : undefined,
    dailySupplySideRevenue: totalFeesUSD > 0 ? totalFeesUSD * 0.8 : undefined,
  };
};

const adapter: SimpleAdapter = {
  fetch,
  version: 1,
  start: 1763942400,
  chains: [CHAIN.MONAD],
  methodology: {
    Fees: "LP fees generated by the swap transactions on Bean Exchange.",
    Revenue: "20% percent of fees to Bean Exchange.",
    ProtocolRevenue: "20% percent of fees to Bean Exchange.",
    SupplySideRevenue: "80% percent of the fees to LPs.",
  },
};

export default adapter;
