import { Adapter, FetchOptions, FetchResultV2 } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import ADDRESSES from '../../helpers/coreAssets.json';
import { METRIC } from "../../helpers/metrics";

const AmphorILHedgedWETH_contractAddress: string = '0xcDC51F2B0e5F0906f2fd5f557de49D99c34Df54e';
const AmphorLRTwstETHVault_contractAddress: string = '0x06824C27C8a0DbDe5F72f770eC82e3c0FD4DcEc3';
const AmphorPTezETHVault_contractAddress: string = '0xeEE8aED1957ca1545a0508AfB51b53cCA7e3c0d1';
const AmphorPTrsETHVault_contractAddress: string = '0xB05cABCd99cf9a73b19805edefC5f67CA5d1895E';
const AmphorPTweETHVault_contractAddress: string = '0xc69Ad9baB1dEE23F4605a82b3354F8E40d1E5966';

// Amphor vaults charge a 20% performance fee. feesInBps() on AmphorILHedgedWETH
// returns 2000 (verified on-chain); the other four vaults are uniform 20% (the
// aggregate fees/revenue ratio sits exactly on 5.00). The EpochEnd `fees` field
// is that 20% cut, so the gross yield that produced it is fees / 20% = fees * 5.
const PERFORMANCE_FEE_BPS = 2000n

const breakdownMethodology = {
    Fees: {
        [METRIC.ASSETS_YIELDS]: "Gross yield generated by the vaults, derived from the performance fee and the 20% fee rate (fees * 10000 / feesInBps).",
    },
    Revenue: {
        [METRIC.PERFORMANCE_FEES]: "20% performance fee charged by Amphor vaults at each epoch end.",
    },
    ProtocolRevenue: {
        [METRIC.PERFORMANCE_FEES]: "Performance fees directed to the Amphor treasury.",
    },
    SupplySideRevenue: {
        [METRIC.ASSETS_YIELDS]: "Net yield distributed to vault depositors (gross yield minus the performance fee).",
    },
}
const event = 'event EpochEnd(uint256 indexed timestamp,uint256 lastSavedBalance,uint256 returnedAssets,uint256 fees,uint256 totalShares)'

const addresss: string[] = [
    AmphorILHedgedWETH_contractAddress,
    AmphorLRTwstETHVault_contractAddress,
    AmphorPTezETHVault_contractAddress,
    AmphorPTrsETHVault_contractAddress,
    AmphorPTweETHVault_contractAddress
]

const fetch = async (options: FetchOptions): Promise<FetchResultV2> => {
    const logs = (await options.getLogs({
        targets: addresss,
        eventAbi: event,
        flatten: true
    }))

    const dailyFees = options.createBalances()
    const dailyRevenue = options.createBalances()
    const dailySupplySideRevenue = options.createBalances()

    const TOKENS = {
        WETH: ADDRESSES.ethereum.WETH,
    }

    logs.forEach((log) => {
        // `fees` is the 20% performance fee (protocol revenue). The gross yield
        // that produced it is fees / 20% = fees * 10000 / feesInBps, and depositors
        // keep the remainder. (Previously dailyFees used returnedAssets -
        // lastSavedBalance, which is not the gross yield and made Revenue = 5x Fees,
        // the reciprocal of the correct relationship.)
        const performanceFee = BigInt(log.fees)
        if (performanceFee <= 0n) return
        const grossYield = (performanceFee * 10000n) / PERFORMANCE_FEE_BPS
        dailyFees.add(TOKENS.WETH, grossYield, METRIC.ASSETS_YIELDS)
        dailyRevenue.add(TOKENS.WETH, performanceFee, METRIC.PERFORMANCE_FEES)
        dailySupplySideRevenue.add(TOKENS.WETH, grossYield - performanceFee, METRIC.ASSETS_YIELDS)
    })

    return {
        dailyFees,
        dailyRevenue,
        dailyProtocolRevenue: dailyRevenue,
        dailySupplySideRevenue,
    }
}

const methodology = {
    Fees: "Gross yield generated by the Amphor vaults (the 20% performance fee grossed up to the total yield).",
    Revenue: "20% performance fee kept by the Amphor treasury.",
    ProtocolRevenue: "20% performance fee kept by the Amphor treasury.",
    SupplySideRevenue: "Yield distributed to vault depositors (the gross yield minus the 20% performance fee).",
}

const adapter: Adapter = {
    version: 2,
    pullHourly: true,
    fetch,
    chains: [CHAIN.ETHEREUM],
    start: '2023-10-06',
    methodology,
    breakdownMethodology,
}

export default adapter;
