import { Adapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";


// Sources: yield split is 80% holders, 10% treasury, 10% insurance fund.
// Mint/redeem fees are documented as zero until $100m TVL, so this tracks yield distributions only.
// https://mainstreet-finance.gitbook.io/mainstreet.finance/protocol-economics-1
// https://mainstreet-finance.gitbook.io/mainstreet.finance/returns-calculation-and-distribution
// https://mainstreet-finance.gitbook.io/mainstreet.finance/risk-factors/insurance-fund
const MSUSD = "0x4ba01f22827018b4772CD326C7627FB4956A7C00";
const MSY = "0x890A5122Aa1dA30fEC4286DE7904Ff808F0bd74A";

// TODO: Add mint/redeem fees if Mainstreet enables the documented 0.2% tax after $100m TVL.
const REWARDS_RECEIVED = "event RewardsReceived(uint256 indexed amount)";
const HOLDER_SHARE = 0.8;
const INSURANCE_SHARE = 0.1;
const TREASURY_SHARE = 0.1;

const METRICS = {
  yield: "msY Strategy Yield",
  insurance: "msY Yield To Insurance Fund",
  holders: "msY Yield To Holders",
  treasury: "msY Yield To Treasury",
};

const fetch = async (options: FetchOptions) => {
  const dailySupplySideRevenue = options.createBalances();

  try {
    const logs = await options.getLogs({
      target: MSY,
      eventAbi: REWARDS_RECEIVED,
    });

    for (const log of logs) {
      dailySupplySideRevenue.add(MSUSD, log.amount, METRICS.holders);
    }
  } catch (error) {
    console.error(`[mainstreet][${options.chain}] failed to fetch RewardsReceived logs`, error);
    return {
      dailyFees: options.createBalances(),
      dailyRevenue: options.createBalances(),
      dailyProtocolRevenue: options.createBalances(),
      dailySupplySideRevenue,
    };
  }

  const dailyFees = dailySupplySideRevenue.clone(1 / HOLDER_SHARE, METRICS.yield);
  dailySupplySideRevenue.addBalances(dailyFees.clone(INSURANCE_SHARE), METRICS.insurance);

  const dailyRevenue = dailyFees.clone(TREASURY_SHARE, METRICS.treasury);

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};


const adapter: Adapter = {
  version: 2,
  fetch,
  chains: [CHAIN.ETHEREUM],
  start: "2025-12-09",
  pullHourly: true,
  methodology: {
    Fees: "Gross yield generated by Mainstreet's msY strategy vault.",
    Revenue: "10% of gross yield allocated to Mainstreet treasury.",
    ProtocolRevenue: "Treasury revenue from Mainstreet's 10% share of gross yield.",
    SupplySideRevenue: "80% of gross yield goes to msY holders and 10% goes to the insurance fund reserve.",
  },
  breakdownMethodology: {
    Fees: {
      [METRICS.yield]: "Total yield generated by the msY strategy vault ",
    },
    Revenue: {
      [METRICS.treasury]: "10% of gross yield allocated to Mainstreet treasury.",
    },
    ProtocolRevenue: {
      [METRICS.treasury]: "10% of gross yield allocated to Mainstreet treasury.",
    },
    SupplySideRevenue: {
      [METRICS.holders]: "80% of gross yield distributed to msY holders through exchange-rate appreciation.",
      [METRICS.insurance]: "10% of gross yield directed to Mainstreet's insurance fund reserve.",
    },
  },
};

export default adapter;
