/*

Infinity is a multi-LST liquidity pool

Infinity v1

10% of trading fees and withdrawal fees go to Sanctum through individual fee accounts
https://github.com/igneous-labs/S/blob/5fe9f64a00f7096317148c91789497b1a64fcb34/libs/s-controller-lib/src/consts.rs

Total fees generated by Infinity are then 10x the amount going to Sanctum which is what the query below calculates
Total revenue is what goes to Sanctum: 10% of total fees

Infinity v2

Sanctum takes a 5% cut on the total yield generated (staking + trading rewards)
--> total fees are 20x the amount going to Sanctum which is what the query below calculates

Proof that the deployed program on-chain matches code from repo
https://solscan.io/account/5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx#programVerification


*/

import {
  Dependencies,
  FetchOptions,
  SimpleAdapter,
} from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { queryDuneSql } from "../../helpers/dune";

const fetch: any = async (_a: any, _b: any, options: FetchOptions) => {
  const fees = await queryDuneSql(
    options,
    `
        WITH infv1_fees AS (
    SELECT 
      COALESCE(cast(
        sum(token_balance_change) as BIGINT
      ) * 10, 0) as infv1_fees
    FROM 
      solana.account_activity 
    WHERE 
      address IN (
        select 
          fee_account 
        from 
          dune.sanctumso.result_infinity_fee_accounts
      ) 
      AND token_balance_change > 0 
      AND block_time >= from_unixtime(${options.startTimestamp}) 
      AND block_time <= from_unixtime(${options.endTimestamp})
      AND block_time < date '2025-03-17' -- date of the v2 launch
  ), 
  infv2_fees as (
    SELECT 
      COALESCE(SUM(bytearray_to_bigint(
        bytearray_reverse(
          bytearray_substring(
            frombase58(inner_instructions[1].data), 
            2, 
            8
          )
        )
  )), 0) / 1e9 * 20 as infv2_fees -- total INF minted
    from 
      solana.instruction_calls 
    where 
      executing_account = '5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx' 
      and data = 0x19 -- withdrawProtocolFeesV2 discriminator
      AND block_time >= from_unixtime(${options.startTimestamp}) 
      AND block_time <= from_unixtime(${options.endTimestamp})
      AND block_time >= date '2025-03-17' -- date of the v2 launch
  )

  SELECT 
    infv1_fees.infv1_fees,
    infv2_fees.infv2_fees
  FROM 
    infv1_fees, infv2_fees
    `,
  );

  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const infv1Fees = fees[0].infv1_fees || 0;
  const infv2Fees = fees[0].infv2_fees || 0;
  dailyFees.addCGToken("solana", infv1Fees + infv2Fees);
  dailyRevenue.addCGToken("solana", infv1Fees * 0.1 + infv2Fees * 0.05);
 
  dailySupplySideRevenue.addBalances(dailyFees);
  dailySupplySideRevenue.subtract(dailyRevenue);

  return {
    dailyFees,
    dailyRevenue,
    dailySupplySideRevenue
  };
};

const methodology = {
  Fees: "Total Infinity fees (LPs + Sanctum)",
  Revenue: "Infinity fees going to Sanctum",
  SupplySideRevenue: "Infinity fees going to LPs",
};

const adapter: SimpleAdapter = {
  version: 1,
  fetch,
  chains: [CHAIN.SOLANA],
  dependencies: [Dependencies.DUNE],
  start: "2024-01-01", // First unstake transaction
  methodology,
  isExpensiveAdapter: true,
};

export default adapter;
