/* Hi team, this is Goosefx's other amm protocol (GAMMA).
As per the docs I created a new adapter.
Please add it to the existing goosefx protocol. */

import fetchURL from "../../utils/fetchURL"
import { SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const gooseFxEndpoint = "https://gamma-api.goosefx.io/v1/stats";

const fetch = async (timestamp: number) => {
    const res = await fetchURL(gooseFxEndpoint);
    return {
        timestamp,
        dailyVolume: res?.data.stats.stats24h.volume,
        totalVolume: res?.data.stats.stats30d.volume
    };
};

const adapter: SimpleAdapter = {
    adapter: {
        [CHAIN.SOLANA]: {
            fetch: fetch,
            runAtCurrTime: true,
            meta: {
                methodology: 'This is the volume generated by GAMMA (GooseFx AMM) & calculated by our internal api!'
            }
        },
    },
};

export default adapter;