/* Hi team, this is Goosefx's other amm protocol (GAMMA).
As per the docs I created a new adapter.
Please add it to the existing goosefx protocol. */

import fetchURL from "../../utils/fetchURL"
import { SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const gooseFxEndpoint = "https://gamma-api.goosefx.io/v1/stats";

const fetch = async () => {
    const res = await fetchURL(gooseFxEndpoint);
    return {
        dailyVolume: res?.data.stats.stats24h.volume,
    };
};

const adapter: SimpleAdapter = {
    version: 2,
    adapter: {
        [CHAIN.SOLANA]: {
            fetch: fetch,
            runAtCurrTime: true,
        },
    },
    methodology: 'This is the volume generated by GAMMA (GooseFx AMM) & calculated by our internal api!'
};

export default adapter;