import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { METRIC } from "../../helpers/metrics";
import { integrate } from "./accounting";
import { CHAIN_CONFIG, STAKING_REWARDS_CAMPAIGNS } from "./config";
import { readRatePoints, supplyEvents, trackedVaults } from "./onchain";

// Concrete vaults are ERC-4626 multi-strategy vaults. Depositor yield is the growth of each
// vault's exchange rate, measured on-chain between every share mint and burn (see accounting.ts);
// protocol revenue is the shares minted to the fee recipients; partner staking rewards campaigns
// are booked on their distribution day.

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const vaults = await trackedVaults(options);
  const events = await supplyEvents(options, vaults);
  const points = await readRatePoints(options, vaults, events);

  for (const vault of vaults) {
    const { holderYield, managementFees, performanceFees } = integrate(points.get(vault.address)!, events.get(vault.address)!.feeMints, vault);
    // `base` keys carry their own chain: converted underlying assets are priced through a mainnet token.
    const add = (balances: typeof dailyFees, amount: bigint, label: string) =>
      balances.add(vault.base, amount.toString(), { label, skipChain: true });
    add(dailyFees, holderYield, METRIC.ASSETS_YIELDS);
    add(dailySupplySideRevenue, holderYield, METRIC.ASSETS_YIELDS);
    add(dailyFees, managementFees, METRIC.MANAGEMENT_FEES);
    add(dailyRevenue, managementFees, METRIC.MANAGEMENT_FEES);
    add(dailyFees, performanceFees, METRIC.PERFORMANCE_FEES);
    add(dailyRevenue, performanceFees, METRIC.PERFORMANCE_FEES);
  }

  await addStakingRewardsCampaigns(options, [dailyFees, dailySupplySideRevenue]);

  return { dailyFees, dailyRevenue, dailySupplySideRevenue, dailyProtocolRevenue: dailyRevenue };
};

/** Campaigns whose distribution day falls in the window, in their token's units. */
async function addStakingRewardsCampaigns(options: FetchOptions, balances: ReturnType<FetchOptions['createBalances']>[]) {
  for (const campaign of STAKING_REWARDS_CAMPAIGNS) {
    if (campaign.chain !== options.chain) continue;
    const distributedAt = Math.floor(new Date(`${campaign.distributedOn}T00:00:00Z`).getTime() / 1e3);
    if (distributedAt <= options.fromTimestamp || distributedAt > options.toTimestamp) continue;
    const decimals = Number(await options.api.call({ abi: 'uint8:decimals', target: campaign.token }));
    for (const balance of balances) balance.add(campaign.token, toRawUnits(campaign.amount, decimals), METRIC.STAKING_REWARDS);
  }
}

function toRawUnits(amount: string, decimals: number): string {
  const [whole, fraction = ''] = amount.split('.');
  return BigInt(whole + fraction.padEnd(decimals, '0').slice(0, decimals)).toString();
}

const methodology = {
  Fees: 'Total yield generated by the vaults\' strategies for depositors, measured from the growth of each vault\'s exchange rate on-chain, plus protocol fees and partner staking rewards campaigns.',
  Revenue: 'Management and performance fees collected by the protocol as vault shares.',
  ProtocolRevenue: 'All revenue goes to the protocol.',
  SupplySideRevenue: 'Yield distributed to vault depositors after fees, plus partner staking rewards campaigns.',
};

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]: 'Yield from vault exchange rate growth distributed to depositors after fees.',
    [METRIC.MANAGEMENT_FEES]: 'V1 vaults: fee shares minted to the fee recipient on user transactions and harvests. V2 vaults: management fee shares.',
    [METRIC.PERFORMANCE_FEES]: 'V2 vaults: performance fee shares on net yield above the hurdle rate.',
    [METRIC.STAKING_REWARDS]: 'Partner staking rewards campaigns distributed to depositors (Berachain, Beraborrow, Movement, Corn, USD.ai, Stable, Katana), booked on their distribution day.',
  },
  Revenue: {
    [METRIC.MANAGEMENT_FEES]: 'V1 fee shares and V2 management fee shares, valued at the exchange rate when minted.',
    [METRIC.PERFORMANCE_FEES]: 'V2 performance fee shares, valued at the exchange rate when minted.',
  },
  ProtocolRevenue: {
    [METRIC.MANAGEMENT_FEES]: 'V1 fee shares and V2 management fee shares, valued at the exchange rate when minted.',
    [METRIC.PERFORMANCE_FEES]: 'V2 performance fee shares, valued at the exchange rate when minted.',
  },
  SupplySideRevenue: {
    [METRIC.ASSETS_YIELDS]: 'Yield from vault exchange rate growth distributed to depositors after fees.',
    [METRIC.STAKING_REWARDS]: 'Partner staking rewards campaigns distributed to depositors.',
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  fetch,
  adapter: CHAIN_CONFIG,
  methodology,
  breakdownMethodology,
  // Strategies realise losses (write-downs, exits below the marked rate); those are real negative yield.
  allowNegativeValue: true,
};

export default adapter;
