import { CHAIN } from "../../helpers/chains";
import { Adapter, FetchOptions, FetchResultV2 } from "../../adapters/types";

const METRICS = {
  StakingRewards: "LST Staking Rewards",
  StakingRewardsToLPs: "LST Staking Rewards To Stakers",
  PerformanceFees: "LST Performance Fees",
  TokenByBack: "Token Buy Back",
};

const methodology = {
  Fees: "Gross validator staking rewards generated by Kinetiq Launch LSTs.",
  Revenue: "10% performance fee taken on LST staking rewards (the full fee accrues to Kinetiq).",
  ProtocolRevenue: "Treasury share (default 30%) of the performance fee.",
  HoldersRevenue: "Buyback share (default 70%) of the performance fee.",
  SupplySideRevenue: "90% of staking rewards retained by LST holders.",
};

const breakdownMethodology = {
  Fees: {
    [METRICS.StakingRewards]: "Total staking rewards from Kinetiq Launch LSTs.",
  },
  Revenue: {
    [METRICS.PerformanceFees]: "Protocol takes a 10% performance fee on staking rewards.",
  },
  ProtocolRevenue: {
    [METRICS.PerformanceFees]: "Treasury share (default 30%) of the performance fee.",
  },
  HoldersRevenue: {
    [METRICS.TokenByBack]: "Buyback share (default 70%) of the performance fee.",
  },
  SupplySideRevenue: {
    [METRICS.StakingRewardsToLPs]: "90% of staking rewards retained by LST holders.",
  },
};

const FACTORY = "0x188a8CFa039C049c6B076C52164E5d51ee207a98";
const FACTORY_DEPLOY_BLOCK = 37414909;
const EXCHANGE_ROUTER = "0x06629c64AAF1639A7CDE24DFe0D1E1eD3E56BF3d";
const exchangeRateAbi =
  "function exLstToHype(address exManager, uint256 sharesIn) view returns (uint256)";
const marketBondedAbi =
  "event MarketBonded(bytes32 indexed marketId, address indexed deployer, uint256 opBond)";
const marketContractsAbi =
  "function getMarketContracts(bytes32 marketId) view returns ((address router, address exManager, address exLST, address stakingAccountant, address validatorManager, address oracleManager, address rewardShareTracker, address ghostLST, address bwq, address defaultOracle, address oracleAdapter, address launchFeeSplitter, address stakeFeesThrottle) contracts)";

// HIP-3 trading-fee revenue is not included yet.
// Deferred until the first market goes LIVE and produces real trading fees to validate against

async function fetch(options: FetchOptions): Promise<FetchResultV2> {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailyHoldersRevenue = options.createBalances();

  // Discover every bonded market and resolve its contracts (auto-tracks new LSTs).
  const logs = await options.getLogs({
    target: FACTORY,
    eventAbi: marketBondedAbi,
    fromBlock: FACTORY_DEPLOY_BLOCK,
    cacheInCloud: true,
  });
  const marketIds = [...new Set(logs.map((log: any) => log.marketId))];
  const contracts = await options.api.multiCall({
    abi: marketContractsAbi,
    calls: marketIds.map((marketId: string) => ({ target: FACTORY, params: [marketId] })),
  });
  const managers = contracts.map((c: any) => c.exManager);
  const exLSTs = contracts.map((c: any) => c.exLST);
  const rewardShareTrackers = contracts.map((c: any) => c.rewardShareTracker);

  // The performance-fee rate (rewardShareBps) and its treasury/buyback split (deployerSplitBps — both wallets are
  // Kinetiq's) are per-market configurable, so they are read on-chain rather than hardcoded.
  const rateCalls = managers.map((manager: string) => ({
    target: EXCHANGE_ROUTER,
    params: [manager, "1000000000000000000"],
  }));
  const [ratesBefore, ratesAfter, supplies, rewardShareBps, deployerSplitBps] = await Promise.all([
    options.fromApi.multiCall({ abi: exchangeRateAbi, calls: rateCalls, permitFailure: true }),
    options.toApi.multiCall({ abi: exchangeRateAbi, calls: rateCalls, permitFailure: true }),
    options.api.multiCall({ abi: "uint256:totalSupply", calls: exLSTs, permitFailure: true }),
    options.api.multiCall({
      abi: "uint256:rewardShareBps",
      calls: rewardShareTrackers,
      permitFailure: true,
    }),
    options.api.multiCall({
      abi: "uint256:deployerSplitBps",
      calls: rewardShareTrackers,
      permitFailure: true,
    }),
  ]);

  managers.forEach((_: string, i: number) => {
    if (ratesBefore[i] == null || ratesAfter[i] == null || supplies[i] == null) return;
    const exchangeRateBefore = ratesBefore[i] / 1e18;
    const exchangeRateAfter = ratesAfter[i] / 1e18;
    const totalSupply = supplies[i] / 1e18;

    const yieldAfterFees = totalSupply * (exchangeRateAfter - exchangeRateBefore);
    const feeRate = Number(rewardShareBps[i] ?? 1000) / 10000; // default 10% performance fee
    const buybackSplit = Number(deployerSplitBps[i] ?? 7000) / 10000; // default 70% to buyback, rest to treasury
    const yieldTotal = yieldAfterFees / (1 - feeRate);
    const performanceFees = yieldTotal - yieldAfterFees;
    const holdersRevenue = performanceFees * buybackSplit;
    const protocolRevenue = performanceFees - holdersRevenue;

    dailyFees.addCGToken("hyperliquid", yieldTotal, METRICS.StakingRewards);
    dailyRevenue.addCGToken("hyperliquid", performanceFees, METRICS.PerformanceFees);
    dailySupplySideRevenue.addCGToken("hyperliquid", yieldAfterFees, METRICS.StakingRewardsToLPs);
    dailyProtocolRevenue.addCGToken("hyperliquid", protocolRevenue, METRICS.PerformanceFees);
    dailyHoldersRevenue.addCGToken("hyperliquid", holdersRevenue, METRICS.TokenByBack);
  });

  return {
    dailyFees,
    dailyRevenue,
    dailySupplySideRevenue,
    dailyProtocolRevenue,
    dailyHoldersRevenue,
  };
}

const adapter: Adapter = {
  version: 2,
  pullHourly: true,
  adapter: {
    [CHAIN.HYPERLIQUID]: {
      fetch,
      start: "2026-06-10",
    },
  },
  methodology,
  breakdownMethodology,
};

export default adapter;
