import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

// https://docs.bracket.fi/product/brkteth/fees

const brktETH = '0x6C8550167BbD06D4610a6A443eCbEd84Bd1AccD6'
const protocolFeeRate = 0.0002

async function fetch(options: FetchOptions) {
    const dailyFees = options.createBalances()
    const dailyRevenue = options.createBalances()
    const dailySupplySideRevenue = options.createBalances()
    const [fromRate, toRate, totalSupply] = await Promise.all([
        options.fromApi.call({ target: brktETH, abi: "uint256:getBracketRate"}),
        options.toApi.call({ target: brktETH, abi: "uint256:getBracketRate"}),
        options.toApi.call({ target: brktETH, abi: "uint256:totalSupply"})
    ])
    const growthRate = (toRate - fromRate) / 1e18
    const fees = growthRate * totalSupply
    dailyFees.addGasToken(fees, METRIC.STAKING_REWARDS)
    const currentPeriod = options.toTimestamp - options.fromTimestamp
    const protocolFee = fees * protocolFeeRate * currentPeriod / (365 * 24 * 3600)
    dailyRevenue.addGasToken(protocolFee, METRIC.MANAGEMENT_FEES)
    dailySupplySideRevenue.addGasToken(fees - protocolFee, METRIC.STAKING_REWARDS)

    return {
        dailyFees,
        dailyRevenue,
        dailyProtocolRevenue: dailyRevenue,
        dailySupplySideRevenue
    }
}

const adapter : SimpleAdapter = {
    version: 2,
    methodology: {
        Fees: "The yield generated by the underlying assets.",
        Revenue: "The protocol charges a 0.02% annual fee on the treasury assets.",
        ProtocolRevenue: "The protocol charges a 0.02% annual fee on the treasury assets.",
        SupplySideRevenue: "The yield generated by the underlying assets minus the protocol fee",
    },
    breakdownMethodology: {
        Fees: {
            [METRIC.STAKING_REWARDS]: "The yield generated by the underlying assets.",
        },
        Revenue: {
            [METRIC.MANAGEMENT_FEES]: "The protocol charges a 0.02% annual fee on the treasury assets.",
        },
        SupplySideRevenue: {
            [METRIC.STAKING_REWARDS]: "The yield generated by the underlying assets minus the protocol fee."
        }
    },
    fetch,
    chains: [CHAIN.ETHEREUM],
    start: "2025-01-21"
}

export default adapter