import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { httpPost, } from "../../utils/fetchURL";
import { getEnv } from "../../helpers/env";
import { METRIC } from "../../helpers/metrics";

const SENTIO_API_URL =
  "https://api.sentio.xyz/v1/analytics/navi/volo-vault/sql/execute";

// One row per on-chain fee helper charge: gross_yield is the vault yield since the
// previous charge, fee_amount the performance fee actually collected.
const DAILY_FEE_SQL = `
SELECT toDate(timestamp, 'UTC') AS day, coin_symbol,
  sum(gross_yield) AS daily_yield, sum(fee_amount) AS daily_fee
FROM VaultPerformanceFee
GROUP BY day, coin_symbol ORDER BY day, coin_symbol`;

const COIN_MAP: Record<string, string> = {
  suiBTC: "bitcoin",
  XBTC: "bitcoin",
  LZWBTC: "bitcoin",
  nUSDC: "usd-coin",
  SUI: "sui",
  XAUM: "matrixdock-gold",
};

const methodology = {
  Fees: "Yield generated by Volo vault strategies.",
  Revenue: "Performance fees collected by Volo on vault yield.",
  ProtocolRevenue: "Performance fees retained by protocol.",
  SupplySideRevenue: "Vault yield left to depositors after performance fees.",
};

let data: any

const fetch = async ({ dateString, createBalances }: FetchOptions) => {
  const dailyFees = createBalances()
  const dailyRevenue = createBalances()
  const dailySupplySideRevenue = createBalances()

  // No pinned processor version: queries run against the active one, since an
  // obsolete version's data is dropped once a newer upload replaces it.
  if (!data)
    data = httpPost(
      SENTIO_API_URL,
      {
        sqlQuery: { sql: DAILY_FEE_SQL, size: 10000 },
        cachePolicy: {
          noCache: false,
          cacheTtlSecs: 1036800,
          cacheRefreshTtlSecs: 43200,
        },
        engine: "DEFAULT",
      },
      {
        headers: {
          "Content-Type": "application/json",
          "api-key": getEnv("VOLO_VAULT_API_KEY"),
        },
      }
    );

  const response: any = await data
  if (!response?.result?.rows) {
    data = undefined // do not cache a failed response for the next day
    throw new Error(`volo-vault: sentio returned no rows: ${JSON.stringify(response).slice(0, 300)}`)
  }

  for (const row of response.result.rows) {
    const coin = COIN_MAP[row.coin_symbol]
    if (row.day.split("T")[0] !== dateString || !coin) continue;

    const vaultYield = parseFloat(row.daily_yield) || 0
    const fee = parseFloat(row.daily_fee) || 0
    dailyFees.addCGToken(coin, vaultYield, METRIC.ASSETS_YIELDS);
    dailyRevenue.addCGToken(coin, fee, METRIC.PERFORMANCE_FEES);
    dailySupplySideRevenue.addCGToken(coin, vaultYield - fee, METRIC.ASSETS_YIELDS);
  }

  return {
    dailyFees,
    dailySupplySideRevenue,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailyHoldersRevenue: 0,
  };
};

const adapter: SimpleAdapter = {
  version: 1, // because we get daily data not hourly
  fetch,
  chains: [CHAIN.SUI],
  start: "2026-08-03", // first charges of the on-chain fee helpers
  methodology,
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: 'The yield generated by Volo vault strategies',
    },
    Revenue: {
      [METRIC.PERFORMANCE_FEES]: 'Performance fees collected by the protocol from vault yields'
    },
    SupplySideRevenue: {
      [METRIC.ASSETS_YIELDS]: 'Vault yield left to depositors after performance fees',
    }
  }
};

export default adapter;
