import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { httpPost, } from "../../utils/fetchURL";
import { getEnv } from "../../helpers/env";
import { METRIC } from "../../helpers/metrics";

const SENTIO_API_URL =
  "https://api.sentio.xyz/v1/analytics/navi/volo-vault/sql/execute";

const DAILY_FEE_SQL = `
WITH eod AS (
  SELECT toDate(timestamp, 'UTC') AS day, coin_symbol,
    argMax(total_active_cumulated, timestamp) AS eod_cumulated
  FROM PerformanceFeeRecord
  GROUP BY day, coin_symbol
)
SELECT day, coin_symbol,
  greatest((eod_cumulated - lag(eod_cumulated, 1, eod_cumulated) 
    OVER (PARTITION BY coin_symbol ORDER BY day)), toDecimal128(0, 18)) AS daily_fee
FROM eod ORDER BY day, coin_symbol`;

const COIN_MAP: Record<string, string> = {
  suiBTC: "bitcoin",
  XBTC: "bitcoin",
  nUSDC: "usd-coin",
};

const methodology = {
  Fees: "Performance fees collected from Volo vault yield strategies.",
  Revenue: "Volo charges a 10% fee from the total yield generated by vaults.",
  ProtocolRevenue: "Performance fees retained by protocol.",
  SupplySideRevenue: "90% of the yield generated by vaults goes to the depositors.",
};

let data: any

const fetch = async (_: any, _1: any, { dateString, createBalances }: FetchOptions) => {
  const dailyFees = createBalances()

  if (!data)
    data = httpPost(
      SENTIO_API_URL,
      {
        version: 85,
        sqlQuery: { sql: DAILY_FEE_SQL, size: 10000 },
        cachePolicy: {
          noCache: false,
          cacheTtlSecs: 1036800,
          cacheRefreshTtlSecs: 43200,
        },
        engine: "DEFAULT",
      },
      {
        headers: {
          "Content-Type": "application/json",
          "api-key": getEnv("VOLO_VAULT_API_KEY"),
        },
      }
    );

  const response: any = await data

  for (const row of response.result.rows) {
    if (row.day.split("T")[0] === dateString && COIN_MAP[row.coin_symbol]) {
      if (COIN_MAP[row.coin_symbol] === undefined) {
        console.log("[Volo-vault] Unknown coin:", row.coin_symbol);
        continue; // skip unknown coins
      }

      dailyFees.addCGToken(COIN_MAP[row.coin_symbol], parseFloat(row.daily_fee) || 0, METRIC.ASSETS_YIELDS);
    }
  }

  const dailyRevenue = dailyFees.clone(0.1, METRIC.PERFORMANCE_FEES); // 10% performance fees are revenue
  const dailySupplySideRevenue = dailyFees.clone(0.9, METRIC.ASSETS_YIELDS); // 90% of the fees goes to the depositors


  return {
    dailyFees,
    dailySupplySideRevenue,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailyHoldersRevenue: 0,
  };
};

const adapter: SimpleAdapter = {
  version: 1, // because we get daily data not hourly
  adapter: {
    [CHAIN.SUI]: {
      fetch,
      start: "2025-08-10",
    },
  },
  methodology,
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: 'The yield generated by Volo vault strategies',
    },
    Revenue: {
      [METRIC.PERFORMANCE_FEES]: '10% performance fee collected by the protocol from vault yields'
    },
    SupplySideRevenue: {
      [METRIC.ASSETS_YIELDS]: '90% of the yield goes to the depositors',
    }
  }
};

export default adapter;
