import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getERC4626VaultsYield } from "../../helpers/erc4626";
import { METRIC } from "../../helpers/metrics";

async function fetch(options: FetchOptions) {
  const sdeUsd = '0x5C5b196aBE0d54485975D1Ec29617D42D9198326'
  const dailyYield = await getERC4626VaultsYield({ options, vaults: [sdeUsd] })
  const dailyFees = options.createBalances()
  dailyFees.addBalances(dailyYield, METRIC.ASSETS_YIELDS)

  return {
    dailyFees,
    dailyRevenue: 0,
    dailyProtocolRevenue: 0,
    dailySupplySideRevenue: dailyFees,
  }
}

const methodology = {
  Fees: 'Yields generated by sdeUsd',
  SupplySideRevenue: '100% of the yields go to sdeUsd holders',
  Revenue: 'No revenue',
  ProtocolRevenue: 'No protocol revenue'
}

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]: 'Yields generated by sdeUsd',
  }
}

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.ETHEREUM],
  methodology,
  breakdownMethodology,
  start: '2024-07-16',
  deadFrom: '2025-11-02'
};

export default adapter;