import { Adapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import fetchURL from "../../utils/fetchURL";
import { METRIC } from "../../helpers/metrics";

const API_BASE = "https://inflow-vault-metrics-brnuh.ondigitalocean.app/fees";
const LIMIT = 200;

const VAULTS = [
    { vault: "usdc", cgToken: "usd-coin", decimals: 1e6 },
    { vault: "atom", cgToken: "cosmos", decimals: 1e6 },
    { vault: "btc", cgToken: "bitcoin", decimals: 1e8 },
];

const fetch = async (options: FetchOptions) => {
    const { fromTimestamp, toTimestamp, createBalances } = options;
    const dailyFees = createBalances();

    for (const { vault, cgToken, decimals } of VAULTS) {
        const url = `${API_BASE}?vault=${vault}&limit=${LIMIT}`;
        const entries: { Timestamp: number; BaseTokenAmount: number }[] = await fetchURL(url);

        const total = entries
            .filter((e) => e.Timestamp >= fromTimestamp && e.Timestamp < toTimestamp)
            .reduce((sum, e) => sum + e.BaseTokenAmount, 0);

        dailyFees.addCGToken(cgToken, total / decimals, METRIC.ASSETS_YIELDS);
    }

    return {
        dailyFees,
        dailyRevenue: 0, 
        dailyProtocolRevenue: 0, 
        dailySupplySideRevenue: dailyFees
    };
};

const methodology = {
    Fees: "Yields generated by valuts using delta neutral strategies",
    Revenue: "No revenue is collected from the vaults",
    ProtocolRevenue: "No revenue is collected from the vaults",
    SupplySideRevenue: "All the yields are distributed to the vault depositors",
};

const adapter: Adapter = {
    version: 2,
    fetch,
    methodology,
    chains: [CHAIN.NEUTRON],
    start: "2026-03-05",
};

export default adapter;
