import { request, gql } from "graphql-request";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

const endpoint = "https://v2.api.liqwid.finance/graphql";

const query = gql`
  query Fees($startDate: String!, $endDate: String!) {
    analytics {
      fees(startDate: $startDate, endDate: $endDate) {
        breakdown {
          borrowInterestAccrued
          borrowInterestAccruedForSupplySide
          borrowInterestAccruedForHolders
          borrowInterestAccruedForProtocol
          loanOriginationFees
          loanOriginationFeesForProtocol
          loanOriginationFeesForHolders
          liquidationBonus
          adaStakingRewards
        }
      }
    }
  }
`;

const ORIGINATION_FEES = "Origination Fees";

const fetch = async (options: FetchOptions) => {
  const startDate = new Date(options.startTimestamp * 1000).toISOString();
  const endDate = new Date(options.endTimestamp * 1000).toISOString();

  const data = await request(endpoint, query, { startDate, endDate }, { "X-App-Source": "DefiLlama" });
  const breakdown = data.analytics.fees.breakdown;

  const dailyFees = options.createBalances();
  dailyFees.addUSDValue(breakdown.borrowInterestAccrued, METRIC.BORROW_INTEREST);
  dailyFees.addUSDValue(breakdown.loanOriginationFees, ORIGINATION_FEES);
  dailyFees.addUSDValue(breakdown.liquidationBonus, METRIC.LIQUIDATION_FEES);
  dailyFees.addUSDValue(breakdown.adaStakingRewards, METRIC.STAKING_REWARDS);

  // ADA staking rewards are not paid by borrowers, so they are excluded from user fees
  const dailyUserFees = options.createBalances();
  dailyUserFees.addUSDValue(breakdown.borrowInterestAccrued, METRIC.BORROW_INTEREST);
  dailyUserFees.addUSDValue(breakdown.loanOriginationFees, ORIGINATION_FEES);
  dailyUserFees.addUSDValue(breakdown.liquidationBonus, METRIC.LIQUIDATION_FEES);

  const dailySupplySideRevenue = options.createBalances();
  dailySupplySideRevenue.addUSDValue(breakdown.borrowInterestAccruedForSupplySide, METRIC.BORROW_INTEREST);
  dailySupplySideRevenue.addUSDValue(breakdown.liquidationBonus, METRIC.LIQUIDATION_FEES);
  dailySupplySideRevenue.addUSDValue(breakdown.adaStakingRewards, METRIC.STAKING_REWARDS);

  const dailyProtocolRevenue = options.createBalances();
  dailyProtocolRevenue.addUSDValue(breakdown.borrowInterestAccruedForProtocol, METRIC.BORROW_INTEREST);
  dailyProtocolRevenue.addUSDValue(breakdown.loanOriginationFeesForProtocol, ORIGINATION_FEES);

  const dailyHoldersRevenue = options.createBalances();
  dailyHoldersRevenue.addUSDValue(breakdown.borrowInterestAccruedForHolders, METRIC.BORROW_INTEREST);
  dailyHoldersRevenue.addUSDValue(breakdown.loanOriginationFeesForHolders, ORIGINATION_FEES);

  const dailyRevenue = options.createBalances();
  dailyRevenue.addBalances(dailyProtocolRevenue);
  dailyRevenue.addBalances(dailyHoldersRevenue);

  return {
    dailyFees,
    dailyUserFees,
    dailyRevenue,
    dailyProtocolRevenue,
    dailyHoldersRevenue,
    dailySupplySideRevenue,
  };
};

const adapter: SimpleAdapter = {
  version: 1,
  chains: [CHAIN.CARDANO],
  fetch,
  start: "2026-01-01",
  pullHourly: false,
  methodology: {
    Fees: "Total fees generated by the protocol: interest accrued by borrowers, loan origination fees, liquidation bonuses and ADA staking rewards earned on assets held in the markets.",
    SupplySideRevenue: "Portion of fees distributed to lenders supplying assets to the markets.",
    Revenue: "Portion of fees kept by the protocol, split between the Liqwid DAO treasury and LQ stakers.",
    ProtocolRevenue: "Portion of fees allocated to the Liqwid DAO treasury.",
    HoldersRevenue: "Portion of fees distributed to LQ stakers.",
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.BORROW_INTEREST]: "Interest accrued by borrowers across all Liqwid markets.",
      [ORIGINATION_FEES]: "Upfront fees charged to borrowers when loans are originated.",
      [METRIC.LIQUIDATION_FEES]: "Liquidation bonuses paid by borrowers whose positions are liquidated.",
      [METRIC.STAKING_REWARDS]: "ADA staking rewards earned on ADA supplied to the protocol.",
    },
    SupplySideRevenue: {
      [METRIC.BORROW_INTEREST]: "Share of borrow interest distributed to lenders.",
      [METRIC.LIQUIDATION_FEES]: "Liquidation bonuses paid to liquidators.",
      [METRIC.STAKING_REWARDS]: "ADA staking rewards distributed to ADA suppliers.",
    },
    Revenue: {
      [METRIC.BORROW_INTEREST]: "Share of borrow interest kept by the DAO treasury and distributed to LQ stakers.",
      [ORIGINATION_FEES]: "Share of loan origination fees kept by the DAO treasury and distributed to LQ stakers.",
    },
    ProtocolRevenue: {
      [METRIC.BORROW_INTEREST]: "Share of borrow interest allocated to the Liqwid DAO treasury.",
      [ORIGINATION_FEES]: "Share of loan origination fees allocated to the Liqwid DAO treasury.",
    },
    HoldersRevenue: {
      [METRIC.BORROW_INTEREST]: "Share of borrow interest distributed to LQ stakers.",
      [ORIGINATION_FEES]: "Share of loan origination fees distributed to LQ stakers.",
    },
  },
};

export default adapter;
