import { SimpleAdapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

// Theo Straddle Vault addresses
const vaults: Record<string, string[]> = {
  [CHAIN.ETHEREUM]: [
    "0xd912325C960F1A6276F1E905d2f7715bD3d5C06d",
    "0x18e0C17bbbdf792925C2Af863570e0e6709DCdB0",
    "0x022D97090127eC95257B1cD844EBBfDCD57c50cE",
    "0xA3819f9a12CA6abeFcFd325B7d78207cdd4Bd9c3",
    "0x0B75e167F8A37179b7044414EE43e94cabeAA2FA",
  ],
  [CHAIN.ARBITRUM]: [
    "0xF37Fe9396Bb95f7823A29090c939847f1817bC8a",
    "0x4fE17dEFc597cC3bD6fBe16135d8Ac42D421907e",
    "0x3ca8F12D7B376E9Ef338d1C432CA1b51DD319009",
    "0x54602E5cBa09e01EeE9B2050F1F4f0Dc902CeE34",
  ],
  [CHAIN.BASE]: [
    "0x83C6aC60Cfb20a0dF00705A78263B88878EC19b4",
    "0xf677A02A91622E2a3ff5923c6530D383C29b0983",
    "0x0275A54EAD26a237803D8Cc6E0d63c954ad98bfE",
  ],
  [CHAIN.LINEA]: [
    "0xcF101e13b5181f79094B0726B03e89d1cB95b28C",
  ],
};

async function fetch(options: FetchOptions) {
  const dailyFees = options.createBalances();

  const startPrices = await options.fromApi.multiCall({
    abi: "function pricePerShare() view returns (uint256)",
    calls: vaults[options.chain],
    permitFailure: true,
  });

  const endPrices = await options.toApi.multiCall({
    abi: "function pricePerShare() view returns (uint256)",
    calls: vaults[options.chain],
    permitFailure: true,
  });

  const vaultParams = await options.api.multiCall({
    abi: "function vaultParams() view returns (uint8 decimals, address asset, uint56 minimumSupply, uint104 cap)",
    calls: vaults[options.chain],
    permitFailure: true,
  });

  const startSupplies = await options.fromApi.multiCall({
    abi: "uint256:totalSupply",
    calls: vaults[options.chain],
    permitFailure: true,
  });

  for (let i = 0; i < vaults[options.chain].length; i++) {
    const startPrice = startPrices[i];
    const endPrice = endPrices[i];
    const params = vaultParams[i];
    const totalSupply = startSupplies[i];
    
    if (!startPrice || !endPrice || !params || !totalSupply) {
      continue;
    }

    const decimals = BigInt(10**Number(params.decimals))
    
    // Calculate price appreciation and multiply by end supply to get yield in asset terms
    const priceAppreciation = BigInt(endPrice) - BigInt(startPrice);
    const tradingYield = (priceAppreciation * BigInt(totalSupply)) / decimals;
    
    dailyFees.add(params.asset, tradingYield);
  }

  return {
    dailyFees,
    dailySupplySideRevenue: dailyFees,
    dailyRevenue: 0,
  };
}

const methodology = {
  Fees: "Trading PnL generated by Theo straddle vaults, PnL accrues to depositors.",
  Revenue: "No revenue.",
  SupplySideRevenue: "Vault depositor PnL as yield on deposited assets.",
};

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  adapter: {
    [CHAIN.ETHEREUM]: { start: '2024-07-21' },
    [CHAIN.ARBITRUM]: { start: '2024-11-14' },
    [CHAIN.BASE]: { start: '2024-11-21' },
    [CHAIN.LINEA]: { start: '2025-03-13' },
  },
  methodology,
  allowNegativeValue: true, // Straddle vaults can have losing days; ignoring losses would give inaccurate total fees
};

export default adapter;