import { Chain, FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

interface ChainConfig {
  diamond: string;
  start: string;
}

const diamonds: Record<Chain, ChainConfig > = {
  [CHAIN.COTI]: {
    diamond: "0x2Ecc7da3Cc98d341F987C85c3D9FC198570838B5",
    start: '2025-05-20'
  },
  [CHAIN.BASE]: {
    diamond: '0x91Cf2D8Ed503EC52768999aA6D8DBeA6e52dbe43',
    start: '2024-10-13'
  },
  [CHAIN.BSC]: {
    diamond: '0x9a9f48888600fc9c05f11e03eab575ebb2fc2c8f',
    start: '2024-10-13'
  },
  [CHAIN.MANTLE]: {
    diamond: '0x2Ecc7da3Cc98d341F987C85c3D9FC198570838B5',
    start: '2024-10-13'
  },
  [CHAIN.MODE]: {
    diamond: '0x3d17f073cCb9c3764F105550B0BCF9550477D266',
    start: '2024-10-13'
  },
  [CHAIN.ARBITRUM]: {
    diamond: '0x8f06459f184553e5d04f07f868720bdacab39395',
    start: '2024-10-13'
  },
  [CHAIN.POLYGON]: {
    diamond: '0x976c87Cd3eB2DE462Db249cCA711E4C89154537b',
    start: '2025-09-30'
  },
  [CHAIN.BERACHAIN]: {
    diamond: '0x3d17f073cCb9c3764F105550B0BCF9550477D266',
    start: '2025-02-07'
  },
  [CHAIN.SONIC]: {
    diamond: '0x803de354cbd853D9aE3BC58131A5D538DE7a72E3',
    start: '2025-06-30'
  },
}

const openPositionEvent =
  "event OpenPosition(uint256 quoteId, address partyA, address partyB, uint256 filledAmount, uint256 openedPrice)";

const fillCloseRequestEvent =
  "event FillCloseRequest(uint256 quoteId, address partyA, address partyB, uint256 filledAmount, uint256 closedPrice, uint8 orderType, uint256 closeId)";

const forceClosePositionEvent =
  "event ForceClosePosition(uint256 quoteId, address partyA, address partyB, uint256 filledAmount, uint256 closedPrice, uint8 orderType, uint256 closeId)";

const emergencyClosePositionEvent =
  "event EmergencyClosePosition(uint256 quoteId, address partyA, address partyB, uint256 filledAmount, uint256 closedPrice, uint8 orderType, uint256 closeId)";

const fetch = async (options: FetchOptions) => {
  const { getLogs } = options;
  const dailyVolume = options.createBalances()
  const { diamond } = diamonds[options.chain]
  const [openLogs, closeLogs, forceCloseLogs, emergencyCloseLogs] =
    await Promise.all([
      getLogs({ target: diamond, eventAbi: openPositionEvent }),
      getLogs({ target: diamond, eventAbi: fillCloseRequestEvent }),
      getLogs({ target: diamond, eventAbi: forceClosePositionEvent }),
      getLogs({ target: diamond, eventAbi: emergencyClosePositionEvent }),
    ]);

  for (const log of openLogs) {
    const amount = Number(log.filledAmount) / 1e18
    const price = Number(log.openedPrice) / 1e18
    dailyVolume.addUSDValue(amount * price)
  }
  for (const log of [...closeLogs, ...forceCloseLogs, ...emergencyCloseLogs]) {
    const amount = Number(log.filledAmount) / 1e18
    const price = Number(log.closedPrice) / 1e18
    dailyVolume.addUSDValue(amount * price)
  }

  return {
    dailyVolume,
  };
};

const methodology = {
  Volume: 'Total volume generated by builders through Symmio.',
}

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  adapter: Object.fromEntries(Object.entries(diamonds).map(([chain, { start }]) => [chain, { fetch, start, meta: { methodology } }]))
};

export default adapter;
