import { SimpleAdapter } from "../adapters/types";
import {
	AERODROME_METRIC,
	aerodromeV2Exports,
	type AerodromeChainConfig
} from "../helpers/aerodrome";
import { createFactoryExports } from "./registry";

const defaultMethodology = {
	Fees: "Total swap fees paid by traders. Fees are applied per swap based on pool type: stable pools (sAMM) and volatile pools (vAMM), with possible per-pool overrides.",
	Revenue:
		"Total voter share of swap fees from LPs staked in gauges, distributed through the zero-leak model. Computed per pool as: fees × gaugeShare.",
	HoldersRevenue: "Swap fees from LPs in gauges and bribes from NotifyReward events.",
	SupplySideRevenue:
		"Swap fees earned by unstaked LPs. Computed as: fees × (1 − gaugeShare). No additional protocol rake module is applied, so unstaked LPs receive their full remaining share of fees.",
	TokenIncentives:
		"Token emissions distributed to LPs staking in gauges. Rewards are calculated per epoch using a gauge-specific emission rate, then streamed over the epoch duration."
};

const defaultBreakdownMethodology = {
	Fees: {
		[AERODROME_METRIC.SWAP_FEES]: "Total trading fees paid by users across all pools."
	},
	Revenue: {
		[AERODROME_METRIC.VOTER_FEES]:
			"Portion of swap fees generated by LPs staked in gauges and distributed to voters."
	},
	HoldersRevenue: {
		[AERODROME_METRIC.VOTER_FEES]:
			"Portion of swap fees generated by LPs staked in gauges and distributed to voters.",
		[AERODROME_METRIC.BRIBES_REVENUE]:
			"Token incentives distributed to voters based on gauge voting."
	},
	SupplySideRevenue: {
		[AERODROME_METRIC.LP_FEES]:
			"Portion of swap fees earned by LPs whose liquidity is not staked in gauges, and claimable directly from pools."
	},
	TokenIncentives: {
		[AERODROME_METRIC.LP_GAUGE_REWARDS]:
			"Token emissions distributed to LPs staking liquidity in gauges."
	}
};

interface ProtocolConfig {
	adapterParams?: SimpleAdapter;
	chains: Record<string, AerodromeChainConfig>;
}

const protocols: Record<string, ProtocolConfig> = {};

export const { protocolList, getAdapter } = createFactoryExports(
	Object.fromEntries(
		Object.entries(protocols).map(([protocolName, protocolConfig]) => [
			protocolName,
			aerodromeV2Exports(protocolConfig.chains, {
				methodology: defaultMethodology,
				breakdownMethodology: defaultBreakdownMethodology,
				...protocolConfig.adapterParams
			})
		])
	)
);
