import { SimpleAdapter } from "../adapters/types";
import {
	AERODROME_METRIC,
	aerodromeV3Exports,
	type AerodromeChainConfig
} from "../helpers/aerodrome";
import { createFactoryExports } from "./registry";

const defaultMethodology = {
	Fees: "Total swap fees paid by traders. Per pool fee rate (tickSpacing-based default, customizable) applied to each swap's input amount.",
	Revenue:
		"Total voter share of swap fees, equal to HoldersRevenue, distributed through the zero-leak model.",
	HoldersRevenue:
		"Rewards include swap fees from LPs staked in gauges and rake fees collected from unstaked LP positions (10% by default), derived from changes in accumulated gauge fees between blocks together with fee collection events, while bribes are accounted for separately through reward notification events.",
	SupplySideRevenue: "Unstaked LPs swap fee share after rake: Fees − HoldersRevenue.",
	TokenIncentives:
		"Token emissions distributed to LPs staking in gauges. Rewards are calculated per epoch using a gauge-specific emission rate, then streamed over the epoch duration."
};

const defaultBreakdownMethodology = {
	Fees: {
		[AERODROME_METRIC.SWAP_FEES]: "Total trading fees paid by users across all pools."
	},
	Revenue: {
		[AERODROME_METRIC.VOTER_FEES]:
			"Portion of swap fees generated by LPs staked in gauges, plus rake fees collected from unstaked LP positions, distributed to voters."
	},
	HoldersRevenue: {
		[AERODROME_METRIC.VOTER_FEES]:
			"Portion of swap fees generated by LPs staked in gauges, plus rake fees collected from unstaked LP positions, distributed to voters",
		[AERODROME_METRIC.BRIBES_REVENUE]:
			"Token incentives distributed to voters based on gauge voting."
	},
	SupplySideRevenue: {
		[AERODROME_METRIC.LP_FEES]:
			"Portion of swap fees generated by unstaked LP positions, after rake allocation to gauges, claimable directly from pools."
	},
	TokenIncentives: {
		[AERODROME_METRIC.LP_GAUGE_REWARDS]:
			"Token emissions distributed to LPs staking liquidity in gauges."
	}
};

interface ProtocolConfig {
	adapterParams?: SimpleAdapter;
	chains: Record<string, AerodromeChainConfig>;
}

const protocols: Record<string, ProtocolConfig> = {};

export const { protocolList, getAdapter } = createFactoryExports(
	Object.fromEntries(
		Object.entries(protocols).map(([protocolName, protocolConfig]) => [
			protocolName,
			aerodromeV3Exports(protocolConfig.chains, {
				methodology: defaultMethodology,
				breakdownMethodology: defaultBreakdownMethodology,
				...protocolConfig.adapterParams
			})
		])
	)
);
