import { blockscoutFeeAdapter2 } from "../helpers/blockscoutFees";
import { CHAIN } from "../helpers/chains";
import { METRIC } from "../helpers/metrics";
import { createFactoryExports } from "./registry";

// Maps protocol name -> chain string for blockscoutFeeAdapter2
const protocolChainMap: Record<string, string> = {
  "acala": CHAIN.ACALA,
  "ancient8": CHAIN.ANCIENT8,
  "apechain": CHAIN.APECHAIN,
  "aurora": CHAIN.AURORA,
  "bitcichain": CHAIN.BITCICHAIN,
  "bitgert": CHAIN.BITGERT,
  "canto": CHAIN.CANTO,
  "celo": CHAIN.CELO,
  "chiliz": CHAIN.CHILIZ,
  "corn": CHAIN.CORN,
  "cronos": CHAIN.CRONOS,
  "ethereumclassic": CHAIN.ETHEREUM_CLASSIC,
  "etherlink": CHAIN.ETHERLINK,
  "fantom": CHAIN.FANTOM,
  "flare": CHAIN.FLARE,
  "fuse": CHAIN.FUSE,
  "gravity": CHAIN.GRAVITY,
  "harmony": CHAIN.HARMONY,
  "hashkey": CHAIN.HASHKEY,
  "hemi": CHAIN.HEMI,
  "imx": CHAIN.IMX,
  "iota_evm": CHAIN.IOTAEVM,
  "karak": CHAIN.KARAK,
  "kardia": CHAIN.KARDIA,
  "kcc": CHAIN.KCC,
  "lightlink": CHAIN.LIGHTLINK_PHOENIX,
  "lisk": CHAIN.LISK,
  "metis": CHAIN.METIS,
  "mixin": CHAIN.MIXIN,
  "mode": CHAIN.MODE,
  "nuls": CHAIN.NULS,
  "oasys": CHAIN.OAS,
  "redstone": CHAIN.REDSTONE,
  "reya": CHAIN.REYA,
  "rootstock": CHAIN.ROOTSTOCK,
  "shimmer_evm": CHAIN.SHIMMER_EVM,
  "story": CHAIN.STORY,
  "swellchain": CHAIN.SWELLCHAIN,
  "syscoin": CHAIN.SYSCOIN,
  "telos": CHAIN.TELOS,
  "thundercore": CHAIN.THUNDERCORE,
  "velas": CHAIN.VELAS,
  "winr": CHAIN.WINR,
  "worldchain": CHAIN.WC,
  "xdai": CHAIN.XDAI,
  "zeta": CHAIN.ZETA,
  "astar": CHAIN.ASTAR,
  "plume": CHAIN.PLUME,
  "goat": CHAIN.GOAT,
  "somnia": CHAIN.SOMNIA,
  "energyweb": CHAIN.ENERGYWEB,
  "superposition": CHAIN.SUPERPOSITION,
  "sanko": CHAIN.SANKO,
  "appchain": CHAIN.APPCHAIN,
  "xrplevm": CHAIN.XRPL_EVM,
  "alienx": CHAIN.ALIENX,
  "adventure-layer": CHAIN.ADVENTURE_LAYER,
  "deri-chain": CHAIN.DERI_CHAIN,
  "earnm": CHAIN.EARNM,
  "duck-chain": CHAIN.DUCKCHAIN,
  "edu-chain": CHAIN.EDU_CHAIN,
  "ethereal": CHAIN.ETHEREAL,
  "eventum": CHAIN.EVENTUM,
  "everclear": CHAIN.EVERCLEAR,
  "flynet": CHAIN.FLYNET,
  "hpp": CHAIN.HPP,
  "mind-network": CHAIN.MIND_NETWORK,
  "molten-network": CHAIN.MOLTEN_NETWORK,
  "syndicate": CHAIN.SYNDICATE,
  "xchain": CHAIN.XCHAIN,
  "capx": CHAIN.CAPX,
  "rari": CHAIN.RARI,
  "shibarium": CHAIN.SHIBARIUM,
  "vana": CHAIN.VANA,
  "neo-x-mainnet": CHAIN.NEO_X_MAINNET,
  "kub": CHAIN.KUB,
  "stratis": CHAIN.STRATIS,
  "superseed": CHAIN.SSEED,
  "swan": CHAIN.SWAN,
  "sx-network": CHAIN.SX,
  "tac": CHAIN.TAC,
  "unit-zero": CHAIN.UNIT0,
  "viction": CHAIN.TOMOCHAIN,
  "vinu": CHAIN.VINUCHAIN,
  "zilliqa": CHAIN.ZILLIQA,
  "matchain": CHAIN.MATCHAIN,
  "neon": CHAIN.NEON,
  "numbers": CHAIN.NUMBERS,
  "omax": CHAIN.OMAX,
  "onus": CHAIN.ONUS,
  "orderly-network": CHAIN.ORDERLY,
  "perennial-chain": CHAIN.PERENNIAL,
  "prom": CHAIN.PROM,
  "q-protocol": CHAIN.Q_PROTOCOL,
  "rollux": CHAIN.ROLLUX,
  "saakuru": CHAIN.SAAKURU,
  "satoshivm": CHAIN.SVM,
  "shape": CHAIN.SHAPE,
  "songbird": CHAIN.SONGBIRD,
  "genesys": CHAIN.GENESYS,
  "grx-chain": CHAIN.GRX,
  "joc": CHAIN.JOC,
  "karura": CHAIN.KARURA,
  "loop": CHAIN.LOOP,
  "cross": CHAIN.CROSS,
  "doma": CHAIN.DOMA,
  "endurance": CHAIN.ENDURANCE,
  "exsat": CHAIN.EXSAT,
  "kroma": CHAIN.KROMA,
  "eni": CHAIN.ENI,
}

const deadFromMap: Record<string, string> = {
  "kroma": "2025-06-30",
}

const methodologyMap: Record<string, any> = {
  "somnia": {
    methodology: {
      Fees: 'Total SOMI gas fees paid by users (gas usage × gas unit price, after any discounts)',
      Revenue: '50% of total fees are burned',
      HoldersRevenue: '50% of total fees are burned',
    },
    breakdownMethodology: {
      Fees: { [METRIC.TRANSACTION_GAS_FEES]: 'Total SOMI fees paid by users' },
      Revenue: { [METRIC.TRANSACTION_GAS_FEES]: '50% share of total SOMI fees will be burned' },
      HoldersRevenue: { [METRIC.TRANSACTION_GAS_FEES]: '50% share of total SOMI fees will be burned' },
    },
  },
}

const protocols: Record<string, any> = {}
for (const [name, chain] of Object.entries(protocolChainMap)) {
  const adapter = blockscoutFeeAdapter2(chain)
  if (deadFromMap[name]) (adapter as any).deadFrom = deadFromMap[name]
  const extra = methodologyMap[name]
  if (extra) Object.assign(adapter, extra)
  protocols[name] = adapter
}

export const { protocolList, getAdapter } = createFactoryExports(protocols)
