import { blockscoutFeeAdapter2 } from "../helpers/blockscoutFees";
import { METRIC } from "../helpers/metrics";
import { createFactoryExports } from "./registry";

// Maps protocol name -> chain string for blockscoutFeeAdapter2
const protocolChainMap: Record<string, string> = {
  "acala": "acala",
  "ancient8": "ancient8",
  "apechain": "apechain",
  "aurora": "aurora",
  "bitcichain": "bitcichain",
  "bitgert": "bitgert",
  "canto": "canto",
  "celo": "celo",
  "chiliz": "chz",
  "corn": "corn",
  "cronos": "cronos",
  "ethereumclassic": "ethereumclassic",
  "etherlink": "etlk",
  "fantom": "fantom",
  "filecoin": "filecoin",
  "flare": "flare",
  "fuse": "fuse",
  "gravity": "gravity",
  "harmony": "harmony",
  "hashkey": "hsk",
  "hemi": "hemi",
  "imx": "imx",
  "iota_evm": "iotaevm",
  "karak": "karak",
  "kardia": "kardia",
  "kcc": "kcc",
  "lightlink": "lightlink_phoenix",
  "lisk": "lisk",
  "metis": "metis",
  "mixin": "mixin",
  "mode": "mode",
  "nuls": "nuls",
  "oasys": "oas",
  "redstone": "redstone",
  "reya": "reya",
  "rootstock": "rsk",
  "shimmer_evm": "shimmer_evm",
  "story": "sty",
  "swellchain": "swellchain",
  "syscoin": "syscoin",
  "telos": "telos",
  "thundercore": "thundercore",
  "velas": "velas",
  "winr": "winr",
  "worldchain": "wc",
  "xdai": "xdai",
  "zeta": "zeta",
  "astar": "astar",
  "plume": "plume_mainnet",
  "goat": "goat",
  "somnia": "somnia",
  "energyweb": "energyweb",
  "superposition": "spn",
  "sanko": "sanko",
  "appchain": "appchain",
  "xrplevm": "xrplevm",
  "alienx": "alienx",
  "adventure-layer": "adventure_layer",
  "deri-chain": "deri_chain",
  "earnm": "earnm",
  "duck-chain": "duckchain",
  "edu-chain": "occ",
  "ethereal": "ethereal",
  "eventum": "eventum",
  "everclear": "everclear",
  "flynet": "flynet",
  "hpp": "hpp",
  "mind-network": "mind_network",
  "molten-network": "molten_network",
  "syndicate": "syndicate",
  "xchain": "xchain",
  "capx": "capx",
  "rari": "rari",
  "shibarium": "shibarium",
  "vana": "vana",
  "neo-x-mainnet": "neo_x_mainnet",
  "kub": "kub",
  "stratis": "stratis",
  "superseed": "sseed",
  "swan": "swan",
  "sx-network": "sx",
  "tac": "tac",
  "unit-zero": "unit0",
  "viction": "tomochain",
  "vinu": "vinu",
  "zilliqa": "zilliqa",
  "matchain": "matchain",
  "neon": "neon_evm",
  "numbers": "numbers",
  "omax": "omax",
  "onus": "onus",
  "orderly-network": "orderly",
  "perennial-chain": "perennial",
  "prom": "prom",
  "q-protocol": "q",
  "rollux": "rollux",
  "saakuru": "saakuru",
  "satoshivm": "svm",
  "shape": "shape",
  "songbird": "songbird",
  "genesys": "genesys",
  "grx-chain": "grx",
  "joc": "joc",
  "karura": "karura",
  "loop": "loop",
  "cross": "cross",
  "doma": "doma",
  "endurance": "endurance",
  "exsat": "xsat",
  "kroma": "kroma",
}

const deadFromMap: Record<string, string> = {
  "kroma": "2025-06-30",
}

const methodologyMap: Record<string, any> = {
  "somnia": {
    methodology: {
      Fees: 'Total SOMI gas fees paid by users (gas usage × gas unit price, after any discounts)',
      Revenue: '50% of total fees are burned',
      HoldersRevenue: '50% of total fees are burned',
    },
    breakdownMethodology: {
      Fees: { [METRIC.TRANSACTION_GAS_FEES]: 'Total SOMI fees paid by users' },
      Revenue: { [METRIC.TRANSACTION_GAS_FEES]: '50% share of total SOMI fees will be burned' },
      HoldersRevenue: { [METRIC.TRANSACTION_GAS_FEES]: '50% share of total SOMI fees will be burned' },
    },
  },
}

const protocols: Record<string, any> = {}
for (const [name, chain] of Object.entries(protocolChainMap)) {
  const adapter = blockscoutFeeAdapter2(chain)
  if (deadFromMap[name]) (adapter as any).deadFrom = deadFromMap[name]
  const extra = methodologyMap[name]
  if (extra) Object.assign(adapter, extra)
  protocols[name] = adapter
}

export const { protocolList, getAdapter } = createFactoryExports(protocols)
