import { CHAIN } from "../../helpers/chains";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { queryEvents } from "../../helpers/sui";

// ggSUI Vault package
const GGSUI_PACKAGE = "0x578faf35a355a272711f97f4cbb77d8060e35dd4042c0b13da9fdf7b640dbc58";

// Safe wrapper: queryEvents crashes on empty results (data[data.length-1] is undefined)
async function safeQueryEvents(params: any): Promise<any[]> {
  try {
    return await queryEvents(params);
  } catch {
    return [];
  }
}

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  // TotalRewardsUpdated: emitted when validator rewards are refreshed each epoch
  //
  // Fields:
  //   old_sui_supply  – total_sui_supply BEFORE validator refresh
  //   new_sui_supply  – total_sui_supply AFTER validator refresh (GROSS, fee NOT deducted)
  //   fees_charged    – protocol fee = (new - old) * protocol_fee_percent / 10000
  //   addon_sui_rewards – current addon balance (marketplace share + redemption fees)
  //
  // IMPORTANT:
  //   • new_sui_supply is GROSS — fees are tracked in uncollected_protocol_fees, not deducted yet
  //   • addon_sui_rewards is NOT included here to avoid double-counting with marketplace adapter
  //     (marketplace adapter already counts the 15% ggSUI share as its own fee distribution)
  const rewardEvents = await safeQueryEvents({
    eventType: `${GGSUI_PACKAGE}::vault::TotalRewardsUpdated`,
    options,
  });

  for (const e of rewardEvents) {
    const grossRewards = Number(e.new_sui_supply) - Number(e.old_sui_supply);
    const protocolFee = Number(e.fees_charged);

    if (grossRewards > 0) {
      // dailyFees = total staking rewards generated (GROSS, before protocol cut)
      dailyFees.addGasToken(grossRewards);
      // dailyRevenue = protocol fee (10% of staking rewards)
      dailyRevenue.addGasToken(protocolFee);
      // dailySupplySideRevenue = net rewards to ggSUI holders
      dailySupplySideRevenue.addGasToken(grossRewards - protocolFee);
    }
  }

  // UserUnstakedInstantly: redemption fee on instant unstakes (0.01%)
  // Fee goes to addon_staking_rewards → redistributed to all stakers (supply side)
  const instantUnstakeEvents = await safeQueryEvents({
    eventType: `${GGSUI_PACKAGE}::vault::UserUnstakedInstantly`,
    options,
  });

  for (const e of instantUnstakeEvents) {
    const fee = Number(e.redemption_fees);
    if (fee > 0) {
      dailyFees.addGasToken(fee);
      dailySupplySideRevenue.addGasToken(fee);
    }
  }

  return {
    dailyFees,
    dailyUserFees: dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Total staking rewards generated by ggSUI vault validators (gross, before protocol cut) plus redemption fees from instant unstakes.",
  Revenue: "10% protocol fee charged on validator staking rewards. Flows to FeeCollector then split 50/50 between SUI treasury (team) and HONEY buybacks.",
  ProtocolRevenue: "Protocol fee on staking rewards (10% of gross validator rewards).",
  SupplySideRevenue: "Net staking rewards distributed to ggSUI holders (90% of validator rewards) plus 100% of instant unstake redemption fees.",
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.SUI]: {
      fetch,
      start: "2025-01-01",
    },
  },
  methodology,
};

export default adapter;
