// DefiLlama Fees / Revenue Adapter for GAIB
// Repo: DefiLlama/dimension-adapters
// Path: fees/gaib/index.ts
//
// Fees     = Gross yield generated by sAID vault (totalAssets growth)
// Revenue  = Protocol spread — what GAIB keeps (~20% of gross yield)
//
// Derived from live data:
//   Gross APR: 14.82%  →  Net APR: 11.85%
//   Spread = 1 - (11.85 / 14.82) ≈ 20.04%

import { Adapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const SAID_VAULT = "0xB3B3c527BA57cd61648e2EC2F5e006A0B390A9F8";
const DAI = "0x6B175474E89094C44Da98b954EedeAC495271d0F";

const ONE = BigInt(1e18);
// Protocol fee ~20% of gross yield — governance-adjustable on-chain
const PROTOCOL_FEE_BPS = 2000n;
const BPS = 10000n;

const fetch = async (options: FetchOptions) => {
  const { api, fromApi, createBalances } = options;

  const dailyFees = createBalances();
  const dailyRevenue = createBalances();

  // Share price (AID per 1 sAID) at end and start of period
  // NAV updates occur when yield is injected, so priceDelta will be zero on non-update days
  const priceEnd = await api.call({ abi: "function convertToAssets(uint256) view returns (uint256)", target: SAID_VAULT, params: [ONE.toString()] });
  const priceStart = await fromApi.call({ abi: "function convertToAssets(uint256) view returns (uint256)", target: SAID_VAULT, params: [ONE.toString()] });

  // Start-of-period supply avoids overstating yield when net minting occurred
  const totalSupply = await fromApi.call({ abi: "uint256:totalSupply", target: SAID_VAULT });

  const priceDelta = BigInt(priceEnd) - BigInt(priceStart);

  if (priceDelta > 0n) {
    // Share price growth = net yield (vault receives only the post-fee portion)
    const netYield = (BigInt(totalSupply) * priceDelta) / ONE;

    // Gross yield = net / (1 - protocolFee); revenue = gross - net
    const grossYield = (netYield * BPS) / (BPS - PROTOCOL_FEE_BPS);
    const revenue = grossYield - netYield;

    // DAI (18 decimals) as pricing proxy since AID ≈ $1
    dailyFees.add(DAI, grossYield);
    dailyRevenue.add(DAI, revenue);
  }

  return {
    dailyFees,
    dailyRevenue,
  };
};

const adapter: Adapter = {
  version: 2,
  methodology: {
    Fees: "Total yield generated by the sAID vault portfolio (AI infrastructure financing + T-bills). Measured as the increase in vault totalAssets over the period.",
    Revenue: "Protocol spread — GAIB retains ~20% of gross yield, computed as the difference between gross and net APR paid to sAID holders. Actual rates vary over time and are derived from current vault metrics.",
  },
  adapter: {
    [CHAIN.ETHEREUM]: {
      fetch,
      start: 1733011200, // Dec 1, 2024 — sAID yield accrual start
    },
  },
};

export default adapter;
