import fetchURL from "../../utils/fetchURL";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const statsUrl = (path: string, from: number, to: number) =>
    `https://stats.ferra.ag/api/stats/dlmm/${path}?from_timestamp=${from}&to_timestamp=${to}`;

const fetch = async (options: FetchOptions) => {
    const now = Math.floor(Date.now() / 1000);
    // api often lags the chain and answers a window it has not indexed yet with volume 0
    const volumeAfterWindow = (await fetchURL(statsUrl('volume', options.startTimestamp, now))).data.volume;
    if (!(Number(volumeAfterWindow) > 0))
        throw new Error(`Ferra stats api has not indexed past ${new Date(options.startTimestamp * 1000).toISOString()} yet`);

    const dailyVolume = (await fetchURL(statsUrl('volume', options.startTimestamp, options.endTimestamp))).data.volume;
    const feeStats = (await fetchURL(statsUrl('fees', options.startTimestamp, options.endTimestamp))).data;

    return {
        dailyVolume: dailyVolume,
        dailyFees: feeStats.fee,
        dailyRevenue: feeStats.revenue,
        dailyProtocolRevenue: feeStats.revenue,
        dailySupplySideRevenue: Number(feeStats.fee) - Number(feeStats.revenue),
    };
}

const adapter: SimpleAdapter = {
    version: 1,
    fetch,
    start: '2025-10-07',
    chains: [CHAIN.SUI],
    methodology: {
        Fees: 'LP fees generated by the swap transactions on Ferra DLMM.',
        Revenue: '20% of fees to Ferra.',
        ProtocolRevenue: '20% of fees to Ferra.',
        SupplySideRevenue: '80% of the fees to LPs.',
    }
};

export default adapter;
