import fetchURL from "../../utils/fetchURL";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const fetch = async (_a: any, b: any, options: FetchOptions) => {
    const dailyVolume = (await fetchURL(`https://stats.ferra.ag/api/stats/dlmm/volume?from_timestamp=${options.startTimestamp}&to_timestamp=${options.endTimestamp}`)).data.volume;
    const feeStats = (await fetchURL(`https://stats.ferra.ag/api/stats/dlmm/fees?from_timestamp=${options.startTimestamp}&to_timestamp=${options.endTimestamp}`)).data;

    return {
        dailyVolume: dailyVolume,
        dailyFees: feeStats.fee,
        dailyRevenue: feeStats.revenue,
        dailyProtocolRevenue: feeStats.revenue,
        dailySupplySideRevenue: Number(feeStats.fee) - Number(feeStats.revenue),
    };
}

const adapter: SimpleAdapter = {
    version: 1,
    methodology: {
        Fees: 'LP fees generated by the swap transactions on Ferra DLMM.',
        Revenue: '20% percent of fees to Ferra.',
        ProtocolRevenue: '20% percent of fees to Ferra.',
        SupplySideRevenue: '80% percent of the fees to LPs.',
    },
    fetch,
    start: '2025-10-07',
    chains: [CHAIN.SUI],
};

export default adapter;