import * as sdk from "@defillama/sdk";
import { Adapter, FetchOptions, FetchResultV2 } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

// Kinetiq Earn — an automated kHYPE DeFi strategy vault powered by Veda (curated by Seven Seas).
// https://kinetiq.xyz/docs/earn
// Performance Fee: 20% (profit-only, fully aligned)
// Fees are only charged on profits the vault generates, never on deposited capital.
// If no profit is made, no fee is taken.
// No Management Fee
// No Entry/Exit Fees

const METRICS = {
  VaultYield: "kHYPE Earn Vault Yield",
  PerformanceFees: "kHYPE Earn Performance Fees",
  VaultYieldToDepositors: "kHYPE Earn Yield To Depositors",
};

const methodology = {
  Fees: "Total yield generated by the Kinetiq Earn (vkHYPE) Veda strategy vault.",
  Revenue: "20% performance fee charged on vault profits (profit-only, no management or entry/exit fees).",
  ProtocolRevenue: "20% performance fee charged on vault profits.",
  SupplySideRevenue: "Net yield (80% of profits) that accrues to vkHYPE depositors.",
};

const breakdownMethodology = {
  Fees: {
    [METRICS.VaultYield]: "Gross yield generated by the Kinetiq Earn strategy vault.",
  },
  Revenue: {
    [METRICS.PerformanceFees]: "20% performance fee taken on vault profits.",
  },
  ProtocolRevenue: {
    [METRICS.PerformanceFees]: "20% performance fee taken on vault profits.",
  },
  SupplySideRevenue: {
    [METRICS.VaultYieldToDepositors]: "80% of profits retained by vkHYPE depositors.",
  },
};

const VAULT = "0x9BA2EDc44E0A4632EB4723E81d4142353e1bB160"; // vkHYPE BoringVault
const ACCOUNTANT = "0x74392Fa56405081d5C7D93882856c245387Cece2";

const accountantStateAbi =
  "function accountantState() view returns(address payoutAddress,uint96 highwaterMark,uint128 feesOwedInBase,uint128 totalSharesLastUpdate,uint96 exchangeRate,uint16 allowedExchangeRateChangeUpper,uint16 allowedExchangeRateChangeLower,uint64 lastUpdateTimestamp,bool isPaused,uint24 minimumUpdateDelayInSeconds,uint16 platformFee,uint16 performanceFee)";
const exchangeRateUpdatedAbi =
  "event ExchangeRateUpdated(uint96 oldRate, uint96 newRate, uint64 currentTime)";

interface ExchangeRateUpdatedEvent {
  blockNumber: number;
  oldRate: bigint;
  newRate: bigint;
}

async function fetch(options: FetchOptions): Promise<FetchResultV2> {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();

  const events: ExchangeRateUpdatedEvent[] = (await options.getLogs({
    target: ACCOUNTANT,
    eventAbi: exchangeRateUpdatedAbi,
    entireLog: true,
    parseLog: true,
  })).map((log) => {
    return {
      blockNumber: Number(log.blockNumber),
      oldRate: log.args.oldRate,
      newRate: log.args.newRate,
    };
  });

  for (const event of events) {
    const [totalSupply, previousState] = await Promise.all([
      sdk.api2.abi.call({
        chain: options.chain,
        target: VAULT,
        abi: "uint256:totalSupply",
        block: event.blockNumber,
      }),
      sdk.api2.abi.call({
        chain: options.chain,
        target: ACCOUNTANT,
        abi: accountantStateAbi,
        block: event.blockNumber - 1,
      }),
    ]);

    const highwaterMark = BigInt(previousState.highwaterMark);
    const shareSupply = Math.min(Number(totalSupply), Number(previousState.totalSharesLastUpdate));
    const grossYield = Number(event.newRate - event.oldRate) * shareSupply / 1e36;

    let performanceFees = 0;
    if (event.newRate > highwaterMark) {
      const yieldAboveHighwater = Number(event.newRate - highwaterMark) * shareSupply / 1e36;
      performanceFees = yieldAboveHighwater * Number(previousState.performanceFee) / 1e4;
    }
    const depositorYield = grossYield - performanceFees;

    dailyFees.addCGToken("hyperliquid", grossYield, METRICS.VaultYield);
    dailyRevenue.addCGToken("hyperliquid", performanceFees, METRICS.PerformanceFees);
    dailyProtocolRevenue.addCGToken("hyperliquid", performanceFees, METRICS.PerformanceFees);
    dailySupplySideRevenue.addCGToken("hyperliquid", depositorYield, METRICS.VaultYieldToDepositors);
  }

  return {
    dailyFees,
    dailyRevenue,
    dailySupplySideRevenue,
    dailyProtocolRevenue,
  };
}

const adapter: Adapter = {
  version: 2,
  pullHourly: true,
  adapter: {
    [CHAIN.HYPERLIQUID]: {
      fetch,
      start: "2025-07-15",
    },
  },
  methodology,
  breakdownMethodology,
  allowNegativeValue: true, // Yield can be negative, though performance fees is charged on profits, we still consider them on negative yields as cumulative would be correct
};

export default adapter;
