import { Adapter, FetchOptions } from '../../adapters/types';
import { CHAIN } from '../../helpers/chains';
import fetchURL from '../../utils/fetchURL';

const nemoApiURL = 'https://api.nemoprotocol.com/api/v1/market/fee';

interface NemoStats {
  data: {
    fee: string;
  }
}

const fetch = async ({ startTimestamp, endTimestamp }: FetchOptions) => {
  const url = `${nemoApiURL}?starttime=${startTimestamp}&endtime=${endTimestamp}&tradeType=1`;
  const { data }: NemoStats = await fetchURL(url);
  const dailyFees = data.fee;
  const dailyRevenue = Number(dailyFees) * 0.2;
  const dailySupplySideRevenue = Number(dailyFees) * 0.8;

  return {
    dailyFees,
    dailyUserFees: dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
    dailyHoldersRevenue: 0,
  };
};

const methodology = {
  Fees: 'Swap fees generated by the PT/YT swap transactions on Nemo.',
  UserFees: 'Swap fees generated by the PT/YT swap transactions on Nemo.',
  Revenue: '20% of fees goes to protocol and rest to LPs.',
  ProtocolRevenue: '20% of fees goes to protocol.',
  SupplySideRevenue: '80% of fees goes to LPs as yield.',
  HoldersRevenue: '0% of fees goes to holders.',
};

const adapter: Adapter = {
  version: 2,
  fetch,
  chains: [CHAIN.SUI],
  methodology,
  start: '2025-02-25',
};

export default adapter;
