import { CHAIN } from "../../helpers/chains";
import { SimpleAdapter, FetchOptions } from "../../adapters/types";
import { httpGet } from "../../utils/fetchURL";
import { METRIC } from "../../helpers/metrics";

const ENDPOINT_BASE = "https://api.obol.tech/tvs/mainnet";

const methodology = {
  Fees: "Fees generated by Obol's services",
  Revenue: "Share of the fees generated and collected by Obol",
};

const breakdownMethodology = {
  Fees: { [METRIC.PROTOCOL_FEES]: "Fees generated by Obol's services" },
  Revenue: { [METRIC.PERFORMANCE_FEES]: "Share of the fees collected by Obol" },
};

const fetchCumulativeData = async (dateStr: string) => {
  const url = `${ENDPOINT_BASE}?limit=1&page=0&timestamp=${encodeURIComponent(dateStr)}`;
  const data = await httpGet(url);
  return { totalFees: Number(data.total_fees_eth_denominated ?? 0), totalRevenue: Number(data.total_revenue ?? 0) };
};

const getPreviousDay = (dateStr: string) => {
  const d = new Date(dateStr + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() - 1);
  return d.toISOString().slice(0, 10);
};

const fetch = async (_a: number, _b: any, options: FetchOptions) => {
  const [current, previous] = await Promise.all([
    fetchCumulativeData(options.dateString),
    fetchCumulativeData(getPreviousDay(options.dateString)),
  ]);

  const dailyFeesETH = current.totalFees - previous.totalFees;
  const dailyRevenueETH = current.totalRevenue - previous.totalRevenue;

  console.log(dailyFeesETH, dailyRevenueETH)

  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();

  if (dailyFeesETH > 0) dailyFees.addGasToken(dailyFeesETH * 1e18, METRIC.PROTOCOL_FEES);
  if (dailyRevenueETH > 0) dailyRevenue.addGasToken(dailyRevenueETH * 1e18, METRIC.PERFORMANCE_FEES);

  return { dailyFees, dailyRevenue };
};

const adapter: SimpleAdapter = {
  version: 1,
  fetch,
  chains: [CHAIN.ETHEREUM],
  start: '2026-02-17',
  methodology,
  breakdownMethodology,
};

export default adapter;
