import { CHAIN } from "../../helpers/chains";
import { SimpleAdapter, FetchOptions } from "../../adapters/types";
import { httpGet } from "../../utils/fetchURL";
import { METRIC } from "../../helpers/metrics";

const ENDPOINT_BASE = "https://api.obol.tech/tvs/mainnet";

const methodology = {
  Fees: "Fees generated by Obol's services",
  Revenue: "Share of the fees generated and collected by Obol",
  SupplySideRevenue: "Share of the fees generated to Node Operators",
};

const breakdownMethodology = {
  Fees: { [METRIC.PROTOCOL_FEES]: "Fees generated by Obol's services" },
  Revenue: { [METRIC.PERFORMANCE_FEES]: "Share of the fees collected by Obol" },
  SupplySideRevenue: { 'Fees to Node Operators': "Share of the fees generated to node operators" },
};

const correctedTotalRevenues: Record<string, number> = {
  '2026-06-04': 114.49, //api wrongly returns 0 vs 114.49 (previous day) and 113 (next day)
}

const fetchCumulativeData = async (dateStr: string) => {
  const url = `${ENDPOINT_BASE}?limit=1&page=0&timestamp=${encodeURIComponent(dateStr)}`;
  const data = await httpGet(url);
  return { totalFees: Number(data.total_fees_eth_denominated ?? 0), totalRevenue: correctedTotalRevenues[dateStr] ?? Number(data.total_revenue ?? 0) };
};

const getPreviousDay = (dateStr: string) => {
  const d = new Date(dateStr + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() - 1);
  return d.toISOString().slice(0, 10);
};

const fetch = async (options: FetchOptions) => {
  const [current, previous] = await Promise.all([
    fetchCumulativeData(options.dateString),
    fetchCumulativeData(getPreviousDay(options.dateString)),
  ]);

  const dailyFeesETH = current.totalFees - previous.totalFees;
  const dailyRevenueETH = current.totalRevenue - previous.totalRevenue;

  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  dailyFees.addGasToken(dailyFeesETH * 1e18, METRIC.PROTOCOL_FEES);
  dailyRevenue.addGasToken(dailyRevenueETH * 1e18, METRIC.PERFORMANCE_FEES);
  dailySupplySideRevenue.addGasToken((dailyFeesETH - dailyRevenueETH) * 1e18, 'Fees to Node Operators');

  return { dailyFees, dailyRevenue, dailySupplySideRevenue };
};

const adapter: SimpleAdapter = {
  version: 1,
  fetch,
  chains: [CHAIN.ETHEREUM],
  start: '2026-02-17',
  methodology,
  breakdownMethodology,
  allowNegativeValue: true,
};

export default adapter;
