import { SimpleAdapter, FetchResultV2, FetchV2 } from '../../adapters/types';
import { CHAIN } from '../../helpers/chains';
import fetchURL from '../../utils/fetchURL';

const fullSailApiURL = 'https://app.fullsail.finance/api/defi_llama/fees';

interface FullSailStats {
    fees_usd: string;
    protocol_revenue_usd: string;
    holders_revenue_usd: string;
    revenue_usd: string;
}

const methodology = {
    Fees: 'All swap fees generated by swap transactions on FullSail Finance protocol, representing the total value flow into the protocol ecosystem from users.',
    HoldersRevenue: 'Portion of Fees distributed to veSail token holders, including all swap fees allocated to holders and rebase oSail.',
    ProtocolRevenue: 'Portion of Fees retained by the protocol entity, including protocol fees from swap transactions and protocol fees from rebase oSail.',
    Revenue: 'Total daily revenue of the protocol, calculated as the sum of HoldersRevenue and ProtocolRevenue.'
};

const fetchFullSailStats: FetchV2 = async ({
    startTimestamp,
    endTimestamp,
}): Promise<FetchResultV2> => {
    const url = `${fullSailApiURL}?start_timestamp=${startTimestamp*1000}&end_timestamp=${endTimestamp*1000}`;
    const data: FullSailStats = await fetchURL(url);
    const dailyFees = data.fees_usd;
    const dailyRevenue = data.revenue_usd;
    const dailyHoldersRevenue = data.holders_revenue_usd;
    const dailyProtocolRevenue = data.protocol_revenue_usd;
    return {
        dailyFees,
        dailyRevenue,
        dailyProtocolRevenue: dailyProtocolRevenue,
        dailyHoldersRevenue: dailyHoldersRevenue,
    };
};

const adapter: SimpleAdapter = {
    version: 2,
    adapter: {
        [CHAIN.SUI]: {
            fetch: fetchFullSailStats,
            start: '2025-05-30',
            meta: {
                methodology,
            },
        },
    },
};

export default adapter;
