import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import coreAssets from "../../helpers/coreAssets.json";

const usdc = coreAssets.avax.USDC
const savUsd = '0x06d47F3fb376649c3A9Dafe069B3D6E35572219E'
const avUsd = '0x24dE8771bC5DdB3362Db529Fc3358F2df3A0E346'
const MINT_AND_REDEEM_CONTRACT = '0xcb43139E90f019624e3B76C56FB05394B162A49c'

const REDEEM_ABI = 'event Redeem(address indexed redeemer,address indexed benefactor,address indexed beneficiary,address collateral_asset,uint256 collateral_amount,uint256 avantcoin_amount)'

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const logs = await options.getLogs({
    eventAbi: REDEEM_ABI,
    target: MINT_AND_REDEEM_CONTRACT,
  })
  logs.forEach((log) => {
    const fee = Number(log.avantcoin_amount) / 1e12 - Number(log.collateral_amount);
    if (fee > 0) {
      dailyFees.add(usdc, fee, METRIC.MINT_REDEEM_FEES);
      dailyRevenue.add(usdc, fee, METRIC.MINT_REDEEM_FEES);
    }
  });

  const daily_rewards = await options.getLogs({
    eventAbi: 'event RewardsReceived (uint256 amount)',
    topic: '0xbb28dd7cd6be6f61828ea9158a04c5182c716a946a6d2f31f4864edb87471aa6',
    target: savUsd,
  })
  daily_rewards.forEach((log) => {
    dailyFees.add(avUsd, log.amount, METRIC.ASSETS_YIELDS);
    dailySupplySideRevenue.add(avUsd, log.amount, METRIC.ASSETS_YIELDS);
    dailyRevenue.add(avUsd, Number(log.amount) / 9, METRIC.PERFORMANCE_FEES)
  });

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue
  }
}

const adapters: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.AVAX],
  start: '2024-11-15',
  methodology: {
    Fees: "Redeem fees + yield distribution",
    Revenue: "10% of the net profits generated by the protocol strategies and mint/redeem fees",
    ProtocolRevenue: "10% of the net profits generated by the protocol strategies and mint/redeem fees",
    UserFees: "Redeem fees from users",
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: 'The net profits generated by the protocol strategies.',
      [METRIC.MINT_REDEEM_FEES]: 'Users pay a 0.05% fee when redeeming avUSD.',
      [METRIC.PERFORMANCE_FEES]: '10% of the net profits as performance fees.',
    }
  },
};

export default adapters;
