import { FetchOptions, FetchResultV2, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getERC4626VaultsYield } from "../../helpers/erc4626";

const WITRY_VAULT = "0xE346C29b5B60Ef870b9724c57ccfbBc631e47DEE";
const iTRY = "0xb492B4aFD9658093694CF9452D5C272e8230F3B0";

const LABELS = {
  VAULT_YIELD: "Vault Yield",
  FAST_REDEEM_FEES: "Fast Redeem Fees",
  FAST_REDEEM_FEES_TO_PROTOCOL: "Fast Redeem Fees to protocol",
} as const;

const abis = {
  fastRedeemed: "event FastRedeemed(address indexed owner, address indexed receiver, uint256 shares, uint256 assets, uint256 feeAssets)",
  fastRedeemedThroughComposer: "event FastRedeemedThroughComposer(address indexed composer, address indexed crosschainReceiver, address indexed owner, uint256 shares, uint256 assets, uint256 feeAssets)",
};

const fetch = async (options: FetchOptions): Promise<FetchResultV2> => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailyUserFees = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const [vaultYield, fastRedeemedLogs, composerFastRedeemedLogs] = await Promise.all([
    getERC4626VaultsYield({
      options,
      vaults: [WITRY_VAULT],
    }),
    options.getLogs({ target: WITRY_VAULT, eventAbi: abis.fastRedeemed }),
    options.getLogs({ target: WITRY_VAULT, eventAbi: abis.fastRedeemedThroughComposer }),
  ]);

  const fastRedeemFeeAssets = [...fastRedeemedLogs, ...composerFastRedeemedLogs]
    .reduce((sum, log: any) => sum + BigInt(log.feeAssets), 0n);

  dailyFees.addBalances(vaultYield, LABELS.VAULT_YIELD);
  dailyFees.add(iTRY, fastRedeemFeeAssets, LABELS.FAST_REDEEM_FEES);

  dailyRevenue.add(iTRY, fastRedeemFeeAssets, LABELS.FAST_REDEEM_FEES_TO_PROTOCOL);
  dailyProtocolRevenue.add(iTRY, fastRedeemFeeAssets, LABELS.FAST_REDEEM_FEES_TO_PROTOCOL);
  dailyUserFees.add(iTRY, fastRedeemFeeAssets, LABELS.FAST_REDEEM_FEES);
  dailySupplySideRevenue.addBalances(vaultYield, LABELS.VAULT_YIELD);

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue,
    dailySupplySideRevenue,
    dailyUserFees,
  };
};

const methodology = {
  Fees: "Includes vault yield generated for wiTRY depositors and fast redeem fees paid by users.",
  Revenue: "Revenue is fast redeem fees retained by Brix.",
  ProtocolRevenue: "Protocol revenue is fast redeem fees retained by Brix.",
  SupplySideRevenue: "Vault yield distributed to wiTRY depositors.",
  UserFees: "Fast redeem fees paid by users.",
};

const breakdownMethodology = {
  Fees: {
    [LABELS.VAULT_YIELD]: "Yield generated by the wiTRY vault.",
    [LABELS.FAST_REDEEM_FEES]: "Fast redeem fees paid by users.",
  },
  UserFees: {
    [LABELS.FAST_REDEEM_FEES]: "Fast redeem fees paid by users.",
  },
  Revenue: {
    [LABELS.FAST_REDEEM_FEES_TO_PROTOCOL]: "Fast redeem fees retained by Brix.",
  },
  ProtocolRevenue: {
    [LABELS.FAST_REDEEM_FEES_TO_PROTOCOL]: "Fast redeem fees retained by Brix.",
  },
  SupplySideRevenue: {
    [LABELS.VAULT_YIELD]: "Vault yield distributed to wiTRY depositors.",
  },
};

//pullHourly not needed as the share prices only update once a day excluding weekends.
const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.ETHEREUM],
  start: "2026-03-12",
  allowNegativeValue: true, // vault yield can be negative if share price decreases
  methodology,
  breakdownMethodology,
};

export default adapter;
