import  { postURL } from "../../utils/fetchURL"
import { SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import customBackfill from "../../helpers/customBackfill";

const gooseFxEndpoint = "https://api-services.goosefx.io/getDefillamaStats";

const fetch = async (timestamp: number) => {
  const timeStampInMs = timestamp * 1000;
  const res = await postURL(gooseFxEndpoint, {
    timestamp: timeStampInMs 
  });
  return {
    timestamp: timeStampInMs,
    dailyVolume: res?.volume24H,
    totalVolume: res?.totalVolume,
  };
};

const adapter: SimpleAdapter = {
    adapter: {
      [CHAIN.SOLANA]: {
        fetch: fetch,
        start: 1696982400,
        customBackfill: customBackfill(CHAIN.SOLANA as CHAIN, () => fetch),
        runAtCurrTime: false,
        meta: {
          methodology: 'This is the volume generated by our SSL Protocol and calculated by our internal api.'
        }
      },
    },
  };

  export default adapter;