import { postURL } from "../../utils/fetchURL"
import { SimpleAdapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const gooseFxEndpoint = "https://api-services.goosefx.io/getDefillamaStats";

const fetch = async (options: FetchOptions) => {
  const timeStampInMs = options.toTimestamp * 1000;
  const res = await postURL(gooseFxEndpoint, {
    timestamp: timeStampInMs
  });
  return {
    dailyVolume: res?.volume24H,
  };
};

const adapter: SimpleAdapter = {
  fetch,
  chains: [CHAIN.SOLANA],
  start: '2023-10-11',
  methodology: 'This is the volume generated by our SSL Protocol and calculated by our internal api.',
  deadFrom: '2025-09-23',
};

export default adapter;