import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getERC4626VaultsYield } from "../../helpers/erc4626";
import { METRIC } from "../../helpers/metrics";

/**
 * Lista DAO RWA fees:
 * - 5% performance fee on yield earned by ERC4626 vaults
 * - 0.1% redemption fee from WithdrawFromVault events
 * @doc https://listaorg.notion.site/Profit-cfd754931df449eaa9a207e38d3e0a54
 * @test npx ts-node --transpile-only cli/testAdapter.ts fees lista-rwa
 */

const WITHDRAW_FROM_VAULT_ABI =
  "event WithdrawFromVault(uint256 shares, uint256 totalAmount, uint256 feeAmount)";

// ERC4626 vaults where users deposit
const EARN_POOLS = [
  "0x60512AeB641E960faAac7E2bFcB1819f993E7282", // USDT.Treasury
  "0x82664f43676FfD81BE2b472c5A2E2808952ecd56", // USDT.AAA
];

// Adapters that emit WithdrawFromVault events with redemption fees
const ADAPTERS = [
  "0xC1AeEBBfD8b1280e78D930C43700758F543F5Fc6", // USDT.Treasury
  "0x69D15B7a232244EB0FDDED2a3E038589E5C50105", // USDT.AAA
];

const PERFORMANCE_FEE_RATE = 0.05; // 5% performance fee

const fetch = async (options: FetchOptions) => {
  // Calculate total yield from ERC4626 vaults
  const totalYield = await getERC4626VaultsYield({
    options,
    vaults: EARN_POOLS,
  });

  // Split yield: 95% to suppliers, 5% to protocol (performance fee)
  const dailySupplySideRevenue = totalYield.clone(1 - PERFORMANCE_FEE_RATE, METRIC.ASSETS_YIELDS);
  const dailyRevenue = options.createBalances();
  dailyRevenue.addBalances(totalYield.clone(PERFORMANCE_FEE_RATE), METRIC.PERFORMANCE_FEES);

  // Get underlying asset (USDT) from vaults
  const assets = await options.api.multiCall({
    abi: "address:asset",
    calls: EARN_POOLS,
  });
  const asset = assets[0]; // Both pools use USDT

  // Add redemption fees (0.1% fee from WithdrawFromVault events)
  const vaultLogs = await options.getLogs({
    targets: ADAPTERS,
    eventAbi: WITHDRAW_FROM_VAULT_ABI,
  });
  vaultLogs.forEach((log) => {
    if (log.feeAmount > 0n) {
      dailyRevenue.add(asset, log.feeAmount, METRIC.DEPOSIT_WITHDRAW_FEES);
    }
  });

  const dailyFees = options.createBalances();
  dailyFees.addBalances(dailySupplySideRevenue);
  dailyFees.addBalances(dailyRevenue);

  return {
    dailyFees,
    dailyRevenue,
    dailySupplySideRevenue,
  };
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.BSC]: {
      fetch,
      start: "2025-11-25",
    },
  },
    methodology: {
      Fees: "Includes the yield generated and a 0.1% redemption fee",
      Revenue: "Includes a 5% performance fee on the yield generated and a 0.1% redemption fee",
      SupplySideRevenue: "95% of the yield goes to vault depositors"
    },
    breakdownMethodology: {
      Fees: {
        [METRIC.ASSETS_YIELDS]: "95% of the yield generated by the vault paid to depositors",
        [METRIC.PERFORMANCE_FEES]: "The protocol takes a 5% fee on the yield generated by the vault",
        [METRIC.DEPOSIT_WITHDRAW_FEES]: "The protocol charges a 0.1% fee on redemption"
      },
      Revenue: {
        [METRIC.PERFORMANCE_FEES]: "The protocol takes a 5% fee on the yield generated by the vault",
        [METRIC.DEPOSIT_WITHDRAW_FEES]: "The protocol charges a 0.1% fee on redemption"
      },
      SupplySideRevenue: {
        [METRIC.ASSETS_YIELDS]: "95% of the yield generated by the vault paid to depositors",
      }
    }
};

export default adapter;
