import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

const DIGGERS = "0x4190a197e9c7c8D9ce1095c32e6666A13A996580";
const DEPLOY_BLOCK = 12296204;

const WAD = 10n ** 18n;
// V4 lpFee denominator (fee is expressed in millionths of the input amount).
const MILLION = 1_000_000n;
// While the launch airdrop window is open, 1e17 (10%) of ETH fees is carved out
// of the team side to fund the $DIG platform token distribution (see docs).
const PLATFORM_SLICE_WAD = 10n ** 17n;

// Every launch emits Created with the creator-chosen pool fee (V4 millionths).
const CREATED =
  "event Created(address indexed token, address indexed creator, string name, string symbol, string metadataURI, bytes32 poolId, uint160 startSqrtPriceX96, uint24 poolFee, uint128 burnShareWad)";
// Emitted on every swap settled against a Diggers pool; ethAmount is the ETH leg.
const SWAPPED =
  "event Swapped(address indexed token, address indexed trader, bool indexed isBuy, uint256 ethAmount, uint256 tokenAmount, uint160 sqrtPriceAfterX96, int24 tickAfter, uint128 liquidityAfter, uint256 ethInPool, uint256 tokenInPool)";

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const teamShareWad = await options.api.call({ target: DIGGERS, abi: "uint256:teamShareWad" })
  const airdropActive = await options.api.call({ target: DIGGERS, abi: "bool:airdropActive" })
  const createdLogs = await options.getLogs({ target: DIGGERS, eventAbi: CREATED, fromBlock: DEPLOY_BLOCK, cacheInCloud: true })
  const swapLogs = await options.getLogs({ target: DIGGERS, eventAbi: SWAPPED })

  // poolFee is chosen per token at launch (1%-5%, V4 millionths).
  const poolFee: Record<string, bigint> = {};
  createdLogs.forEach((log: any) => {
    poolFee[log.token.toLowerCase()] = BigInt(log.poolFee);
  });

  const teamWad = BigInt(teamShareWad);
  const platformWad = airdropActive ? PLATFORM_SLICE_WAD : 0n;

  swapLogs.forEach((log: any) => {
    const fee = poolFee[log.token.toLowerCase()];
    if (fee === undefined) return;
    const ethLeg = BigInt(log.ethAmount);
    // The V4 lpFee is charged on the input amount: ETH on buys, tokens on
    // sells. The token-side fee is valued via the trade's own ETH leg (the
    // launched tokens have no external price), mirroring the ETH-side formula.
    const swapFee = log.isBuy
      ? (ethLeg * fee) / MILLION
      : (ethLeg * fee) / (MILLION - fee);

    const teamShare = (swapFee * teamWad) / WAD;
    const platformShare = (swapFee * platformWad) / WAD;
    const creatorShare = swapFee - teamShare - platformShare;

    dailyFees.addGasToken(swapFee, METRIC.SWAP_FEES);
    dailyRevenue.addGasToken(teamShare + platformShare, "Swap Fees to Protocol");
    dailySupplySideRevenue.addGasToken(creatorShare, "Swap Fees to Creators");
  });

  return {
    dailyFees,
    dailyUserFees: dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  UserFees:
    "Swappers pay the creator-chosen Uniswap V4 pool fee (1%-5% per token) on every trade in a Diggers pool.",
  Fees:
    "LP fees generated by Diggers pools. Diggers is the only LP of every pool it creates, so all LP fees accrue to the protocol's harvest split. Fees are valued on the ETH leg of each swap.",
  Revenue:
    "The team share of ETH fees (on-chain teamShareWad, currently 30%) plus the 10% platform-token slice while the $DIG airdrop window is live.",
  ProtocolRevenue:
    "The team share of ETH fees plus the platform-token slice while the airdrop window is live.",
  SupplySideRevenue:
    "The creator share of ETH fees (remainder after team/platform), paid to each token's creator fee-split table via pull-payment claims. The token-side fee split (burn + daily traders-airdrop pot) is denominated in the launched tokens and not valued here.",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.SWAP_FEES]:
      "Creator-chosen 1%-5% Uniswap V4 pool fee on swaps in Diggers-created pools, valued on the ETH leg of each trade.",
  },
  Revenue: {
    "Swap Fees to Protocol":
      "Team share of ETH fees (on-chain teamShareWad) plus the 10% platform slice while the $DIG airdrop window is live.",
  },
  SupplySideRevenue: {
    "Swap Fees to Creators":
      "Creator share of ETH fees, distributed to the token's immutable fee-split table via pull-payment claims.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  chains: [CHAIN.ROBINHOOD],
  start: "2026-07-17",
  fetch,
  methodology,
  breakdownMethodology,
  doublecounted: true, // uniswap
};

export default adapter;
