import fetchURL from "../../utils/fetchURL";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getUniqStartOfTodayTimestamp } from "../../helpers/getUniSubgraphVolume";

const methodology = {
    Fees: 'LP fees generated by the swap transactions on Ferra CLMM.',
    ProtocolRevenue: '20% percent of the LP fees.',
};

const fetchData = () => {
    return async ({ startTimestamp, endTimestamp }: FetchOptions) => {
        const res = (await fetchURL(`https://stats.ferra.ag/api/stats/clmm/fees?from_timestamp=${startTimestamp}&to_timestamp=${endTimestamp}`)).data;
        const dayTimestamp = getUniqStartOfTodayTimestamp(new Date(endTimestamp * 1000))
        return {
            dailyFees: res.fee ,
            dailyRevenue: res.revenue,
            dailyProtocolRevenue: res.revenu,
            timestamp: dayTimestamp,
        };
    };
}

const adapter: SimpleAdapter = {
    version: 2,
    adapter: {
        [CHAIN.SUI]: {
            fetch: fetchData(),
            start: '2025-10-07',
        }
    },
    methodology,
};

export default adapter;