import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { fetchStats } from "./pharaoh-v3";

const fetch = async (options: FetchOptions) => {
  const stats = await fetchStats(options);

  const dailyVolume = stats.legacyVolumeUSD;
  const dailyFees = options.createBalances();
  const dailyUserFees = options.createBalances();
  const dailyHoldersRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyRevenue = options.createBalances();

  dailyFees.addUSDValue(stats.legacyFeesUSD, "Swap fees");
  dailyUserFees.addUSDValue(stats.legacyFeesUSD, "Swap fees");
  dailyHoldersRevenue.addUSDValue(stats.legacyUserFeesRevenueUSD, "Swap fees to xPHAR voters");
  dailyHoldersRevenue.addUSDValue(stats.legacyBribeRevenueUSD, "Vote incentives to xPHAR voters");
  dailyProtocolRevenue.addUSDValue(stats.legacyProtocolRevenueUSD, "Swap fees to treasury");
  dailySupplySideRevenue.addUSDValue(
    stats.legacyFeesUSD - stats.legacyUserFeesRevenueUSD - stats.legacyProtocolRevenueUSD,
    "Swap fees to LPs",
  );
  dailyRevenue.add(dailyProtocolRevenue);
  dailyRevenue.addUSDValue(stats.legacyUserFeesRevenueUSD, "Swap fees to xPHAR voters");

  return {
    dailyVolume,
    dailyFees,
    dailyUserFees,
    dailyHoldersRevenue,
    dailyProtocolRevenue,
    dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Swap fees generated by Pharaoh legacy pools.",
  Revenue: "Swap fee revenue directed to the protocol treasury and xPHAR voters.",
  UserFees: "Swap fees paid by traders.",
  ProtocolRevenue: "Treasury share of swap fees.",
  HoldersRevenue: "Swap fees and vote incentives distributed to xPHAR voters.",
  SupplySideRevenue: "Swap fees retained by liquidity providers.",
};

const breakdownMethodology = {
  Fees: {
    "Swap fees": "Swap fees paid by traders.",
  },
  Revenue: {
    "Swap fees to treasury": "Treasury share of swap fees.",
    "Swap fees to xPHAR voters": "Swap fees distributed to xPHAR voters.",
  },
  UserFees: {
    "Swap fees": "Swap fees paid by traders.",
  },
  ProtocolRevenue: {
    "Swap fees to treasury": "Treasury share of swap fees.",
  },
  HoldersRevenue: {
    "Swap fees to xPHAR voters": "Swap fees distributed to xPHAR voters.",
    "Vote incentives to xPHAR voters": "Vote incentives distributed to xPHAR voters.",
  },
  SupplySideRevenue: {
    "Swap fees to LPs": "Swap fees retained by liquidity providers.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.AVAX],
  start: '2025-10-08',
  methodology,
  breakdownMethodology,
  pullHourly: true,
};

export default adapter;
