import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { fetchStats } from "./pharaoh-v3";
import { PHARAOH_METRIC } from "./pharaoh-v2";

const fetch = async (options: FetchOptions) => {
  const stats = await fetchStats(options);

  const dailyVolume = stats.legacyVolumeUSD;
  const dailyFees = options.createBalances();
  const dailyUserFees = options.createBalances();
  const dailyHoldersRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyRevenue = options.createBalances();

  dailyFees.addUSDValue(stats.legacyFeesUSD, PHARAOH_METRIC.SwapFees);
  dailyFees.addUSDValue(stats.legacyBribeRevenueUSD, PHARAOH_METRIC.VoteIncentives);
  
  dailyUserFees.addUSDValue(stats.legacyFeesUSD, PHARAOH_METRIC.SwapFees);

  dailyRevenue.addUSDValue(stats.legacyUserFeesRevenueUSD, PHARAOH_METRIC.SwapFeesToVoters);
  dailyRevenue.addUSDValue(stats.legacyBribeRevenueUSD, PHARAOH_METRIC.VoteIncentives);
  dailyHoldersRevenue.addUSDValue(stats.legacyUserFeesRevenueUSD, PHARAOH_METRIC.SwapFeesToVoters);
  dailyHoldersRevenue.addUSDValue(stats.legacyBribeRevenueUSD, PHARAOH_METRIC.VoteIncentives);

  dailyRevenue.addUSDValue(stats.legacyProtocolRevenueUSD, PHARAOH_METRIC.SwapFeesToTreasury);
  dailyProtocolRevenue.addUSDValue(stats.legacyProtocolRevenueUSD, PHARAOH_METRIC.SwapFeesToTreasury);

  dailySupplySideRevenue.addUSDValue(
    stats.legacyFeesUSD - stats.legacyUserFeesRevenueUSD - stats.legacyProtocolRevenueUSD,
    PHARAOH_METRIC.SwapFeesToLPs,
  );

  return {
    dailyVolume,
    dailyFees,
    dailyUserFees,
    dailyHoldersRevenue,
    dailyProtocolRevenue,
    dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Swap fees generated by Pharaoh legacy pools.",
  Revenue: "Swap fee revenue directed to the protocol treasury and xPHAR voters.",
  UserFees: "Swap fees paid by traders.",
  ProtocolRevenue: "Treasury share of swap fees.",
  HoldersRevenue: "Swap fees and vote incentives distributed to xPHAR voters.",
  SupplySideRevenue: "Swap fees retained by liquidity providers.",
};

const breakdownMethodology = {
  Fees: {
    [PHARAOH_METRIC.SwapFees]: "Swap fees paid by traders.",
    [PHARAOH_METRIC.VoteIncentives]: "Vote incentives distributed to xPHAR voters.",
  },
  Revenue: {
    [PHARAOH_METRIC.SwapFeesToTreasury]: "Swap fees shared to treasury.",
    [PHARAOH_METRIC.SwapFeesToVoters]: "Swap fees shared to xPHAR voters.",
    [PHARAOH_METRIC.VoteIncentives]: "Vote incentives distributed to xPHAR voters.",
  },
  UserFees: {
    [PHARAOH_METRIC.SwapFees]: "Swap fees paid by traders.",
  },
  ProtocolRevenue: {
    [PHARAOH_METRIC.SwapFeesToTreasury]: "Swap fees shared to treasury.",
  },
  HoldersRevenue: {
    [PHARAOH_METRIC.SwapFeesToVoters]: "Swap fees shared to xPHAR voters.",
    [PHARAOH_METRIC.VoteIncentives]: "Vote incentives distributed to xPHAR voters.",
  },
  SupplySideRevenue: {
    [PHARAOH_METRIC.SwapFeesToLPs]: "Swap fees distributed to liquidity providers.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.AVAX],
  start: '2025-10-08',
  methodology,
  breakdownMethodology,
  pullHourly: true,
};

export default adapter;
