import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { getUniV2LogAdapter } from "../helpers/uniswap";

export const PHARAOH_METRIC = {
  SwapFees: 'Token Swap Fees',
  VoteIncentives: 'Vote Incentives To xPHAR Voters',
  SwapFeesToTreasury: 'Token Swap Fees To Treasury',
  SwapFeesToVoters: 'Token Swap Fees To xPHAR Voters',
  SwapFeesToLPs: 'Token Swap Fees To LPs',
}

const fetch = async (options: FetchOptions) => {
  const dailyVolume = options.createBalances();
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  
  const results: any = await getUniV2LogAdapter({ factory: '0xAAA16c016BF556fcD620328f0759252E29b1AB57' })(options);
  dailyVolume.add(results.dailyVolume);
  dailyFees.add(results.dailyFees, PHARAOH_METRIC.SwapFees);
  dailyRevenue.add(results.dailyFees, PHARAOH_METRIC.SwapFeesToVoters);

  return {
    dailyVolume,
    dailyFees,
    dailyUserFees: dailyFees,
    dailyHoldersRevenue: dailyRevenue,
    dailyRevenue,
    dailyProtocolRevenue: 0,
    dailySupplySideRevenue: 0,
  };
};

const methodology = {
  Fees: "Swap fees generated by Pharaoh V2 pools.",
  Revenue: "All fees are revenue and distributed to xPHAR voters.",
  UserFees: "Swap fees paid by traders.",
  ProtocolRevenue: "No revenue shared to treasury.",
  HoldersRevenue: "All fees are revenue and distributed to xPHAR voters.",
  SupplySideRevenue: "No revenue shared to LPs.",
};

const breakdownMethodology = {
  Fees: {
    [PHARAOH_METRIC.SwapFees]: "Swap fees paid by traders.",
  },
  Revenue: {
    [PHARAOH_METRIC.SwapFeesToVoters]: "Swap fees shared to xPHAR voters.",
  },
  UserFees: {
    [PHARAOH_METRIC.SwapFees]: "Swap fees paid by traders.",
  },
  HoldersRevenue: {
    [PHARAOH_METRIC.SwapFeesToVoters]: "Swap fees shared to xPHAR voters.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  fetch,
  chains: [CHAIN.AVAX],
  start: '2024-03-13',
  methodology,
  breakdownMethodology,
};

export default adapter;
