import { CHAIN } from "../helpers/chains";
import { fetchBuilderData } from "../helpers/extended-exchange";
import { FetchOptions, SimpleAdapter } from "../adapters/types";

const EXTENDED_BUILDER_NAMES = ["Planemo Trading"];
const EXTENDED_BUILDER_ID = "114410";

const fetchExtended = async (_a: any, _b: any, options: FetchOptions) => {
  const { dailyVolume, dailyFees } = await fetchBuilderData({
    options,
    builderNames: EXTENDED_BUILDER_NAMES,
  });
  const labeledFees = options.createBalances();
  const labeledRevenue = options.createBalances();

  labeledFees.addBalances(dailyFees, "Extended Builder Fees");
  labeledRevenue.addBalances(dailyFees, "Extended Builder Fees");

  return {
    dailyVolume,
    dailyFees: labeledFees,
    dailyRevenue: labeledRevenue,
    dailyProtocolRevenue: labeledRevenue,
  };
};

const methodology = {
  Fees: `Trading fees generated by Planemo Trading flow on Extended (builderName: Planemo Trading, builderId: ${EXTENDED_BUILDER_ID}).`,
  Revenue: "Builder revenue collected by Planemo Trading from Extended.",
  ProtocolRevenue: "All reported builder revenue is attributed to Planemo Trading protocol revenue.",
};

const adapter: SimpleAdapter = {
  adapter: {
    [CHAIN.STARKNET]: {
      fetch: fetchExtended,
      start: "2026-04-12",
    },
  },
  methodology,
  breakdownMethodology: {
    Fees: {
      "Extended Builder Fees":
        "Fees generated by users trading via Planemo Trading's Extended builder flow.",
    },
    Revenue: {
      "Extended Builder Fees":
        "Builder fees collected by Planemo Trading from Extended trading flow.",
    },
    ProtocolRevenue: {
      "Extended Builder Fees":
        "Builder fees retained by Planemo Trading as protocol revenue.",
    },
  },
  doublecounted: true,
};

export default adapter;
