import { SimpleAdapter } from '../../adapters/types';
import { CHAIN } from '../../helpers/chains';
import fetchURL from '../../utils/fetchURL';

const cetusApiURL = 'https://api-sui.cetus.zone/v3/sui/dlmm/histogram?dateType=hour';

const fetch = async ({ startTimestamp, endTimestamp }) => {
  const feeUrl = `${cetusApiURL}&dataType=fee&beginTimestamp=${startTimestamp}&endTimestamp=${endTimestamp}`;
  const protocolFeeUrl = `${cetusApiURL}&dataType=protocolFee&beginTimestamp=${startTimestamp}&endTimestamp=${endTimestamp}`;
  const feeList = (await fetchURL(feeUrl)).data.list;
  const protocolFeeList = (await fetchURL(protocolFeeUrl)).data.list;

  let dailyFees = feeList.reduce((p, c) => p + Number(c.value), 0);
  let dailyRevenue = protocolFeeList.reduce((p, c) => p + Number(c.value), 0);
  let dailySupplySideRevenue = dailyFees - dailyRevenue;

  return {
    dailyFees,
    dailyUserFees: dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: 'Swap fees generated by the swap transactions on Cetus Protocol.',
  Revenue: '20% of the swap fees are charged by the protocol.',
  ProtocolRevenue: 'Protocol fees charged from the swap fees.',
  SupplySideRevenue: '80% of the swap fees are distributed to the supply side.',
};

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.SUI],
  start: '2025-09-30',
  methodology,
};

export default adapter;
