import type { SimpleAdapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { addTokensReceived } from "../../helpers/token";

// Developer 1 / Fee Receiver for DEX Aggregator Swaps
const DEX_FEE_RECEIVER = '0xafF5340ECFaf7ce049261cff193f5FED6BDF04E7';

// Accumulator address that collects 100% of the 4% ARB INC token transfer tax
const TAX_ACCUMULATOR = '0x4c1caA917FD012b285Ba35E93535675e5B59806C';

// Arbitrage Inception (ARB INC) token contract on BSC
const ARB_TOKEN = '0x5EE54869Ecd5E752C31aF095187326D4A4D50e1c';

// Timestamp when DEX swap dev fee changed from 0.1% (10 bps) to 0.5% (50 bps)
// June 8, 2026 00:00:00 UTC (commit 9a41ee3)
const FEE_RATE_CHANGE_TIMESTAMP = 1780876800;

const fetch = async (options: FetchOptions) => {
    // Dynamic fee rate based on date: 0.1% prior to June 8, 2026, 0.5% thereafter
    const timestamp = options.startTimestamp ?? options.startOfDay;
    const feeRate = timestamp < FEE_RATE_CHANGE_TIMESTAMP ? 0.001 : 0.005;

    // 1. DEX Aggregator Swap Dev Fees
    // Filter out internal transfers originating from the tax accumulator to avoid double-counting
    const swapFees = await addTokensReceived({
        options,
        targets: [DEX_FEE_RECEIVER],
        logFilter: (log: any) => {
            const from = String(log.from ?? log.fromAddress ?? log.from_address ?? '').toLowerCase();
            return from !== TAX_ACCUMULATOR.toLowerCase();
        },
    });

    // DEX trading volume is calculated from collected swap fees divided by the fee rate
    const dailyVolume = swapFees.clone(1 / feeRate);

    // 2. Token Transfer Tax (4% on ARB INC transfers received by accumulator)
    const tokenTax = await addTokensReceived({
        options,
        target: TAX_ACCUMULATOR,
        tokens: [ARB_TOKEN],
    });

    // 3. Token Tax RevShare Distribution:
    // 40% is allocated to Developer 2 / Treasury (0x66BB...): distributed to ARB INC holders via the DEX Leaderboard engine.
    // The distribution daemon (scripts/watcher.js) applies SAFE_FACTOR = 0.73 (73% net yield distributed = 29.2% of total tax,
    // with the remaining 27% / 10.8% of tax serving as an on-chain gas fee reserve buffer).
    const SAFE_FACTOR = 0.73;
    const dailyHoldersRevenue = options.createBalances();
    dailyHoldersRevenue.addBalances(tokenTax.clone(0.40 * SAFE_FACTOR), 'Token Tax To Holders Yield');

    // 60% of Token Tax is allocated to core developers and operational management:
    // 40% Developer 1 (0xafF5...), 10% Developer 3 (0x3b52...), 10% Developer 4 (0x49fc...)
    const taxProtocolRevenue = tokenTax.clone(0.60);

    // 4. Daily Protocol Revenue: 100% of DEX Swap Dev Fees + 60% of Token Tax
    const dailyProtocolRevenue = options.createBalances();
    dailyProtocolRevenue.addBalances(swapFees, 'DEX Swap Fees To Protocol');
    dailyProtocolRevenue.addBalances(taxProtocolRevenue, 'Token Tax To Protocol Operations');

    // 5. Gross Protocol Fees: DEX Swap Fees + 100% Token Tax
    const dailyFees = options.createBalances();
    dailyFees.addBalances(swapFees, 'DEX Swap Fees');
    dailyFees.addBalances(tokenTax, 'Token Transfer Tax');

    // 6. Gross Profit / Total Revenue: dailyFees (dailyFees = dailyRevenue)
    const dailyRevenue = options.createBalances();
    dailyRevenue.addBalances(swapFees, 'DEX Swap Fees');
    dailyRevenue.addBalances(tokenTax, 'Token Transfer Tax');

    return {
        dailyFees,
        dailyRevenue,
        dailyProtocolRevenue,
        dailyHoldersRevenue,
        dailyVolume,
    };
};

const methodology = {
    Fees: "Total fees collected from DEX aggregator swaps (0.1% before June 8, 2026, and 0.5% thereafter) and the 4% token tax on ARB INC transfers.",
    Revenue: "All revenue generated by the protocol from DEX aggregator swap fees and the 4% token tax.",
    ProtocolRevenue: "Revenue retained for protocol operations, development, and management (100% of DEX swap fees and 60% of token tax via RevShare).",
    HoldersRevenue: "Net yield distributed to active ARB INC holders via the DEX leaderboard real-yield engine (40% RevShare treasury allocation with SAFE_FACTOR = 0.73 applied, delivering 29.2% of total token tax as net yield; the remaining 27% of the allocation serves as an on-chain gas fee reserve buffer).",
    Volume: "Trades executed on the Arbitrage Inc DEX platform across 100+ liquidity pools, calculated from collected swap fees divided by the fee rate (0.1% prior to June 8, 2026, 0.5% thereafter).",
};

const breakdownMethodology = {
    Fees: {
        'DEX Swap Fees': "Commission collected on swaps executed through the Arbitrage Inc aggregator frontend (0.1% prior to June 8, 2026, 0.5% thereafter).",
        'Token Transfer Tax': "4% transfer tax collected on ARB INC token buys and sells, received by the tax accumulator address.",
    },
    Revenue: {
        'DEX Swap Fees': "Protocol revenue from aggregator swap fees collected from trades.",
        'Token Transfer Tax': "Total revenue collected from the 4% ARB INC token transfer tax prior to distribution.",
    },
    ProtocolRevenue: {
        'DEX Swap Fees To Protocol': "100% of DEX swap dev fees allocated to protocol operations and core development.",
        'Token Tax To Protocol Operations': "60% of the token transfer tax distributed via RevShare to core developers and operational management (40% Dev 1, 10% Dev 3, 10% Dev 4).",
    },
    HoldersRevenue: {
        'Token Tax To Holders Yield': "Net yield distributed to active ARB INC holders via the DEX leaderboard engine (40% RevShare treasury allocation with SAFE_FACTOR = 0.73 applied, delivering 29.2% of total token tax as net yield; the remaining 27% of the allocation serves as an on-chain gas fee reserve buffer).",
    },
};

const adapter: SimpleAdapter = {
    version: 2,
    pullHourly: true,
    chains: [CHAIN.BSC],
    fetch,
    start: '2026-03-23',
    methodology,
    breakdownMethodology,
};

export default adapter;
