import { FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { SimpleAdapter } from "../../adapters/types";
import { METRIC } from "../../helpers/metrics";

const chainConfig = {
    [CHAIN.BERACHAIN]: {
        factory: '0x189bD734C2f1beeaca81e0edbB1cE3B8A16ed137',
        start: '2025-06-26',
        fromBlock: 6918218
    },
    [CHAIN.ETHEREUM]: {
        factory: '0x5B7B8b487D05F77977b7ABEec5F922925B9b2aFa',
        start: '2023-07-07',
        fromBlock: 17641488
    },
    [CHAIN.KATANA]: {
        factory: '0xF0F42C62923c6e741C64E0163C5C50965C05dF61',
        start: '2025-06-27',
        fromBlock: 4240014
    },
    [CHAIN.ARBITRUM]: {
        factory: '0x5b7b8b487d05f77977b7abeec5f922925b9b2afa',
        start: '2023-07-07',
        fromBlock: 108739231
    },
    [CHAIN.BASE]: {
        factory: '0x5b7b8b487d05f77977b7abeec5f922925b9b2afa',
        start: '2025-07-31',
        fromBlock: 1999920
    }
}

const vaultCreatedEvent = "event NewVault (address vault)"
const collectFeesEvent = "event CollectFees (uint256 feesToVault0, uint256 feesToVault1, uint256 feesToProtocol0, uint256 feesToProtocol1, uint256 feesToManager0, uint256 feesToManager1)"

async function fetch(options: FetchOptions) {
    const dailyFees = options.createBalances();
    const dailyRevenue = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();

    const { factory, fromBlock } = chainConfig[options.chain];

    const vaultCreationLogs = await options.getLogs({
        target: factory,
        eventAbi: vaultCreatedEvent,
        fromBlock,
        cacheInCloud: true,
    });

    const vaults = vaultCreationLogs.map((log: any) => log.vault);

    const [token0, token1] = await Promise.all([options.api.multiCall({
        abi: 'address:token0',
        calls: vaults,
        permitFailure: true,
    }), options.api.multiCall({
        abi: 'address:token1',
        calls: vaults,
        permitFailure: true,
    })]);

    const feeCollectLogs = await options.getLogs({
        targets: vaults,
        eventAbi: collectFeesEvent,
        flatten: false,
    });

    for (let i = 0; i < vaults.length; i++) {
        const tokenZero = token0[i];
        const tokenOne = token1[i];

        if(!tokenZero || !tokenOne) continue;

        feeCollectLogs[i].forEach((log: any) => {
            dailyFees.add(tokenZero, log.feesToVault0 + log.feesToManager0, METRIC.SWAP_FEES);
            dailyFees.add(tokenOne, log.feesToVault1 + log.feesToManager1, METRIC.SWAP_FEES);

            dailySupplySideRevenue.add(tokenZero, log.feesToManager0, 'Swap fees to LPs');
            dailySupplySideRevenue.add(tokenOne, log.feesToManager1, 'Swap fees to LPs');

            dailySupplySideRevenue.add(tokenZero, log.feesToVault0, 'Swap fees to vault');
            dailySupplySideRevenue.add(tokenOne, log.feesToVault1, 'Swap fees to vault');

            dailyFees.add(tokenZero, log.feesToProtocol0, METRIC.PERFORMANCE_FEES);
            dailyFees.add(tokenOne, log.feesToProtocol1, METRIC.PERFORMANCE_FEES);
            dailyRevenue.add(tokenZero, log.feesToProtocol0, METRIC.PERFORMANCE_FEES);
            dailyRevenue.add(tokenOne, log.feesToProtocol1, METRIC.PERFORMANCE_FEES);
        });
    }

    return {
        dailyFees,
        dailyRevenue,
        dailyProtocolRevenue: dailyRevenue,
        dailySupplySideRevenue,
    }

}

const methodology = {
    Fees: "Swap fees generated by providing liquidity to pools of various protocols",
    Revenue: "2-5% swap fees taken as performance fees",
    ProtocolRevenue: "2-5% swap fees taken as performance fees",
    SupplySideRevenue: "Swap fees going to LPs and vault post performance fees"
}

const breakdownMethodology = {
    Fees: {
        [METRIC.SWAP_FEES]: "Swap fees generated by providing liquidity to pools of various protocols",
        [METRIC.PERFORMANCE_FEES]: "2-5% swap fees taken as performance fees",
    },
    Revenue: {
        [METRIC.PERFORMANCE_FEES]: "2-5% swap fees taken as performance fees",
    },
    ProtocolRevenue: {
        [METRIC.PERFORMANCE_FEES]: "2-5% swap fees taken as performance fees",
    },
    SupplySideRevenue: {
        ['Swap fees to LPs']: "Swap fees going to LPs performance fees",
        ['Swap fees to vault']: "Small part of swap fees added back to the vault",
    }
}

const adapter: SimpleAdapter = {
    version: 2,
    pullHourly: true,
    fetch,
    adapter: chainConfig,
    methodology,
    breakdownMethodology,
    doublecounted: true, //dexs
}

export default adapter;