import { Dependencies, FetchOptions, FetchResult, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { queryDuneSql } from "../../helpers/dune";
import fetchURL from "../../utils/fetchURL";

/**
 * NEAR Intents fees adapter.
 *
 * Fees: Dune total (protocol fee + channel fees)
 * Revenue split: NEAR-retained share from revenue.near.org.
 */

const SPLIT_URL = "https://revenue.near.org/";

const feesQuery = (date: string) => `
  WITH pf AS (
    SELECT CAST(amount_fee AS double) AS fee
    FROM dune.near.dataset_near_intents_protocol_fees
    WHERE CAST(from_iso8601_timestamp(date_at) AS DATE) = DATE '${date}'
  ),
  cf AS (
    SELECT CAST(fee AS double) AS fee
    FROM dune.near.dataset_near_intents_fees
    WHERE CAST(from_iso8601_timestamp(date_at) AS DATE) = DATE '${date}'
  )
  SELECT
    (SELECT COALESCE(SUM(fee), 0) FROM pf) + (SELECT COALESCE(SUM(fee), 0) FROM cf) AS total_fees
`;

let splitHtml: Promise<string> | undefined;

// NEAR-retained (revenue) share for the day; undefined if not published.
async function getProtocolShare(dateString: string): Promise<number | undefined> {
  try {
    if (!splitHtml) splitHtml = fetchURL(SPLIT_URL);
    const text: string = (await splitHtml).replace(/\\"/g, '"');
    const matches = text.match(/\{"date_at":"\d{4}-\d{2}-\d{2}"[^{}]*\}/g) || [];
    for (const m of matches) {
      const obj = JSON.parse(m);
      if (obj.date_at === dateString && typeof obj.total_fees_near === "number" && obj.total_fees_near > 0) {
        return obj.protocol_fee_near / obj.total_fees_near;
      }
    }
  } catch {
    // fall through — report fees only
  }
  return undefined;
}

const fetch = async (options: FetchOptions): Promise<FetchResult> => {
  const { dateString, createBalances } = options;

  const dailyFees = createBalances();
  const dailyRevenue = createBalances();
  const dailySupplySideRevenue = createBalances();

  const rows = await queryDuneSql(options, feesQuery(dateString));
  const totalFees = Number(rows?.[0]?.total_fees) || 0;
  dailyFees.addUSDValue(totalFees);

  const protocolShare = await getProtocolShare(dateString);
  if (protocolShare !== undefined && totalFees > 0) {
    dailyRevenue.addUSDValue(totalFees * protocolShare);
    dailySupplySideRevenue.addUSDValue(totalFees * (1 - protocolShare));
    return { dailyFees, dailySupplySideRevenue, dailyRevenue, dailyProtocolRevenue: dailyRevenue };
  }

  return { dailyFees };
};

const adapter: SimpleAdapter = {
  version: 1,
  fetch,
  start: '2024-12-10',
  chains: [CHAIN.NEAR],
  dependencies: [Dependencies.DUNE],
  isExpensiveAdapter: true,
  methodology: {
    Fees: "Total fees generated by NEAR Intents (protocol fee + distribution-channel fees).",
    SupplySideRevenue: "Portion of fees paid out to integration partners, solvers and dApps under NEAR's revenue-sharing model.",
    Revenue: "Portion of fees retained by NEAR after ecosystem payouts.",
    ProtocolRevenue: "Retained fees go to the NEAR protocol treasury.",
  },
};

export default adapter;
