import fetchURL from "../../utils/fetchURL";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";

const API_URL = "https://api.affluent.org/v2/api/protocol/financials";

const toUsd = (value: any) => Number(value ?? 0);

type DailyHistory = {
    timestamp: number;
    grossRevenueBorrowInterest: number;
    grossRevenueVaultYield: number;
    grossRevenueLiquidationFee: number;
    costOfRevenueBorrowInterestPaidToLender: number;
    costOfRevenueVaultYieldPaidToDepositor: number;
    costOfRevenueVaultLiquidationFeePaidToLiquidator: number;
    grossProfit: number;
};

const fetch = async (_a: any, _b: any, options: FetchOptions) => {
    const dailyFees = options.createBalances();
    const dailyRevenue = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();

    const url = new URL(API_URL);
    url.searchParams.set("from", String(options.startTimestamp));
    url.searchParams.set("to", String(options.endTimestamp + 1));

    const res = await fetchURL(url.toString());

    const json = await res as {
        data?: {
            dailyHistories?: DailyHistory[];
        };
    };

    const histories = json?.data?.dailyHistories ?? [];

    const dayData = histories.reduce<typeof histories[number] | undefined>((best, item) => {
        if (item.timestamp <= options.endTimestamp) {
            if (!best || item.timestamp > best.timestamp) {
                return item;
            }
        }
        return best;
    }, undefined);

    if (!dayData) {
        return {
            dailyFees,
            dailyRevenue,
            dailySupplySideRevenue,
        };
    }

    dailyFees.addUSDValue(toUsd(dayData.grossRevenueBorrowInterest), METRIC.BORROW_INTEREST);
    dailyFees.addUSDValue(toUsd(dayData.grossRevenueVaultYield), METRIC.ASSETS_YIELDS);
    dailyFees.addUSDValue(toUsd(dayData.grossRevenueLiquidationFee), METRIC.LIQUIDATION_FEES);

    dailySupplySideRevenue.addUSDValue(toUsd(dayData.costOfRevenueBorrowInterestPaidToLender), METRIC.BORROW_INTEREST);
    dailySupplySideRevenue.addUSDValue(toUsd(dayData.costOfRevenueVaultYieldPaidToDepositor), METRIC.ASSETS_YIELDS);
    dailySupplySideRevenue.addUSDValue(toUsd(dayData.costOfRevenueVaultLiquidationFeePaidToLiquidator), METRIC.LIQUIDATION_FEES);

    dailyRevenue.addUSDValue(toUsd(dayData.grossProfit));

    return {
        dailyFees,
        dailyRevenue,
        dailySupplySideRevenue,
    };
};

const adapter: SimpleAdapter = {
    version: 1,
    fetch,
    start: "2025-01-20",
    methodology: {
        Fees:
            "Total gross revenue generated by the protocol, calculated as borrow interest + vault yield + liquidation fees.",
        SupplySideRevenue:
            "Revenue distributed to supply-side participants such as lenders, depositors, and liquidators.",
        Revenue:
            "Net revenue retained by the protocol after paying interest, yields, and liquidation rewards to suppliers.",
    },
    chains: [CHAIN.TON],
};

export default adapter;