import fetchURL from "../../utils/fetchURL";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";

const API_URL = "https://api.affluent.org/v2/api/protocol/financials";

const toUsd = (value: any) => Number(value ?? 0);

const fetch = async (_a: any, _b: any, options: FetchOptions) => {
    const dailyFees = options.createBalances();
    const dailyRevenue = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();

    const url = new URL(API_URL);
    url.searchParams.set("from", String(options.startTimestamp));
    url.searchParams.set("to", String(options.endTimestamp + 1));

    const res = await fetchURL(url.toString());

    const histories = res.data.dailyHistories;
    if (!histories) {
        throw new Error(`No data found for date ${options.dateString}`);
    }

    const dayData = histories.reduce((best: any, item: any) => {
        if (item.timestamp <= options.endTimestamp) {
            if (!best || item.timestamp > best.timestamp) {
                return item;
            }
        }
        return best;
    }, undefined);

    if (!dayData)
        throw new Error(`No data found for date ${options.dateString}`);

    dailyFees.addUSDValue(toUsd(dayData.grossRevenueBorrowInterest), METRIC.BORROW_INTEREST);
    dailyFees.addUSDValue(toUsd(dayData.grossRevenueVaultYield), METRIC.ASSETS_YIELDS);
    dailyFees.addUSDValue(toUsd(dayData.grossRevenueLiquidationFee), METRIC.LIQUIDATION_FEES);

    dailySupplySideRevenue.addUSDValue(toUsd(dayData.costOfRevenueBorrowInterestPaidToLender), METRIC.BORROW_INTEREST);
    dailySupplySideRevenue.addUSDValue(toUsd(dayData.costOfRevenueVaultYieldPaidToDepositor), METRIC.ASSETS_YIELDS);
    dailySupplySideRevenue.addUSDValue(toUsd(dayData.costOfRevenueVaultLiquidationFeePaidToLiquidator), METRIC.LIQUIDATION_FEES);

    dailyRevenue.addUSDValue(toUsd(dayData.grossRevenueBorrowInterest) - toUsd(dayData.costOfRevenueBorrowInterestPaidToLender), METRIC.BORROW_INTEREST);
    dailyRevenue.addUSDValue(toUsd(dayData.grossRevenueVaultYield) - toUsd(dayData.costOfRevenueVaultYieldPaidToDepositor), METRIC.ASSETS_YIELDS);
    dailyRevenue.addUSDValue(toUsd(dayData.grossRevenueLiquidationFee) - toUsd(dayData.costOfRevenueVaultLiquidationFeePaidToLiquidator), METRIC.LIQUIDATION_FEES);

    return {
        dailyFees,
        dailyRevenue,
        dailySupplySideRevenue,
        dailyProtocolRevenue: dailyRevenue,
    };
};

const methodology = {
    Fees:
        "Total gross revenue generated by the protocol, calculated as borrow interest + vault yield + liquidation fees.",
    SupplySideRevenue:
        "Revenue distributed to supply-side participants such as lenders, depositors, and liquidators.",
    Revenue:
        "Net revenue retained by the protocol after paying interest, yields, and liquidation rewards to suppliers.",
    ProtocolRevenue: "All the revenue is retained by the protocol",
};

const breakdownMethodology = {
    Fees: {
        [METRIC.BORROW_INTEREST]: "Total borrow interest generated",
        [METRIC.ASSETS_YIELDS]: "Total vault yield generated",
        [METRIC.LIQUIDATION_FEES]: "Total liquidation fees generated",
    },
    SupplySideRevenue: {
        [METRIC.BORROW_INTEREST]: "Borrow interest distributed to lenders",
        [METRIC.ASSETS_YIELDS]: "Vault yield distributed to depositors",
        [METRIC.LIQUIDATION_FEES]: "Liquidation fees distributed to liquidators",
    },
    Revenue: {
        [METRIC.BORROW_INTEREST]: "Borrow interest retained by the protocol",
        [METRIC.ASSETS_YIELDS]: "Vault yield retained by the protocol",
        [METRIC.LIQUIDATION_FEES]: "Liquidation fees retained by the protocol",
    },
};

const adapter: SimpleAdapter = {
    version: 1,
    fetch,
    start: "2025-01-20",
    methodology,
    breakdownMethodology,
    chains: [CHAIN.TON],
};

export default adapter;
