import { CHAIN } from "../../helpers/chains";
import { FetchOptions, Adapter } from "../../adapters/types";
import fetchURL from "../../utils/fetchURL";

// Foxify contract addresses
const contracts: any = {
    [CHAIN.SONIC]: {
        foxifyProxy: "0x6DB7d4B3Db759446Df89951149fC88088a0Ab2c3",
        fox: "0x261DFA2528dfa19011F10B168c856E02baaF0eb6",
        ebFox: "0xBD87A909F9A40FdaD6D9BE703E89A0383064D0Ab",
        foxiMaxi: "0x3725B740b33E75898e4e2E616E9BB519884edd37",
    },
};

// Foxify fee methodology
const methodology = {
    UserFees:
        "Trading fees paid by users when swapping tokens on Foxify DEX on Sonic blockchain.",
    Fees: "All trading fees collected by the Foxify protocol from token swaps and trading activities.",
    Revenue:
        "Total revenue generated by Foxify protocol from trading fees and platform activities.",
    ProtocolRevenue:
        "Portion of trading fees retained by Foxify protocol treasury for development and operations.",
    SupplySideRevenue:
        "Portion of trading fees distributed to liquidity providers and stakers as rewards.",
    HoldersRevenue:
        "Fees distributed to FOX token holders through staking and governance participation.",
};

// Foxify API-based fees fetch implementation using existing Foxify API
const fetch = async (options: FetchOptions) => {
    // Fetch data from Foxify's existing API endpoint
    const apiResponse = await fetchURL("https://api.foxify.trade/FoxifyStats");

    const dailyFees = apiResponse.fees?.daily || 0;

    // Since the API doesn't provide fee breakdown, we'll use the total daily fees
    // You may need to update this based on Foxify's actual fee distribution model
    return {
        dailyFees: dailyFees,
        dailyRevenue: dailyFees, // Assuming all fees are revenue for now
        dailyProtocolRevenue: dailyFees * 0.3, // Example: 30% to protocol (update with actual %)
        dailySupplySideRevenue: dailyFees * 0.7, // Example: 70% to LPs (update with actual %)
        dailyUserFees: dailyFees,
        dailyHoldersRevenue: 0, // Update if FOX holders receive fees
    };
};

const adapter: Adapter = {
    version: 2,
    methodology,
    adapter: {
        [CHAIN.SONIC]: {
            fetch,
            start: "2025-04-24",
        },
    },
};

export default adapter;
