import { Adapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

const USDAT = "0x23238f20b894f29041f48D88eE91131C395Aaa71";
const sUSDat = "0xD166337499E176bbC38a1FBd113Ab144e5bd2Df7";
const BPS = 10000;
const PERFORMANCE_FEE_BPS = 1000;
const sUSDatDecimals = 18;

// Sources:
// - USDat / sUSDat docs: https://saturncredit.gitbook.io/saturn-docs/solution
// - Fee and reserve docs: https://saturncredit.gitbook.io/saturn-docs/operations-and-governance/protocol-fee-and-risk-reserve
// - Verified contracts: https://etherscan.io/address/0xD166337499E176bbC38a1FBd113Ab144e5bd2Df7#code
// - M0 JMI yield model: https://docs.m0.org/build/models/treasury/jmi/overview/
const Event = {
    Deposit: "event Deposit(address indexed sender,address indexed owner,uint256 assets,uint256 shares)",
    RewardsReceived: "event RewardsReceived(uint256 strcAmount,uint256 amount)",
    YieldClaimed: "event YieldClaimed(uint256 amount)",
};
const ABI = {
    depositFeeBps: "uint256:depositFeeBps",
    getPrice: "function getPrice() view returns (uint256 price, uint8 priceDecimals)",
};

const fetch = async (options: FetchOptions) => {
    const dailyRevenue = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();

    const depositLogs = await options.getLogs({ target: sUSDat, eventAbi: Event.Deposit });

    if (depositLogs.length) {
        const feeBps = await options.api.call({ target: sUSDat, abi: ABI.depositFeeBps });
        if (feeBps) {
            depositLogs.forEach((log: any) => {
                // Deposit.assets is net of fees, so gross up the net amount to recover the deposit fee.
                const denominator = BPS - feeBps;
                const fee = Number(log.assets) * feeBps / denominator;
                dailyRevenue.add(USDAT, fee, METRIC.DEPOSIT_WITHDRAW_FEES);
            });
        }
    }

    const [priceBefore, priceAfter, totalSupply] = await Promise.all([
        options.fromApi.call({
            target: sUSDat,
            abi: 'function convertToAssets(uint256 shares) external view returns (uint256)',
            params: ['1000000000000000000'],
        }),
        options.toApi.call({
            target: sUSDat,
            abi: 'function convertToAssets(uint256 shares) external view returns (uint256)',
            params: ['1000000000000000000'],
        }),
        options.api.call({
            target: sUSDat,
            abi: 'uint256:totalSupply',
        }),
    ])

    const yieldForPeriod = (priceAfter - priceBefore) * totalSupply / 10 ** sUSDatDecimals;
    const performanceFee = yieldForPeriod * PERFORMANCE_FEE_BPS / (BPS - PERFORMANCE_FEE_BPS);

    dailyRevenue.add(USDAT, performanceFee, METRIC.PERFORMANCE_FEES);
    dailySupplySideRevenue.add(USDAT, yieldForPeriod, METRIC.ASSETS_YIELDS);

    const dailyFees = dailyRevenue.clone();
    dailyFees.add(dailySupplySideRevenue);

    return {
        dailyFees,
        dailyRevenue,
        dailySupplySideRevenue,
        dailyProtocolRevenue: dailyRevenue,
    };
};

const methodology = {
    Fees: "Fees include sUSDat deposit fees if any, asset yields from sUSDat price appreciation and 10% perfomance fee on the yield generated by sUSDat",
    Revenue: "Saturn earns sUSDat deposit fees, and 10% performance fee on the yield generated by sUSDat.",
    ProtocolRevenue: "Saturn earns sUSDat deposit fees, and 10% performance fee on the yield generated by sUSDat.",
    SupplySideRevenue: "Yield generated by sUSDat price appreciation.",
};

const breakdownMethodology = {
    Fees: {
        [METRIC.DEPOSIT_WITHDRAW_FEES]: "Fees paid when users deposit USDat into sUSDat.",
        [METRIC.ASSETS_YIELDS]: "Yield generated by sUSDat price appreciation.",
        [METRIC.PERFORMANCE_FEES]: "10% performance fee on the yield generated by sUSDat.",
    },
    Revenue: {
        [METRIC.DEPOSIT_WITHDRAW_FEES]: "Deposit fees kept by Saturn.",
        [METRIC.PERFORMANCE_FEES]: "10% performance fee on the yield generated by sUSDat.",
    },
    ProtocolRevenue: {
        [METRIC.DEPOSIT_WITHDRAW_FEES]: "Deposit fees kept by Saturn.",
        [METRIC.PERFORMANCE_FEES]: "10% performance fee on the yield generated by sUSDat.",
    },
    SupplySideRevenue: {
        [METRIC.ASSETS_YIELDS]: "Yield generated by sUSDat price appreciation.",
    },
};

const adapter: Adapter = {
    version: 2,
    pullHourly: true,
    chains: [CHAIN.ETHEREUM],
    start: "2026-03-10",
    fetch,
    methodology,
    breakdownMethodology,
    allowNegativeValue: true,
};

export default adapter;
