import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const SUPERVAULT_AGGREGATOR = "0x10AC0b33e1C4501CF3ec1cB1AE51ebfdbd2d4698";

const GET_SUPERVAULT_STRATEGIES_ABI = "function getAllSuperVaultStrategies() view returns (address[])";
const GET_VAULT_INFO_ABI = "function getVaultInfo() view returns (address vault, address asset, uint8 vaultDecimals)";

const MANAGEMENT_FEE_EVENT = "event ManagementFeePaid(address indexed controller, address indexed recipient, uint256 feeAssets, uint256 feeBps)";
const PERFORMANCE_FEE_EVENT = "event PerformanceFeeSkimmed(uint256 totalFee, uint256 superformFee)";
const HWMPPS_UPDATE_EVENT = "event HWMPPSUpdated(uint256 newHwmPps, uint256 previousPps, uint256 profit, uint256 feeCollected)";

const fetch = async (options: FetchOptions) => {
    const { getLogs, createBalances, api } = options;
    const dailyFees = createBalances();
    const dailyUserFees = createBalances();
    const dailySupplySideRevenue = createBalances();
    const dailyRevenue = createBalances();
    const dailyHoldersRevenue = createBalances();
    const dailyProtocolRevenue = createBalances();

    const strategies: string[] = await api.call({ 
        abi: GET_SUPERVAULT_STRATEGIES_ABI, 
        target: SUPERVAULT_AGGREGATOR 
    });

    const vaultInfo = await api.multiCall({
      abi: GET_VAULT_INFO_ABI,
      calls: strategies.map(strat => ({ target: strat }))
    });

    const strategyMap = Object.fromEntries(
        strategies.map((s, i) => [s.toLowerCase(), vaultInfo[i].asset.toLowerCase()])
    );
    
    const performanceFeeLogs = await getLogs({
        targets: Object.keys(strategyMap),
        eventAbi: PERFORMANCE_FEE_EVENT,
        entireLog: true,
    });

    const updateLogs = await getLogs({
        targets: Object.keys(strategyMap),
        eventAbi: HWMPPS_UPDATE_EVENT,
        entireLog: true,
    });

    if (performanceFeeLogs.length === 0 || updateLogs.length === 0) {
        return { 
            dailyFees, 
            dailyUserFees,
            dailySupplySideRevenue,
            dailyRevenue,
            dailyHoldersRevenue, 
            dailyProtocolRevenue,  
        };
    };

    const combinedLogs: { 
        strategy: string, 
        totalFee: bigint, 
        superformFee: bigint, 
        profit: bigint 
    }[] = [];

    for (const perfLog of performanceFeeLogs) {
        const updateLog = updateLogs.find((log) => log.transactionHash.toLowerCase() === perfLog.transactionHash.toLowerCase());
        if (!updateLog) continue;
        combinedLogs.push({
            strategy: updateLog.address,
            totalFee: perfLog.args.totalFee,
            superformFee: perfLog.args.superformFee,
            profit: updateLog.args.profit
        });
    };

    for (const log of combinedLogs) {
        const underlying = strategyMap[log.strategy.toLowerCase()];
        if (!underlying) continue;
        dailyFees.add(underlying, log.profit);
        dailyUserFees.add(underlying, log.totalFee);
        dailySupplySideRevenue.add(underlying, log.profit - log.totalFee);
        dailyRevenue.add(underlying, log.superformFee);
        if (options.endTimestamp >= 1771472040) {
            dailyHoldersRevenue.add(underlying, log.superformFee * 2n / 10n);
            dailyProtocolRevenue.add(underlying, log.superformFee * 8n / 10n);
        } else {
            dailyProtocolRevenue.add(underlying, log.superformFee);
        };
    };

    const managementFeeLogs = await getLogs({
        targets: Object.keys(strategyMap),
        eventAbi: MANAGEMENT_FEE_EVENT,
        entireLog: true,
    });

    for (const manageLogs of managementFeeLogs) {
        const underlying = strategyMap[manageLogs.address.toLowerCase()];
        if (!underlying) continue;
        dailyFees.add(underlying, manageLogs.feeAssets);
        dailyUserFees.add(underlying, manageLogs.feeAssets);
        dailyRevenue.add(underlying, manageLogs.feeAssets);
        if (options.endTimestamp >= 1771472040) {
            dailyHoldersRevenue.add(underlying, manageLogs.feeAssets * 2n / 10n);
            dailyProtocolRevenue.add(underlying, manageLogs.feeAssets * 8n / 10n);
        } else {
            dailyProtocolRevenue.add(underlying, manageLogs.feeAssets);
        };
    };

    return { 
        dailyFees, 
        dailyUserFees,
        dailySupplySideRevenue,
        dailyRevenue,
        dailyHoldersRevenue, 
        dailyProtocolRevenue,  
    };
};

const methodology = {
    Fees: "All yield generated by the protocol.",
    UserFees: "Vault management and protocol fees paid by users.",
    SupplySideRevenue: "Actual yield distributed to vaults.",
    Revenue: "Fees paid directly to Superform.",
    HoldersRevenue: "20% of protocol fees are sent to the sUP vault.",
    ProtocolRevenue: "80% of protocol fees are sent to the Superform Foundation treasury."
};

// const breakdownMethodology

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  methodology,
  // breakdownMethodology,
  fetch,
  chains: [CHAIN.ETHEREUM, CHAIN.BASE],
  start: '2025-12-03'
};


export default adapter;