import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import ADDRESSES from '../../helpers/coreAssets.json'

// key: strategy address, value: underlying address
const STRATEGY_MAPS = {
    ethereum: new Map([
        ["0x41A9Eb398518D2487301c61D2b33E4e966A9F1DD".toLowerCase(), ADDRESSES.ethereum.USDC],
        ["0x1199a6B2587Ed96446E76Dee3FB660bb8fCfd0b2".toLowerCase(), ADDRESSES.ethereum.WETH],
        ["0xa96060B0B6907406EdBDf3cCc9438abf0F78Cf83".toLowerCase(), ADDRESSES.ethereum.WBTC]
    ]),
    base: new Map([
        ["0x2787a17fe04C73AD109370C90917d62D1899Eb6A".toLowerCase(), ADDRESSES.base.WETH],
        ["0x5bE8c059A8E101d24B107aFb5A013feF505280b9".toLowerCase(), ADDRESSES.base.USDC],
        ["0x0c14c751b19D4362f14f4A1D1cB963180B63fB87".toLowerCase(), ADDRESSES.base.cbBTC],
    ]),
};

const MANAGEMENT_FEE_EVENT = "event ManagementFeePaid(address indexed controller, address indexed recipient, uint256 feeAssets, uint256 feeBps)";
const PERFORMANCE_FEE_EVENT = "event PerformanceFeeSkimmed(uint256 totalFee, uint256 superformFee)";
const HWMPPS_UPDATE_EVENT = "event HWMPPSUpdated(uint256 newHwmPps, uint256 previousPps, uint256 profit, uint256 feeCollected)";

const fetch = async (options: FetchOptions) => {
    const { getLogs, createBalances } = options;
    const dailyFees = createBalances();
    const dailyUserFees = createBalances();
    const dailySupplySideRevenue = createBalances();
    const dailyRevenue = createBalances();
    const dailyHoldersRevenue = createBalances();
    const dailyProtocolRevenue = createBalances();

    const strategyMap = STRATEGY_MAPS[options.chain as keyof typeof STRATEGY_MAPS];

    const performanceFeeLogs = await getLogs({
        targets: [...strategyMap.keys()],
        eventAbi: PERFORMANCE_FEE_EVENT,
        entireLog: true,
    });

    const updateLogs = await getLogs({
        targets: [...strategyMap.keys()],
        eventAbi: HWMPPS_UPDATE_EVENT,
        entireLog: true,
    });

    if (performanceFeeLogs.length === 0 || updateLogs.length === 0) {
        return { 
            dailyFees, 
            dailyUserFees,
            dailySupplySideRevenue,
            dailyRevenue,
            dailyHoldersRevenue, 
            dailyProtocolRevenue,  
        };
    };

    const combinedLogs: { 
        strategy: string, 
        totalFee: bigint, 
        superformFee: bigint, 
        profit: bigint 
    }[] = [];

    for (const perfLog of performanceFeeLogs) {
        const updateLog = updateLogs.find((log) => log.transactionHash.toLowerCase() === perfLog.transactionHash.toLowerCase());
        if (!updateLog) continue;
        combinedLogs.push({
            strategy: updateLog.address,
            totalFee: perfLog.args.totalFee,
            superformFee: perfLog.args.superformFee,
            profit: updateLog.args.profit
        });
    };

    for (const log of combinedLogs) {
        const underlying = strategyMap.get(log.strategy.toLowerCase());
        if (!underlying) continue;
        dailyFees.add(underlying, log.profit);
        dailyUserFees.add(underlying, log.totalFee);
        dailySupplySideRevenue.add(underlying, log.profit - log.totalFee);
        dailyRevenue.add(underlying, log.superformFee);
        if (options.endTimestamp >= 1771472040) {
            dailyHoldersRevenue.add(underlying, log.superformFee * 2n / 10n);
            dailyProtocolRevenue.add(underlying, log.superformFee * 8n / 10n);
        } else {
            dailyProtocolRevenue.add(underlying, log.superformFee);
        };
    };

    const managementFeeLogs = await getLogs({
        targets: [...strategyMap.keys()],
        eventAbi: MANAGEMENT_FEE_EVENT,
        entireLog: true,
    });

    for (const manageLogs of managementFeeLogs) {
        const underlying = strategyMap.get(manageLogs.address.toLowerCase());
        if (!underlying) continue;
        dailyFees.add(underlying, manageLogs.feeAssets);
        dailyUserFees.add(underlying, manageLogs.feeAssets);
        dailyRevenue.add(underlying, manageLogs.feeAssets);
        if (options.endTimestamp >= 1771472040) {
            dailyHoldersRevenue.add(underlying, manageLogs.feeAssets * 2n / 10n);
            dailyProtocolRevenue.add(underlying, manageLogs.feeAssets * 8n / 10n);
        } else {
            dailyProtocolRevenue.add(underlying, manageLogs.feeAssets);
        };
    };

    return { 
        dailyFees, 
        dailyUserFees,
        dailySupplySideRevenue,
        dailyRevenue,
        dailyHoldersRevenue, 
        dailyProtocolRevenue,  
    };
};

const methodology = {
    Fees: "All yield generated by the protocol.",
    UserFees: "Vault management and protocol fees paid by users.",
    SupplySideRevenue: "Actual yield distributed to vaults.",
    Revenue: "Fees paid directly to Superform.",
    HoldersRevenue: "20% of protocol fees are sent to the sUP vault.",
    ProtocolRevenue: "80% of protocol fees are sent to the Superform Foundation treasury."
};

const adapter: SimpleAdapter = {
  version: 2,
  methodology,
  fetch,
  chains: [CHAIN.ETHEREUM, CHAIN.BASE],
  start: '2025-12-03'
};


export default adapter;