import { Adapter, FetchV2 } from '../../adapters/types';
import { CHAIN } from '../../helpers/chains';
import fetchURL from '../../utils/fetchURL';

const turbosApiURL = 'https://api.turbos.finance/dex/defillama/fees';

interface TurbosStats {
  fee: string;
  protocolFee: string;
}

const methodology = {
  Fees: 'Swap fees generated by the swap transactions on Turbos Protocol.',
  Revenue: 'Protocol fees charged from the swap fees.',
  SupplySideRevenue: 'Swap fees distributed to liquidity providers.',
  ProtocolRevenue: 'Protocol fees charged from the swap fees.',
};

const fetchTurbosStats: FetchV2 = async ({ startTimestamp, endTimestamp })=> {
  const url = `${turbosApiURL}?start=${startTimestamp}&end=${endTimestamp}`;
  const { fee, protocolFee }: TurbosStats = await fetchURL(url);
  const dailySupplySideRevenue = Number(fee) - Number(protocolFee);
  return {
    dailyFees: fee,
    dailyRevenue: protocolFee,
    dailySupplySideRevenue,
    dailyProtocolRevenue: protocolFee,
  };
};

const adapter: Adapter = {
  version: 2,
  adapter: {
    [CHAIN.SUI]: {
      fetch: fetchTurbosStats,
      start: '2023-05-01',
    },
  },
  methodology,
};

export default adapter;
