import { Adapter, FetchOptions } from '../../adapters/types';
import { CHAIN } from '../../helpers/chains';
import fetchURL from '../../utils/fetchURL';

const turbosApiURL = 'https://api.turbos.finance/dex/defillama/fees';

interface TurbosStats {
  fee: string;
  protocolFee: string;
}

const fetch = async (options: FetchOptions) => {

  const url = `${turbosApiURL}?start=${options.startTimestamp}&end=${options.endTimestamp}`;
  const { fee, protocolFee }: TurbosStats = await fetchURL(url);
  const dailySupplySideRevenue = Number(fee) - Number(protocolFee);

  return {
    dailyFees: fee,
    dailyRevenue: protocolFee,
    dailySupplySideRevenue,
    dailyProtocolRevenue: protocolFee,
  };
};

const methodology = {
  Fees: 'Swap fees generated by the swap transactions on Turbos Protocol.',
  Revenue: 'Protocol fees charged from the swap fees.',
  SupplySideRevenue: 'Swap fees distributed to liquidity providers.',
  ProtocolRevenue: 'Protocol fees charged from the swap fees.',
};

const adapter: Adapter = {
  version: 2,
  fetch,
  chains: [CHAIN.SUI],
  start: '2023-05-01',
  methodology,
};

export default adapter;
