import { FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getSolanaReceived } from "../../helpers/token";
import { getSqlFromFile, queryDuneSql } from "../../helpers/dune";

const FEE_COLLECTOR_ADDRESS = "DG399HKiLgKxGG176QiojyTtiSeqAurK6FVXGfBPTzSD";
const JUPITER_STAKE_ACCOUNT = "FMAWbzuxsgbgndArunedwxXPA6sweaVUGGgadCpSxau2";
const JUPITER_AUTHORITY = "EMjuABxELpYWYEwjkKmQKBNCwdaFAy4QYAs6W9bDQDNw";

const fetch = async (_a: any, _b: any, options: FetchOptions) => {
  const query = getSqlFromFile("helpers/queries/solana-liquid-staking-fees.sql", {
    start: options.startTimestamp,
    end: options.endTimestamp,
    stake_account: JUPITER_STAKE_ACCOUNT,
    authority: JUPITER_AUTHORITY
  });
  const stake_rewards = await queryDuneSql(options, query);
  const dailyFees = options.createBalances();
  dailyFees.addCGToken("solana", stake_rewards[0].daily_yield != null ? stake_rewards[0].daily_yield : 0);

  const dailyRevenue = await getSolanaReceived({
    options,
    target: FEE_COLLECTOR_ADDRESS
  });

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue: dailyFees.subtract(dailyRevenue)
  };
};

const meta = {
  methodology: {
    Fees: 'Staking yield rewards generated by the vault',
    Revenue: 'Includes withdrawal fees and management fees collected by fee collector',
    ProtocolRevenue: 'Revenue going to treasury/team',
    SupplySideRevenue: 'Staking yield received by JUPSOL liquid token holders, which is 100% of the staking yield generated by the vault except for the withdrawal fees',
  }
}

export default {
  version: 1,
  adapter: {
    [CHAIN.SOLANA]: {
      fetch,
      start: "2024-06-09",
      meta
    }
  },
  isExpensiveAdapter: true
};
