import { SimpleAdapter, FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const SWAP_PROXY = "0x37ccd90ed5fa96207b41c4fbcb90b883e30e63dc";

const SUPPORTED_ASSETS: string[] = [
  "0x47c98f74dBC1acc4cf2e04C4a729E22379EF4373",
  "0x545e289b88c6d97b74ec0b96e308cae46bf5f832",
  "0xdc1a8a35b0baa3229b13f348ed708a2fd50b5e3a",
].map((a) => a.toLowerCase());

const TRANSFER_EVENT = "event Transfer(address indexed from, address indexed to, uint256 value)";

function eq(a?: string, b?: string) {
  return (a ?? "").toLowerCase() === (b ?? "").toLowerCase();
}

const fetch = async (options: FetchOptions) => {
  const dailyVolume = options.createBalances();

  for (const token of SUPPORTED_ASSETS) {
    const logs: any[] = await options.getLogs({
      target: token,
      eventAbi: TRANSFER_EVENT,
    });

    for (const log of logs) {
      const from = log.from;
      const to = log.to;
      const value = log.value;

      if (eq(to, SWAP_PROXY) || eq(from, SWAP_PROXY)) {
        dailyVolume.add(token, value);
      }
    }
  }

  return { dailyVolume };
};

const adapter: SimpleAdapter = {
  version: 2,
  chains: [CHAIN.ENI],
  fetch,
  start: "2025-06-09",
  methodology: {
    Volume:
      "Sums ERC20 Transfer amounts of supported swap assets that move into or out of the EGAS Swap proxy contract. " +
      "Each swap is reflected by transfers that touch the proxy, so aggregating these transfers provides swap volume. " +
      "As new assets are supported, they can be included by adding their token addresses to the supported assets list in the adapter.",
    Fees: "No fees are charged by the protocol.",
    Revenue: "No revenue is generated by the protocol.",
  },
};

export default adapter;
