import { FetchOptions, FetchResultV2, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const VAULT = "0xd1074E0AE85610dDBA0147e29eBe0D8E5873a000";

const BoringVaultAbis = {
    hook: "address:hook",
    decimals: "uint8:decimals",
    totalSupply: "uint256:totalSupply",
    accountant: "address:accountant",
    base: "address:base",
    exchangeRateUpdated: "event ExchangeRateUpdated(uint96 oldRate, uint96 newRate, uint64 currentTime)",
    accountantState: "function accountantState() view returns(address,uint128,uint128,uint96,uint16,uint16,uint64,bool,uint32,uint16)",
};

// BoringVault (Veda) tracks yield via ExchangeRateUpdated events in the accountant
const fetch = async (options: FetchOptions): Promise<FetchResultV2> => {
    const dailyFees = options.createBalances();

    const decimals = await options.api.call({ abi: BoringVaultAbis.decimals, target: VAULT });
    const hook = await options.api.call({ abi: BoringVaultAbis.hook, target: VAULT });
    const accountant = await options.api.call({ abi: BoringVaultAbis.accountant, target: hook });
    const baseToken = await options.api.call({ abi: BoringVaultAbis.base, target: accountant });

    const vaultRateBase = 10 ** Number(decimals);

    const logs = await options.getLogs({
        target: accountant,
        eventAbi: BoringVaultAbis.exchangeRateUpdated,
        onlyArgs: false,
    });

    for (const log of logs) {
        const oldRate = Number(log.args.oldRate);
        const newRate = Number(log.args.newRate);
        const growthRate = newRate > oldRate ? newRate - oldRate : 0;

        if (growthRate > 0) {
            // Get total supply at the rate update block
            const totalSupplyAtUpdate = await options.api.call({
                abi: BoringVaultAbis.totalSupply,
                target: VAULT,
                block: log.blockNumber,
                chain: options.chain,
            });

            const yieldAmount = Number(totalSupplyAtUpdate) * growthRate / vaultRateBase;

            dailyFees.add(baseToken, yieldAmount);
        }
    }

    return { dailyFees, dailyRevenue: 0, dailySupplySideRevenue: dailyFees };
};

const adapter: SimpleAdapter = {
    version: 2,
    adapter: {
        [CHAIN.PLASMA]: {
            fetch,
            start: "2025-09-11",
        }
    },
    methodology: {
        Fees: "Total yield generated by the Plasma Saving Vaults.",
        Revenue: "No fees are collected by the protocol.",
        SupplySideRevenue: "Revenue earned by Plasma Saving Vault liquidity providers."
    }
};

export default adapter;