import { FetchOptions, FetchResultV2, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const VAULT = "0xd1074E0AE85610dDBA0147e29eBe0D8E5873a000";

const BoringVaultAbis = {
  hook: "address:hook",
  decimals: "uint8:decimals",
  totalSupply: "uint256:totalSupply",
  accountant: "address:accountant",
  base: "address:base",
  getRate: "uint256:getRate",
};

// BoringVault (Veda) tracks yield via ExchangeRateUpdated events in the accountant
const fetch = async (options: FetchOptions): Promise<FetchResultV2> => {
  const dailyFees = options.createBalances();

  const decimals = await options.api.call({ abi: BoringVaultAbis.decimals, target: VAULT });
  const hook = await options.api.call({ abi: BoringVaultAbis.hook, target: VAULT });
  const accountant = await options.api.call({ abi: BoringVaultAbis.accountant, target: hook });
  const baseToken = await options.api.call({ abi: BoringVaultAbis.base, target: accountant });
  const totalSupply = await options.fromApi.call({ abi: BoringVaultAbis.totalSupply, target: VAULT });


  const oldRate = await options.fromApi.call({ target: accountant, abi: BoringVaultAbis.getRate });
  const newRate = await options.toApi.call({ target: accountant, abi: BoringVaultAbis.getRate });

  const growthRate = BigInt(newRate) > BigInt(oldRate) ? BigInt(newRate) - BigInt(oldRate) : 0n;

  const vaultRateBase = BigInt(10 ** Number(decimals));
  const yieldAmount = BigInt(totalSupply) * growthRate / vaultRateBase

  dailyFees.add(baseToken, yieldAmount);
  
  return { dailyFees, dailyRevenue: 0, dailySupplySideRevenue: dailyFees };
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.PLASMA]: {
      fetch,
      start: "2025-09-11",
    }
  },
  methodology: {
    Fees: "Total yield generated by the Plasma Saving Vaults.",
    Revenue: "No fees are collected by the protocol.",
    SupplySideRevenue: "All yields earned by Plasma Saving Vault are distributed to depositors."
  }
};

export default adapter;