import { Adapter, FetchOptions } from '../../adapters/types';
import { CHAIN } from '../../helpers/chains';
import { METRIC } from '../../helpers/metrics';
import fetchURL from '../../utils/fetchURL';

const cetusApiURL = 'https://api-sui.cetus.zone/v3/sui/daily-fees';

interface CetusStats {
  data: {
    fee: string;
    protocolFee: string;
  }
}

const methodology = {
  Fees: 'Swap fees generated by the swap transactions on Cetus Protocol.',
  Revenue: 'Protocol fees charged from the swap fees.',
  SupplySideRevenue: 'Amount of swap fees are distributed to LPs.',
  ProtocolRevenue: 'Protocol fees charged from the swap fees.',
};

const breakdownMethodology = {
  Fees: {
    [METRIC.SWAP_FEES]: 'All swap fees paid by users when trading on Cetus DEX',
  },
  Revenue: {
    [METRIC.PROTOCOL_FEES]: 'Portion of swap fees retained by the Cetus protocol treasury',
  },
  SupplySideRevenue: {
    [METRIC.LP_FEES]: 'Portion of swap fees distributed to liquidity providers',
  },
};

const fetch = async (options: FetchOptions) => {
  const url = `${cetusApiURL}?fromTimestamp=${options.startTimestamp}&toTimestamp=${options.endTimestamp}`;
  const { data }: CetusStats = await fetchURL(url);
  const swap_fees = data.fee;
  const rev_usd = data.protocolFee;
  const supply_side_rev_usd = Number(swap_fees) - Number(rev_usd);

  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  dailyFees.addUSDValue(Number(swap_fees), METRIC.SWAP_FEES);
  dailyRevenue.addUSDValue(Number(rev_usd), METRIC.PROTOCOL_FEES);
  dailySupplySideRevenue.addUSDValue(Number(supply_side_rev_usd), METRIC.LP_FEES);

  return {
    dailyFees,
    dailyRevenue,
    dailySupplySideRevenue,
    dailyProtocolRevenue: dailyRevenue,
  };
};

const adapter: Adapter = {
  version: 2,
  chains: [CHAIN.SUI],
  fetch,
  start: '2024-01-01',
  methodology,
  breakdownMethodology,
};

export default adapter;
