import { Adapter, FetchOptions } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import request, { gql } from "graphql-request";
import { METRIC } from "../helpers/metrics";

type ChainConfig = {
  start: string;
  endpoint: string;
}

type DailySnapshot = {
  borrowFeesGenerated: string;
  interestFeesGenerated: string;
  liquidationFeesGenerated: string;
}

type GraphResponse = {
  protocolDailySnapshots: DailySnapshot[];
}

const MIM = "magic-internet-money";
const BORROW_FEES = "Borrow Fees";
const BASE_URL = "https://api.studio.thegraph.com/query/56065";

const chainConfig: Record<string, ChainConfig> = {
  [CHAIN.ETHEREUM]: { start: "2021-09-01", endpoint: `${BASE_URL}/cauldrons/version/latest` },
  [CHAIN.OPTIMISM]: { start: "2022-10-28", endpoint: `${BASE_URL}/cauldrons-optimism/version/latest` },
  [CHAIN.FANTOM]: { start: "2021-09-01", endpoint: `${BASE_URL}/cauldrons-fantom/version/latest` },
  [CHAIN.KAVA]: { start: "2023-05-01", endpoint: "https://kava.graph.abracadabra.money/subgraphs/name/cauldrons" },
  [CHAIN.ARBITRUM]: { start: "2021-09-01", endpoint: `${BASE_URL}/cauldrons-arbitrum/version/latest` },
  [CHAIN.AVAX]: { start: "2021-09-01", endpoint: `${BASE_URL}/cauldrons-avalanche/version/latest` },
};

const graphQuery = gql`
  query Fees($timestamp: Int!) {
    protocolDailySnapshots(where: { timestamp: $timestamp }) {
      borrowFeesGenerated
      interestFeesGenerated
      liquidationFeesGenerated
    }
  }
`;

const fetch = async (_a: any, _b: any, options: FetchOptions) => {
  const { protocolDailySnapshots } = await request<GraphResponse>(
    chainConfig[options.chain].endpoint,
    graphQuery,
    { timestamp: options.startOfDay },
  );
  const snapshot = protocolDailySnapshots[0];
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  if (snapshot) {
    dailyFees.addCGToken(MIM, Number(snapshot.interestFeesGenerated), METRIC.BORROW_INTEREST);
    dailyFees.addCGToken(MIM, Number(snapshot.borrowFeesGenerated), BORROW_FEES);
    dailyFees.addCGToken(MIM, Number(snapshot.liquidationFeesGenerated), METRIC.LIQUIDATION_FEES);
    dailyRevenue.addCGToken(MIM, Number(snapshot.interestFeesGenerated) / 2, METRIC.PROTOCOL_FEES);
    dailyRevenue.addCGToken(MIM, Number(snapshot.borrowFeesGenerated) / 2, METRIC.PROTOCOL_FEES);
    dailySupplySideRevenue.addCGToken(MIM, Number(snapshot.interestFeesGenerated) / 2, METRIC.BORROW_INTEREST);
    dailySupplySideRevenue.addCGToken(MIM, Number(snapshot.borrowFeesGenerated) / 2, BORROW_FEES);
    dailySupplySideRevenue.addCGToken(MIM, Number(snapshot.liquidationFeesGenerated), METRIC.LIQUIDATION_FEES);
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Daily fees generated by Abracadabra Cauldrons, including interest, borrow/opening fees, and liquidation fees reported by Abracadabra analytics subgraphs.",
  Revenue: "50% of Cauldron interest and borrow/opening fees retained by the Abracadabra protocol. Liquidation fees are excluded as they are paid to liquidators.",
  ProtocolRevenue: "50% of Cauldron interest and borrow/opening fees retained by the Abracadabra protocol. Liquidation fees are excluded as they are paid to liquidators.",
  SupplySideRevenue: "50% of Cauldron interest and borrow/opening fees distributed to lenders and fee recipients, plus 100% of liquidation fees paid to liquidators.",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.BORROW_INTEREST]: "Interest fees generated by Abracadabra Cauldrons.",
    [BORROW_FEES]: "Borrow/opening fees generated when users borrow from Cauldrons.",
    [METRIC.LIQUIDATION_FEES]: "Liquidation fees generated by Cauldron liquidations.",
  },
  Revenue: {
    [METRIC.PROTOCOL_FEES]: "50% of interest and borrow/opening fees retained by the Abracadabra protocol.",
  },
  ProtocolRevenue: {
    [METRIC.PROTOCOL_FEES]: "50% of interest and borrow/opening fees retained by the Abracadabra protocol.",
  },
  SupplySideRevenue: {
    [METRIC.BORROW_INTEREST]: "50% of interest fees distributed to lenders and fee recipients.",
    [BORROW_FEES]: "50% of borrow/opening fees distributed to lenders and fee recipients.",
    [METRIC.LIQUIDATION_FEES]: "100% of liquidation fees paid to liquidators.",
  },
};

const adapter: Adapter = {
  version: 1,
  adapter: chainConfig,
  fetch,
  methodology,
  breakdownMethodology,
};

export default adapter;
