import { Adapter, FetchOptions, FetchResultV2 } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { METRIC } from "../helpers/metrics";
import { getERC4626VaultsYield } from "../helpers/erc4626";

// Alchemix V3 deploys its yield-bearing collateral as standalone ERC-4626 "MYT"
// vaults from a VaultV2Factory on each chain. Each vault accrues yield to its
// share price (convertToAssets grows over time); Alchemix takes a 10% protocol
// fee on that yield and 90% repays users' self-repaying loans.
//
// These vaults are a separate contract set from the V2 alchemists (which
// fees/alchemix.ts tracks via the Harvest event), so the two adapters do not
// overlap.

const CREATE_VAULT_EVENT =
  "event CreateVaultV2(address indexed owner, address indexed asset, bytes32 salt, address indexed newVaultV2)";

// Factories are the same source the V3 TVL adapter enumerates vaults from:
// https://github.com/DefiLlama/DefiLlama-Adapters/blob/master/projects/alchemix-v3/index.js
// fromBlock = the factory deployment block on each chain (ETH factory deployed 2026-04-14).
const chainConfig: Record<string, { start: string; factory: string; fromBlock: number }> = {
  [CHAIN.ETHEREUM]: { start: "2026-04-14", factory: "0xdd56b00302e91C4c2b8246156bDEAa1cEDc58984", fromBlock: 24875892 },
  [CHAIN.ARBITRUM]: { start: "2026-04-14", factory: "0x8c7C0C380bA4eE38461eb5a6b82e5d930EC11Ca2", fromBlock: 452291175 },
  [CHAIN.OPTIMISM]: { start: "2026-04-14", factory: "0x8c7C0C380bA4eE38461eb5a6b82e5d930EC11Ca2", fromBlock: 150271732 },
};

// Alchemix takes 10% of generated yield; the other 90% repays users' loans.
// Same split the existing V2 adapter (fees/alchemix.ts) applies to Alchemix yield.
const PROTOCOL_FEE = 0.1;

async function fetch(options: FetchOptions): Promise<FetchResultV2> {
  const { factory, fromBlock } = chainConfig[options.chain];

  const logs = await options.getLogs({
    target: factory,
    eventAbi: CREATE_VAULT_EVENT,
    fromBlock,
    cacheInCloud: true,
  });
  const vaults: string[] = logs.map((log: any) => log.newVaultV2);

  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  if (vaults.length) {
    const dailyYield = await getERC4626VaultsYield({ options, vaults });
    dailyFees.add(dailyYield, METRIC.ASSETS_YIELDS);
    dailyRevenue.add(dailyYield.clone(PROTOCOL_FEE), "Yields To Protocol");
    dailySupplySideRevenue.add(dailyYield.clone(1 - PROTOCOL_FEE), "Yields To Self-Repay Loans");
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
}

const methodology = {
  Fees: "Yield generated by all Alchemix V3 ERC-4626 (MYT) vaults, measured from each vault's share-price (convertToAssets) growth over the day.",
  Revenue: "10% of generated yield collected by the Alchemix protocol.",
  ProtocolRevenue: "10% of generated yield collected by the Alchemix protocol.",
  SupplySideRevenue: "90% of generated yield that repays users' self-repaying loans.",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]: "Yield generated by all Alchemix V3 MYT vaults via share-price growth.",
  },
  Revenue: {
    "Yields To Protocol": "10% share of all yields collected by the protocol.",
  },
  SupplySideRevenue: {
    "Yields To Self-Repay Loans": "90% share of all yields repaying users' self-repaying loans.",
  },
};

const adapter: Adapter = {
  version: 2,
  fetch,
  adapter: chainConfig,
  methodology,
  breakdownMethodology,
  allowNegativeValue: true, // a vault's share price can dip on a loss day before the next yield accrual
};

export default adapter;
