import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { METRIC } from "../helpers/metrics";
import { addTokensReceived } from "../helpers/token";

const bUSDT = "0x3c594084dc7ab1864ac69dfd01ab77e8f65b83b7";
const bUSDC = "0x038dbe3d967bb8389190446dacdfe7b95b44f73d";
const bAUSD = "0xd211b17dfe8288d4fb0dd8eeff07a6c48fc679d5";
const USDT = "0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7";

const B_TOKENS = [bUSDT, bUSDC, bAUSD];

const PROTOCOL_FEE_WALLET = "0x223BBd67defAb792E66a76B7972C3cB17367d681";

const fetch = async (options: FetchOptions) => {
  const protocolYield = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const exitFees = options.createBalances();

  // 15% of generated yield is retained for ecosystem liquidity
  // and protocol sustainability.
  await addTokensReceived({
    options,
    targets: [PROTOCOL_FEE_WALLET],
    tokens: B_TOKENS,
    balances: protocolYield,
  });

  // 85% of generated yield is distributed to depositors.
  const dailySupplySideRevenue = protocolYield.clone(85 / 15);
  
  dailyProtocolRevenue.addBalances(
    protocolYield,
    METRIC.PROTOCOL_FEES
  );

  // 0.2% fee charged when b-Tokens are redeemed for underlying assets.
  await addTokensReceived({
    options,
    targets: [PROTOCOL_FEE_WALLET],
    tokens: [USDT],
    balances: exitFees,
  });


  dailyProtocolRevenue.addBalances(
    exitFees,
    METRIC.PROTOCOL_FEES
  );

  const dailyRevenue = dailyProtocolRevenue.clone();
  const dailyFees = dailyRevenue.clone();
  dailyFees.addBalances(
    dailySupplySideRevenue,
    METRIC.ASSETS_YIELDS
  );

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Total yield generated by AllBlue Stable, including the 15% protocol ecosystem share and 85% distributed to depositors, plus withdrawal fees.",
  Revenue: "15% of generated yield is retained by the protocol ecosystem fund, together with withdrawal fees.",
  ProtocolRevenue: "15% of generated yield is retained to strengthen ecosystem liquidity and support protocol sustainability, plus a 0.2% withdrawal fee.",
  SupplySideRevenue: "85% of generated yield is distributed to AllBlue Stable depositors.",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.PROTOCOL_FEES]: "15% of generated yield retained for ecosystem liquidity and protocol sustainability, plus 0.2% withdrawal fees",
    [METRIC.ASSETS_YIELDS]: "85% of generated yield distributed to AllBlue Stable depositors",
  },
  Revenue: {
    [METRIC.PROTOCOL_FEES]: "15% of generated yield retained for ecosystem liquidity and protocol sustainability, plus 0.2% withdrawal fees",
  },
  ProtocolRevenue: {
    [METRIC.PROTOCOL_FEES]: "15% of generated yield retained for ecosystem liquidity and protocol sustainability, plus 0.2% withdrawal fees",
  },
  SupplySideRevenue: {
    [METRIC.ASSETS_YIELDS]: "85% of generated yield distributed to AllBlue Stable depositors",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  fetch,
  chains: [CHAIN.AVAX],
  start: "2025-08-28",
  methodology,
  breakdownMethodology,
};

export default adapter;
