import ADDRESSES from '../helpers/coreAssets.json'
import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { METRIC } from "../helpers/metrics";

const ACCRUE_REWARDS_EVENT = 'event AccrueRewards(uint256 userRewardAmount, uint256 protocolRewardAmount)';
const address = ADDRESSES.avax.SAVAX;

const fetchFees = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  // sAVAX (0x2b2C81e08f1Af8835a78Bb2A90AE924ACE0eA4bE) emits AccrueRewards whenever validator
  // staking rewards are compounded into the contract:
  // - userRewardAmount: AVAX rewards added to totalPooledAvax for sAVAX holders (~90% yield) -> SupplySideRevenue
  // - protocolRewardAmount: AVAX protocol commission collected by BENQI (~10% fee) -> ProtocolRevenue
  // - dailyFees = userRewardAmount + protocolRewardAmount: Gross Protocol Revenue (100% of validator yield)
  const logs = await options.getLogs({
    target: address,
    eventAbi: ACCRUE_REWARDS_EVENT,
  });

  for (const log of logs) {
    const userReward = BigInt(log.userRewardAmount);
    const protocolReward = BigInt(log.protocolRewardAmount);

    dailySupplySideRevenue.addGasToken(userReward, METRIC.STAKING_REWARDS);
    dailyRevenue.addGasToken(protocolReward, METRIC.PROTOCOL_FEES);
    dailyFees.addGasToken(userReward + protocolReward, METRIC.STAKING_REWARDS);
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
    // Explicit 0: BENQI retains all staking commission in treasury; no revenue share / buyback to QI token holders
    dailyHoldersRevenue: 0,
  };
};

const methodology = {
  Fees: 'Total gross staking rewards generated by staked AVAX validators, tracked on-chain via AccrueRewards events.',
  Revenue: 'Protocol fee retained by BENQI from staking rewards (protocolRewardAmount).',
  ProtocolRevenue: 'All protocol revenue is retained by the BENQI treasury.',
  HoldersRevenue: 'No revenue share or token buybacks distributed to QI governance token holders.',
  SupplySideRevenue: 'Staking rewards compounded into the pool for sAVAX holders (userRewardAmount).',
}

const breakdownMethodology = {
  Fees: {
    [METRIC.STAKING_REWARDS]: 'Total AVAX staking rewards earned from validators for all AVAX staked through BENQI (100% of validator rewards)',
  },
  Revenue: {
    [METRIC.PROTOCOL_FEES]: 'Protocol fee retained by BENQI from staking rewards (10% of total rewards)',
  },
  SupplySideRevenue: {
    [METRIC.STAKING_REWARDS]: 'AVAX staking rewards distributed to sAVAX holders through appreciation of sAVAX/AVAX ratio (90% of total rewards)',
  }
}

const adapters: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  methodology,
  breakdownMethodology,
  adapter: {
    [CHAIN.AVAX]: {
      fetch: fetchFees,
      start: '2022-02-13', // sAVAX contract deployment on Avalanche C-Chain
    }
  }
}

export default adapters;
