import { Adapter, FetchOptions } from '../adapters/types'
import { CHAIN } from '../helpers/chains'
import { METRIC } from '../helpers/metrics'

interface BfUSDConfig {
  token: string
  vaults: string[]
  instantRedeemer: string
  start: string
}

const RATIO_PRECISION = 100_000_000n
const BFUSD_DECIMALS = 1_000_000

const bfUSDConfig: Record<string, BfUSDConfig> = {
  [CHAIN.ETHEREUM]: {
    token: '0xa3eB7A9e57FCa4e40b79E394eD5eB37fEd205A24',
    vaults: [
      '0xde5D4ab42251Ba9AF6f247CF07c9a4793fA6eD88',
      '0x4f85cBfDefBdb3fA96fCf1E38b0ee68dB9Ae438b',
    ],
    instantRedeemer: '0x0971cB672b4eF3E19284Aa64717aFb154A6fbeDF',
    start: '2025-11-03'
  },
}

async function fetch(options: FetchOptions) {
  const dailyFees = options.createBalances()
  const dailyUserFees = options.createBalances()
  const dailyRevenue = options.createBalances()
  const dailySupplySideRevenue = options.createBalances()
  const { token, vaults, instantRedeemer } = bfUSDConfig[options.chain]

  const crossChainFeeLogs = await options.getLogs({
    target: token,
    eventAbi: 'event CrossChainFeeCollected(address indexed user, uint256 amount, uint256 fee)',
  })

  for (const log of crossChainFeeLogs) {
    const fee = Number(log.fee) / BFUSD_DECIMALS
    dailyFees.addUSDValue(fee, METRIC.DEPOSIT_WITHDRAW_FEES)
    dailyUserFees.addUSDValue(fee, METRIC.DEPOSIT_WITHDRAW_FEES)
    dailyRevenue.addUSDValue(fee, METRIC.DEPOSIT_WITHDRAW_FEES)
  }

  const instantRedemptionLogs = await options.getLogs({
    target: instantRedeemer,
    eventAbi: 'event InstantRedemption(address indexed user, address indexed to, uint256 bfUSDAmount, uint256 underlyingAmount, uint256 feeAmount)',
  })

  for (const log of instantRedemptionLogs) {
    const fee = Number(log.feeAmount) / BFUSD_DECIMALS
    dailyFees.addUSDValue(fee, METRIC.MINT_REDEEM_FEES)
    dailyUserFees.addUSDValue(fee, METRIC.MINT_REDEEM_FEES)
    dailyRevenue.addUSDValue(fee, METRIC.MINT_REDEEM_FEES)
  }

  const vaultCrossChainFeeLogs = await options.getLogs({
    targets: vaults,
    eventAbi: 'event CrossChainFeeCollected(address indexed user, uint256 amount, uint256 fee)',
    flatten: false,
  })

  const [totalSupplies, ratioStarts, ratioEnds] = await Promise.all([
    options.fromApi.multiCall({ calls: vaults, abi: 'uint256:totalSupply' }),
    options.fromApi.multiCall({ calls: vaults, abi: 'uint256:currentRatio' }),
    options.toApi.multiCall({ calls: vaults, abi: 'uint256:currentRatio' }),
  ])

  vaultCrossChainFeeLogs.forEach((logs: any[], index: number) => {
    logs.forEach((log: any) => {
      const feeBfusd = (BigInt(log.fee) * BigInt(ratioEnds[index])) / RATIO_PRECISION
      const fee = Number(feeBfusd) / BFUSD_DECIMALS
      dailyFees.addUSDValue(fee, METRIC.DEPOSIT_WITHDRAW_FEES)
      dailyUserFees.addUSDValue(fee, METRIC.DEPOSIT_WITHDRAW_FEES)
      dailyRevenue.addUSDValue(fee, METRIC.DEPOSIT_WITHDRAW_FEES)
    })
  })

  vaults.forEach((_, index) => {
    const strategyYield = (BigInt(totalSupplies[index]) * (BigInt(ratioEnds[index]) - BigInt(ratioStarts[index]))) / RATIO_PRECISION
    dailyFees.addUSDValue(Number(strategyYield) / BFUSD_DECIMALS, METRIC.ASSETS_YIELDS)
    dailySupplySideRevenue.addUSDValue(Number(strategyYield) / BFUSD_DECIMALS, METRIC.ASSETS_YIELDS)
  })

  return {
    dailyFees,
    dailyUserFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  }
}

const adapter: Adapter = {
  version: 2,
  pullHourly: true,
  allowNegativeValue: true,
  fetch,
  chains: [CHAIN.ETHEREUM],
  start: '2025-11-02',
  methodology: {
    Fees: 'Instant redemption and cross-chain transfer fees from bfUSD paid by users, plus real yield accrued by Horizon and Pulsar vault shares.',
    UserFees: 'Instant redemption and cross-chain transfer fees from bfUSD paid by users.',
    Revenue: 'Instant redemption and cross-chain transfer fees collected by BitFi.',
    ProtocolRevenue: 'Instant redemption and cross-chain transfer fees collected by BitFi.',
    SupplySideRevenue: 'Real yield accrued to hbfUSD and pbfUSD holders through BitFi currentRatio appreciation.',
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.DEPOSIT_WITHDRAW_FEES]: 'Cross-chain transfer fees collected by bfUSD and staked bfUSD contracts.',
      [METRIC.MINT_REDEEM_FEES]: 'Instant redemption fees collected by the bfUSD instant redeemer.',
      [METRIC.ASSETS_YIELDS]: 'Yield generated by Horizon and Pulsar strategies and accrued to hbfUSD/pbfUSD shares through BitFi currentRatio appreciation.',
    },
    UserFees: {
      [METRIC.DEPOSIT_WITHDRAW_FEES]: 'Cross-chain transfer fees paid directly by users.',
      [METRIC.MINT_REDEEM_FEES]: 'Instant redemption fees paid directly by users.',
    },
    Revenue: {
      [METRIC.DEPOSIT_WITHDRAW_FEES]: 'Cross-chain transfer fees collected by BitFi.',
      [METRIC.MINT_REDEEM_FEES]: 'Instant redemption fees collected by BitFi.',
    },
    ProtocolRevenue: {
      [METRIC.DEPOSIT_WITHDRAW_FEES]: 'Cross-chain transfer fees collected by BitFi.',
      [METRIC.MINT_REDEEM_FEES]: 'Instant redemption fees collected by BitFi.',
    },
    SupplySideRevenue: {
      [METRIC.ASSETS_YIELDS]: 'Net real yield accrued to hbfUSD and pbfUSD holders through BitFi currentRatio appreciation.',
    },
  },
}

export default adapter
