import { SimpleAdapter, FetchOptions } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { httpGet } from "../utils/fetchURL";

const fetch: any = async (options: FetchOptions) => {
    try {
        const data = await httpGet(
            `https://api.bitway.com/bitway-earn-api/defillama/fees-revenue?startTimestamp=${options.startTimestamp}&endTimestamp=${options.endTimestamp}`
        );
    
        if (data?.fees === undefined || data?.revenue === undefined) {
            console.error(`Bitway Earn API returned unexpected response: ${JSON.stringify(data)}`);
            return { dailyFees: 0, dailyRevenue: 0 };
        }

        return {
            dailyFees: Number(data.fees),
            dailyRevenue: Number(data.revenue),
        };
    } catch (e) {
        console.error(`Bitway Earn API request failed: ${e}`);
        return { dailyFees: 0, dailyRevenue: 0 };
    }
};

const methodology = {
    Fees: "Total fees, including yield generated by vault strategies and flash unstake penalties.",
    Revenue: "Total revenue earned by the protocol, excluding yield distributed to depositors."
};

const adapter: SimpleAdapter = {
    version: 2,
    pullHourly: false,
    fetch,
    chains: [CHAIN.BSC],
    start: "2026-01-01",
    methodology,
    allowNegativeValue: true,
};

export default adapter;
