import { FetchOptions, FetchV2, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import CoreAddresses from "../helpers/coreAssets.json";
import { addTokensReceived } from "../helpers/token";

// ClawdStrategy is an AI-powered Bitcoin income protocol on Base.
// AI trading agents generate revenue, which the protocol distributes
// weekly as cbBTC (Coinbase Bitcoin on Base) directly to STRI holders
// pro-rata to their balance. Distributions are on-chain ERC20 transfers
// from the Treasury wallet to holders.
const TREASURY = "0x0A5703883BB4983886212B7b32edCb526e68E847";

const fetch: FetchV2 = async (options: FetchOptions) => {
  // All cbBTC outflows from the Treasury are weekly holder distributions.
  // The Treasury holds capital deposited by minters until it is deployed
  // by AI agents; the only cbBTC that leaves the Treasury is paid out to
  // STRI holders.
  const dailyHoldersRevenue = await addTokensReceived({
    options,
    tokens: [CoreAddresses.base.cbBTC],
    fromAdddesses: [TREASURY],
  });

  return {
    dailyFees: dailyHoldersRevenue,
    dailyRevenue: dailyHoldersRevenue,
    dailyHoldersRevenue,
    dailyProtocolRevenue: 0,
  };
};

const methodology = {
    Fees: "Total cbBTC distributed by the ClawdStrategy Treasury to STRI holders. Represents the gross income generated by the AI trading agents that is paid out to the protocol's tokenholders.",
    Revenue: "Same as Fees. ClawdStrategy does not charge a supply-side fee — 100% of agent-generated income is paid out from the Treasury, so dailyRevenue equals dailyFees.",
    HoldersRevenue: "All cbBTC income generated by the AI trading agents is sent from the Treasury to STRI holders pro-rata. Pre-max-supply (500,000 STRI), 100% of distributions go to holders. After the supply cap is reached, the protocol begins retaining 5% for ongoing operations.",
    ProtocolRevenue: "0 today. The protocol takes 0% until the 500,000 STRI max supply is fully minted; afterwards, 5% of distributions are allocated to protocol operations.",
  };
  
  const breakdownMethodology = {
    Fees: {
      "Treasury Distributions": "cbBTC sent from Treasury to STRI holders",
    },
    Revenue: {
      "Treasury Distributions": "cbBTC sent from Treasury to STRI holders",
    },
    HoldersRevenue: {
      "Treasury Distributions": "cbBTC sent from Treasury to STRI holders",
    },
  };

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  fetch,
  chains: [CHAIN.BASE],
  start: "2026-03-01",
  methodology,
  breakdownMethodology,
};

export default adapter;
