import { Adapter, FetchOptions, FetchResultFees } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import fetchURL from "../utils/fetchURL";

interface Pool {
    poolName: string;
    date: string;
    totalRevenue: string;
    totalProtocolFee: string;
}

const urlRevStats = "https://api.prod.flash.trade/protocol-fees/daily";

const calculateProtocolRevenue = (stats: Pool[]) => {
    const protocolRevenue = stats.reduce((sum, item) => sum + parseFloat(item.totalProtocolFee) / 1e6, 0);
    return protocolRevenue;
};

const calculateteHolderRevenue = (stats: Pool[]) => {
    const holderRevenue = stats.reduce((sum, item) => sum + parseFloat(item.totalRevenue) / 1e6, 0);
    return holderRevenue;
};

const pools = [
    "Crypto.1",
    "Virtual.1",
    "Governance.1",
    "Community.1",
    "Community.2",
    "Community.3",
    "Trump.1",
]

const fetch = async (_a: any, _b: any, options: FetchOptions): Promise<FetchResultFees> => {
    const timestamp = options.startOfDay;
    const targetDate = new Date(timestamp * 1000).toISOString().split('T')[0];

    let dailyFees = 0;
    for (const pool of pools) {
        const url = `https://api.prod.flash.trade/pnl-info/cumulative-pnl-per-day?poolName=${pool}&startDate=2023-01-01%2000:00:00&endDate=${targetDate}%2023:59:59`;
        const res = await fetchURL(url);
        dailyFees += (res[targetDate]?.totalFees / 1e6) || 0;
    }

    const dailyRevStatsResponse = await fetchURL(urlRevStats);
    const dailyStats: Pool[] = dailyRevStatsResponse;

    const todayStats = dailyStats.filter(item => {
        const itemDate = new Date(item.date).toISOString().split('T')[0];
        return itemDate === targetDate;
    });

    // Token stakers revenue is 0 before 2025-06-15
    const dailyHoldersRevenue = timestamp >= 1750291200 ? calculateteHolderRevenue(todayStats): 0; // 50% holder revenue share
    const dailyProtocolRevenue = calculateProtocolRevenue(todayStats);
    const dailyRevenue = ((dailyProtocolRevenue) + (dailyHoldersRevenue))
    const dailySupplySideRevenue = dailyFees - dailyRevenue;

    return {
        dailyFees,
        dailyUserFees: dailyFees,
        dailyRevenue,
        dailyProtocolRevenue,
        dailyHoldersRevenue,
        dailySupplySideRevenue,
    };
};

const methodology = {
    Fees: 'All fees generated by the pools.',
    Revenue: 'Sum of protocol revenue and holder revenue.',
    ProtocolRevenue: '30% of all the fees accrued excluding Community pool before 2025-06-15, 15% after 2025-06-15.',
    HolderRevenue: '50% of revenue goes to token stakers after 2025-06-15.',
    SupplySideRevenue: 'Fees paid to LP pools.',
}

const adapter: Adapter = {
    version: 1,
    adapter: {
        [CHAIN.SOLANA]: {
            fetch,
            start: '2023-12-29',
            meta: { methodology },
        },
    },
};

export default adapter;