import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";

// Contract addresses
// https://github.com/kleros/kleros-v2/tree/dev/contracts/deployments
// https://github.com/kleros/kleros/blob/master/contracts/kleros/KlerosLiquid.sol
const contracts = {
  [CHAIN.ARBITRUM]: {
    klerosCore: "0x991d2df165670b9cac3B022f4B68D65b664222ea",
    disputeKit: "0x70B464be85A547144C72485eBa2577E5D3A45421",
  },
  [CHAIN.ETHEREUM]: {
    klerosLiquid: "0x988b3A538b618C7A603e1c11Ab82Cd16dbE28069",
  },
  [CHAIN.XDAI]: {
    xKlerosLiquid: "0x9C1dA9A04925bDfDedf0f6421bC7EEa8305F9002",
  },
};

// Events
// https://github.com/kleros/kleros-v2/blob/dev/contracts/src/arbitration/KlerosCore.sol
// https://github.com/kleros/kleros-v2/blob/dev/contracts/src/arbitration/dispute-kits/DisputeKitClassic.sol
// https://github.com/kleros/kleros/blob/master/contracts/kleros/KlerosLiquid.sol
const events = {
  // V2 (Arbitrum): emitted when juror rewards/penalties are executed after dispute resolution
  tokenAndETHShiftV2:
    "event TokenAndETHShift(address indexed _account, uint256 indexed _disputeID, uint256 indexed _roundID, uint256 _degreeOfCoherency, int256 _pnkAmount, int256 _feeAmount, address _feeToken)",
  // V2: appeal fee deposits by funders
  contribution:
    "event Contribution(uint256 indexed _coreDisputeID, uint256 indexed _coreRoundID, uint256 _choice, address indexed _contributor, uint256 _amount)",
  // V2: appeal fee refunds after round resolves
  withdrawal:
    "event Withdrawal(uint256 indexed _coreDisputeID, uint256 _choice, address indexed _contributor, uint256 _amount)",
  // V1 (Ethereum, Gnosis): emitted when juror wins or loses tokens and ETH from a dispute
  tokenAndETHShiftV1:
    "event TokenAndETHShift(address indexed _address, uint256 indexed _disputeID, int256 _tokenAmount, int256 _ETHAmount)",
};

const fetchArbitrum = async ({ createBalances, getLogs }: FetchOptions) => {
  const dailyFees = createBalances();
  const dailySupplySideRevenue = createBalances();
  const { klerosCore, disputeKit } = contracts[CHAIN.ARBITRUM];

  // Juror fee rewards from dispute resolution
  const shiftLogs = await getLogs({
    target: klerosCore,
    eventAbi: events.tokenAndETHShiftV2,
  });

  for (const log of shiftLogs) {
    const feeAmount = Number(log._feeAmount);
    if (feeAmount > 0) {
      const feeToken = log._feeToken;
      if (feeToken === "0x0000000000000000000000000000000000000000") {
        dailyFees.addGasToken(feeAmount);
        dailySupplySideRevenue.addGasToken(feeAmount);
      } else {
        dailyFees.add(feeToken, feeAmount);
        dailySupplySideRevenue.add(feeToken, feeAmount);
      }
    }
  }

  // Net appeal contributions
  const [contributionLogs, withdrawalLogs] = await Promise.all([
    getLogs({ target: disputeKit, eventAbi: events.contribution }),
    getLogs({ target: disputeKit, eventAbi: events.withdrawal }),
  ]);

  for (const log of contributionLogs) {
    dailyFees.addGasToken(log._amount);
  }

  for (const log of withdrawalLogs) {
    dailyFees.addGasToken(-log._amount);
  }

  return {
    dailyFees,
    dailyRevenue: dailyFees,
    dailySupplySideRevenue,
  };
};

const fetchEthereum = async ({ createBalances, getLogs }: FetchOptions) => {
  const dailyFees = createBalances();
  const dailySupplySideRevenue = createBalances();
  const { klerosLiquid } = contracts[CHAIN.ETHEREUM];

  // Juror ETH rewards from dispute resolution
  const shiftLogs = await getLogs({
    target: klerosLiquid,
    eventAbi: events.tokenAndETHShiftV1,
  });

  for (const log of shiftLogs) {
    const ethAmount = Number(log._ETHAmount);
    if (ethAmount > 0) {
      dailyFees.addGasToken(ethAmount);
      dailySupplySideRevenue.addGasToken(ethAmount);
    }
  }

  return {
    dailyFees,
    dailyRevenue: dailyFees,
    dailySupplySideRevenue,
  };
};

const fetchGnosis = async ({ createBalances, getLogs }: FetchOptions) => {
  const dailyFees = createBalances();
  const dailySupplySideRevenue = createBalances();
  const { xKlerosLiquid } = contracts[CHAIN.XDAI];

  // Juror xDAI rewards from dispute resolution
  const shiftLogs = await getLogs({
    target: xKlerosLiquid,
    eventAbi: events.tokenAndETHShiftV1,
  });

  for (const log of shiftLogs) {
    const ethAmount = Number(log._ETHAmount);
    if (ethAmount > 0) {
      dailyFees.addGasToken(ethAmount);
      dailySupplySideRevenue.addGasToken(ethAmount);
    }
  }

  return {
    dailyFees,
    dailyRevenue: dailyFees,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Arbitration fees paid by dispute creators distributed to jurors, plus net appeal contributions.",
  Revenue: "All arbitration fees generated by the protocol.",
  SupplySideRevenue: "Fees distributed as rewards to coherent jurors who vote correctly.",
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.ARBITRUM]: {
      fetch: fetchArbitrum,
      start: "2024-02-01",
    },
    [CHAIN.ETHEREUM]: {
      fetch: fetchEthereum,
      start: "2018-11-01",
    },
    [CHAIN.XDAI]: {
      fetch: fetchGnosis,
      start: "2020-03-01",
    },
  },
  methodology,
};

export default adapter;
