import { Adapter, FetchOptions, FetchResultV2 } from "../adapters/types"
import { CHAIN } from "../helpers/chains"
import { METRIC } from "../helpers/metrics"

interface IBoringVault {
  vault: string;
  accountant: string;
}

const vaults: IBoringVault[] = [
  {
    vault: '0x7Dee0120739b7ec048B469939EFB178ADbbB19B2',
    accountant: '0x4Bb6C416a00561ad6657110b76552c42d55Ff1d6',
  },
]

const abis = {
  decimals: 'uint8:decimals',
  totalSupply: 'uint256:totalSupply',
  base: 'address:base',
  exchangeRateUpdated: 'event ExchangeRateUpdated(uint96 oldRate, uint96 newRate, uint64 currentTime)',
  accountantState: 'function accountantState() view returns(address,uint96,uint128,uint128,uint96,uint16,uint16,uint64,bool,uint24,uint16,uint16)',
}

const FeeRateBase = 1e4

async function fetch(options: FetchOptions): Promise<FetchResultV2> {
  const dailyFees = options.createBalances()
  const dailySupplySideRevenue = options.createBalances()
  const dailyProtocolRevenue = options.createBalances()

  const [decimals, tokens, accountantStates, totalSupplies] = await Promise.all([
    options.api.multiCall({ abi: abis.decimals, calls: vaults.map(vault => vault.vault) }),
    options.api.multiCall({ abi: abis.base, calls: vaults.map(vault => vault.accountant) }),
    options.api.multiCall({ abi: abis.accountantState, calls: vaults.map(vault => vault.accountant) }),
    options.api.multiCall({ abi: abis.totalSupply, calls: vaults.map(vault => vault.vault) }),
  ])

  for (const [index, vault] of vaults.entries()) {
    const decimal = decimals[index]
    const token = tokens[index]
    const accountantState = accountantStates[index]
    const totalSupply = totalSupplies[index]

    const rateBase = Number(10 ** Number(decimal))
    const logs = await options.getLogs({
      eventAbi: abis.exchangeRateUpdated,
      entireLog: true,
      target: vault.accountant,
      parseLog: true,
    })

    const events = logs.map((log: any) => {
      const decoded: any = log.parsedLog.args
      return {
        blockNumber: Number(log.blockNumber),
        oldRate: decoded.oldRate,
        newRate: decoded.newRate,
      }
    })

    for (const event of events) {
      const growthRate = Number(event.newRate - event.oldRate)
      const exchangeRate = Number(accountantState[4])
      const performanceFeeRate = Number(accountantState[11]) / FeeRateBase

      const totalDeposited = Number(totalSupply) * exchangeRate / rateBase
      const supplySideYield = totalDeposited * growthRate / rateBase
      const totalYield = supplySideYield / (1 - performanceFeeRate)
      const protocolFee = totalYield - supplySideYield

      dailyFees.add(token, totalYield, METRIC.ASSETS_YIELDS)
      dailySupplySideRevenue.add(token, supplySideYield, METRIC.ASSETS_YIELDS)
      dailyProtocolRevenue.add(token, protocolFee, METRIC.PERFORMANCE_FEES)
    }

    // Platform fees (annual fee on total assets)
    const exchangeRate = Number(accountantState[4])
    const platformFeeRate = Number(accountantState[10])
    const totalDeposited = Number(totalSupply) * exchangeRate / rateBase

    const yearInSecs = 365 * 24 * 60 * 60
    const timespan = options.fromTimestamp && options.toTimestamp
      ? Number(options.toTimestamp) - Number(options.fromTimestamp)
      : 3600
    const platformFee = totalDeposited * (platformFeeRate / FeeRateBase) * timespan / yearInSecs

    dailyFees.add(token, platformFee, METRIC.MANAGEMENT_FEES)
    dailyProtocolRevenue.add(token, platformFee, METRIC.MANAGEMENT_FEES)
  }

  return {
    dailyFees,
    dailyRevenue: dailyProtocolRevenue,
    dailySupplySideRevenue,
    dailyProtocolRevenue,
  }
}

const methodology = {
  Fees: 'Total yield generated by the Kraken Bitcoin Vault from overcollateralized lending strategies managed by Veda/Sentora, derived from exchange rate appreciation and platform management fees.',
  Revenue: 'Performance fees taken as a percentage of yield plus annual platform management fees on total vault assets.',
  ProtocolRevenue: 'Performance fees taken as a percentage of yield plus annual platform management fees on total vault assets.',
  SupplySideRevenue: 'Yield distributed to vault depositors after performance and management fees are deducted.',
}

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]: 'Gross yield from vault exchange rate appreciation, including performance fees.',
    [METRIC.MANAGEMENT_FEES]: 'Annual management fee charged on total vault assets.',
  },
  Revenue: {
    [METRIC.PERFORMANCE_FEES]: 'Performance fee taken as a percentage of yield on exchange rate increases.',
    [METRIC.MANAGEMENT_FEES]: 'Annual management fee charged on total vault assets.',
  },
  ProtocolRevenue: {
    [METRIC.PERFORMANCE_FEES]: 'Performance fee taken as a percentage of yield on exchange rate increases.',
    [METRIC.MANAGEMENT_FEES]: 'Annual management fee charged on total vault assets.',
  },
  SupplySideRevenue: {
    [METRIC.ASSETS_YIELDS]: 'Yield distributed to depositors after performance and management fees are deducted.',
  },
}

const adapter: Adapter = {
  version: 2,
  methodology,
  breakdownMethodology,
  pullHourly: true,
  fetch,
  chains: [CHAIN.INK],
  start: '2026-02-26',
  allowNegativeValue: true,
}

export default adapter
