import { postURL } from "../utils/fetchURL"
import { FetchResultV2, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { FetchOptions } from "../adapters/types";

const url: any = {
  [CHAIN.SUI]: `https://app.sentio.xyz/api/v1/insights/mmt-finance/clmm-dashboard/query`
}

const options = {
  headers: {
    'Content-Type': 'application/json',
    'api-key': 'sd0mYLVwi9gZx8l0FHryM5pQY5VEbU8RX',
  },
};

const methodology = {
  Fees: 'Swap fees generated by the swap transactions on Momentum.',
  ProtocolRevenue: 'Protocol fees charged from the swap fees.',
};

const buildQueryPayload = (metricName: string, start: number, end: number) => ({
  timeRange: {
    start: start.toString(),
    end: end.toString(),
    step: 3600,
  },
  queries: [
    {
      metricsQuery: {
        query: metricName,
        aggregate: { op: 'SUM' },
      },
      dataSource: 'METRICS',
    },
  ],
  cachePolicy: {
    noCache: true,
  },
});

const extractMetricDelta = (values?: { value: string }[]): number => {
  if (!values || values.length < 2) return 0;
  const begin = Number(values[0].value);
  const end = Number(values[values.length - 1].value);
  return end - begin;
};

const fetch = async (_t: any, _b: any, { startOfDay, chain }: FetchOptions): Promise<FetchResultV2> => {
  const [feeRes, protocolFeeRes] = await Promise.all([
    postURL(url[chain], buildQueryPayload('FeeUsdCounter', startOfDay, startOfDay + 86400), 3, options),
    postURL(url[chain], buildQueryPayload('ProtocolFeeUsdCounter', startOfDay, startOfDay + 86400), 3, options),
  ]);
  const feeValues = feeRes?.results?.[0]?.matrix?.samples?.[0]?.values;
  const protocolFeeValues = protocolFeeRes?.results?.[0]?.matrix?.samples?.[0]?.values;

  const dailyFees = extractMetricDelta(feeValues);
  const protocolFees = extractMetricDelta(protocolFeeValues);

  return {
    dailyFees,
    dailyRevenue: protocolFees,
    dailyProtocolRevenue: protocolFees,
  };
};

const adapter: SimpleAdapter = {
  version: 1,
  adapter: {
    [CHAIN.SUI]: {
      fetch,
      start: '2025-03-08',
    }
  },
  methodology,
};

export default adapter;