import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import coreAssets from "../helpers/coreAssets.json";

const USDC = coreAssets.hyperliquid.USDC;

// https://hyperevmscan.io/address/0x5586c2c8223C73Ec0B41D6352748e6c173372E11
const MONETRIX_VAULT = '0x5586c2c8223C73Ec0B41D6352748e6c173372E11';
// InstantRedeem — USDC
const INSTANT_REDEEM = '0xF4F03Bbfb6D314fD1D1E22012905d778f5B0adD2';
// InstantUnstake — USDM (6 decimals, $1-pegged, booked as USDC)
const INSTANT_UNSTAKE = '0x7592b9Fc42E000783d491739c77CcB86F19c4132';

const YIELD_DISTRIBUTED_ABI = 'event YieldDistributed(uint256 totalYield, uint256 userShare, uint256 insuranceShare, uint256 foundationShare)';
const INSTANT_EXITED_ABI = 'event InstantExited(address indexed user, uint256 inputAmount, uint256 payout, uint256 fee)';

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyUserFees = options.createBalances();

  // Yield earned by the USDM vault's delta-neutral positions on Hyperliquid Core
  // (funding payments, HLP and borrow-lend yield), measured at distribution.
  const yieldLogs = await options.getLogs({ targets: [MONETRIX_VAULT], eventAbi: YIELD_DISTRIBUTED_ABI });
  yieldLogs.forEach((log: any) => {
    dailyFees.add(USDC, log.totalYield, 'Yield');
    dailySupplySideRevenue.add(USDC, log.userShare, 'Yield To sUSDM Stakers');
    dailySupplySideRevenue.add(USDC, log.insuranceShare, 'Yield To Insurance Fund');
    dailyRevenue.add(USDC, log.foundationShare, 'Yield To Foundation');
    dailyProtocolRevenue.add(USDC, log.foundationShare, 'Yield To Foundation');
  });

  // Both USDM instant-exit paths charge USDC-denominated fees.
  const exitLogs = await options.getLogs({
    targets: [INSTANT_REDEEM, INSTANT_UNSTAKE],
    eventAbi: INSTANT_EXITED_ABI,
  });
  exitLogs.forEach((log: any) => {
    dailyFees.add(USDC, log.fee, 'Instant Exit Fees');
    dailyRevenue.add(USDC, log.fee, 'Instant Exit Fees');
    dailyProtocolRevenue.add(USDC, log.fee, 'Instant Exit Fees');
    dailyUserFees.add(USDC, log.fee, 'Instant Exit Fees');
  });

  return { dailyFees, dailyRevenue, dailyProtocolRevenue, dailySupplySideRevenue, dailyUserFees };
};

const adapter: SimpleAdapter = {
  version: 2,
  chains: [CHAIN.HYPERLIQUID],
  fetch,
  start: '2026-06-10',
  pullHourly: true,
  methodology: {
    Fees: "Yield generated by the USDM vault's delta-neutral positions on Hyperliquid Core (funding payments, HLP and borrow-lend yield), measured at distribution via the MonetrixVault's YieldDistributed event, plus instant redeem/unstake fees paid by users.",
    Revenue: "Share of distributed yield routed to the foundation, plus instant redeem/unstake fees. The insurance-fund share is a protocol reserve that backstops the system and is booked as supply-side revenue rather than protocol revenue.",
    ProtocolRevenue: "Revenue kept by the protocol. Monetrix has no token holder distribution, so protocol revenue equals total revenue (foundation share plus instant redeem/unstake fees; the insurance-fund reserve is booked as supply-side, not revenue).",
    SupplySideRevenue: "Share of distributed yield paid to sUSDM stakers, plus the insurance-fund reserve that backstops the system for stakers (cost of system security).",
    UserFees: "Instant redeem/unstake fees paid by users for skipping the delayed exit flow.",
  },
  breakdownMethodology: {
    Fees: {
      'Yield': "Total yield distributed by the USDM vault, measured via the MonetrixVault's YieldDistributed event.",
      'Instant Exit Fees': "Fees paid by users who take the instant redeem/unstake flow to skip the delayed exit.",
    },
    Revenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    ProtocolRevenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    SupplySideRevenue: {
      'Yield To sUSDM Stakers': "Share of distributed yield paid to sUSDM stakers.",
      'Yield To Insurance Fund': "Share of distributed yield routed to the insurance-fund reserve that backstops the system for stakers (cost of system security).",
    },
    UserFees: {
      'Instant Exit Fees': "Instant redeem/unstake fees paid by users.",
    },
  },
};

export default adapter;
