import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import coreAssets from "../helpers/coreAssets.json";

const USDC = coreAssets.hyperliquid.USDC;
const WHYPE = coreAssets.hyperliquid.WHYPE;

const YIELD_DISTRIBUTED_ABI = 'event YieldDistributed(uint256 totalYield, uint256 userShare, uint256 insuranceShare, uint256 foundationShare)';
const INSTANT_EXITED_ABI = 'event InstantExited(address indexed user, uint256 inputAmount, uint256 payout, uint256 fee)';

const PRODUCTS = [
  {
    token: USDC,
    vault: '0x5586c2c8223C73Ec0B41D6352748e6c173372E11',
    instantExits: [
      '0xF4F03Bbfb6D314fD1D1E22012905d778f5B0adD2', // InstantRedeem — USDC
      '0x7592b9Fc42E000783d491739c77CcB86F19c4132', // InstantUnstake — USDM (6 decimals, $1-pegged, booked as USDC)
    ],
    stakerBreakdown: 'Yield To sUSDM Stakers',
  },
  {
    token: WHYPE,
    vault: '0x270A9d32F893A5D3ff1878185010894dd890593D',
    instantExits: [
      '0x80e9b092395fda5d4391aE03ACa6Afcf2bAe3051',
      '0x930Ec4B9066fCDa704501CFEf286e6f095EF2450',
    ],
    stakerBreakdown: 'Yield To smxHYPE Stakers',
  },
];

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyUserFees = options.createBalances();

  const vaults = PRODUCTS.map((p) => p.vault);
  const instantExits = PRODUCTS.flatMap((p) => p.instantExits.map((address) => ({ address, product: p })));

  const [yieldLogsByVault, exitLogsByTarget] = await Promise.all([
    options.getLogs({ targets: vaults, eventAbi: YIELD_DISTRIBUTED_ABI, flatten: false }),
    options.getLogs({ targets: instantExits.map((e) => e.address), eventAbi: INSTANT_EXITED_ABI, flatten: false }),
  ]);

  PRODUCTS.forEach(({ token, stakerBreakdown }, i) => {
    for (const log of yieldLogsByVault[i] ?? []) {
      dailyFees.add(token, log.totalYield, 'Yield');
      dailySupplySideRevenue.add(token, log.userShare, stakerBreakdown);
      dailySupplySideRevenue.add(token, log.insuranceShare, 'Yield To Insurance Fund');
      dailyRevenue.add(token, log.foundationShare, 'Yield To Foundation');
      dailyProtocolRevenue.add(token, log.foundationShare, 'Yield To Foundation');
    }
  });

  instantExits.forEach(({ product }, i) => {
    for (const log of exitLogsByTarget[i] ?? []) {
      dailyFees.add(product.token, log.fee, 'Instant Exit Fees');
      dailyRevenue.add(product.token, log.fee, 'Instant Exit Fees');
      dailyProtocolRevenue.add(product.token, log.fee, 'Instant Exit Fees');
      dailyUserFees.add(product.token, log.fee, 'Instant Exit Fees');
    }
  });

  return { dailyFees, dailyRevenue, dailyProtocolRevenue, dailySupplySideRevenue, dailyUserFees };
};

const adapter: SimpleAdapter = {
  version: 2,
  chains: [CHAIN.HYPERLIQUID],
  fetch,
  start: '2026-06-10',
  pullHourly: true,
  methodology: {
    Fees: "Yield generated by Monetrix vaults on Hyperliquid Core — sUSDM's delta-neutral positions (funding payments, HLP and borrow-lend yield) and mxHYPE's borrowed-USDC overlay (converted to HYPE before distribution) — measured at distribution via each vault's YieldDistributed event, plus instant redeem/unstake fees paid by users.",
    Revenue: "Share of distributed yield routed to the foundation, plus instant redeem/unstake fees. The insurance-fund share is a protocol reserve that backstops the system and is booked as supply-side revenue rather than protocol revenue.",
    ProtocolRevenue: "Revenue kept by the protocol. Monetrix has no token holder distribution, so protocol revenue equals total revenue (foundation share plus instant redeem/unstake fees; the insurance-fund reserve is booked as supply-side, not revenue).",
    SupplySideRevenue: "Share of distributed yield paid to sUSDM and smxHYPE stakers, plus the insurance-fund reserve that backstops the system for stakers (cost of system security).",
    UserFees: "Instant redeem/unstake fees paid by users for skipping the delayed exit flow.",
  },
  breakdownMethodology: {
    Fees: {
      'Yield': "Total yield distributed by the sUSDM and mxHYPE vaults, measured via each vault's YieldDistributed event.",
      'Instant Exit Fees': "Fees paid by users who take the instant redeem/unstake flow to skip the delayed exit.",
    },
    Revenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    ProtocolRevenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    SupplySideRevenue: {
      'Yield To sUSDM Stakers': "Share of distributed yield paid to sUSDM stakers.",
      'Yield To smxHYPE Stakers': "Share of distributed yield paid to smxHYPE stakers.",
      'Yield To Insurance Fund': "Share of distributed yield routed to the insurance-fund reserve that backstops the system for stakers.",
    },
    UserFees: {
      'Instant Exit Fees': "Instant redeem/unstake fees paid by users.",
    },
  },
};

export default adapter;
