import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import coreAssets from "../helpers/coreAssets.json";

const WHYPE = coreAssets.hyperliquid.WHYPE;

// Production HyperEVM deployments:
// https://hyperevmscan.io/address/0x270A9d32F893A5D3ff1878185010894dd890593D
const HYPE_VAULT = '0x270A9d32F893A5D3ff1878185010894dd890593D';
// https://hyperevmscan.io/address/0x80e9b092395fda5d4391aE03ACa6Afcf2bAe3051
const HYPE_INSTANT_REDEEM = '0x80e9b092395fda5d4391aE03ACa6Afcf2bAe3051';
// https://hyperevmscan.io/address/0x930Ec4B9066fCDa704501CFEf286e6f095EF2450
const HYPE_INSTANT_UNSTAKE = '0x930Ec4B9066fCDa704501CFEf286e6f095EF2450';

const YIELD_DISTRIBUTED_ABI = 'event YieldDistributed(uint256 totalYield, uint256 userShare, uint256 insuranceShare, uint256 foundationShare)';
const INSTANT_EXITED_ABI = 'event InstantExited(address indexed user, uint256 inputAmount, uint256 payout, uint256 fee)';

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyUserFees = options.createBalances();

  // Yield generated by mxHYPE's borrowed-USDC overlay on Hyperliquid Core is
  // converted into HYPE before the HypeVault distributes it.
  const yieldLogs = await options.getLogs({ targets: [HYPE_VAULT], eventAbi: YIELD_DISTRIBUTED_ABI });
  yieldLogs.forEach((log: any) => {
    dailyFees.add(WHYPE, log.totalYield, 'Yield');
    dailySupplySideRevenue.add(WHYPE, log.userShare, 'Yield To smxHYPE Stakers');
    dailySupplySideRevenue.add(WHYPE, log.insuranceShare, 'Yield To Insurance Fund');
    dailyRevenue.add(WHYPE, log.foundationShare, 'Yield To Foundation');
    dailyProtocolRevenue.add(WHYPE, log.foundationShare, 'Yield To Foundation');
  });

  // Both mxHYPE instant-exit paths charge native HYPE-denominated fees.
  const exitLogs = await options.getLogs({
    targets: [HYPE_INSTANT_REDEEM, HYPE_INSTANT_UNSTAKE],
    eventAbi: INSTANT_EXITED_ABI,
  });
  exitLogs.forEach((log: any) => {
    dailyFees.add(WHYPE, log.fee, 'Instant Exit Fees');
    dailyRevenue.add(WHYPE, log.fee, 'Instant Exit Fees');
    dailyProtocolRevenue.add(WHYPE, log.fee, 'Instant Exit Fees');
    dailyUserFees.add(WHYPE, log.fee, 'Instant Exit Fees');
  });

  return { dailyFees, dailyRevenue, dailyProtocolRevenue, dailySupplySideRevenue, dailyUserFees };
};

const adapter: SimpleAdapter = {
  version: 2,
  chains: [CHAIN.HYPERLIQUID],
  fetch,
  start: '2026-08-17',
  pullHourly: true,
  methodology: {
    Fees: "Yield generated by mxHYPE's borrowed-USDC overlay on Hyperliquid Core, measured in HYPE at distribution via the HypeVault's YieldDistributed event, plus instant redeem/unstake fees paid by users.",
    Revenue: "Share of distributed yield routed to the foundation, plus instant redeem/unstake fees. The insurance-fund share is booked as supply-side revenue because it backstops the system.",
    ProtocolRevenue: "Revenue kept by the protocol. Monetrix has no token holder distribution, so protocol revenue equals the foundation share plus instant redeem/unstake fees.",
    SupplySideRevenue: "Share of distributed yield paid to smxHYPE stakers, plus the insurance-fund reserve that backstops the system.",
    UserFees: "Instant redeem/unstake fees paid by users for skipping the delayed exit flow.",
  },
  breakdownMethodology: {
    Fees: {
      'Yield': "Total HYPE yield distributed by the HypeVault.",
      'Instant Exit Fees': "Fees paid by users who take the instant redeem/unstake flow.",
    },
    Revenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    ProtocolRevenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    SupplySideRevenue: {
      'Yield To smxHYPE Stakers': "Share of distributed yield paid to smxHYPE stakers.",
      'Yield To Insurance Fund': "Share of distributed yield routed to the insurance-fund reserve.",
    },
    UserFees: {
      'Instant Exit Fees': "Instant redeem/unstake fees paid by users.",
    },
  },
};

export default adapter;
