import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import coreAssets from "../helpers/coreAssets.json";

const USDC = coreAssets.hyperliquid.USDC;
const WHYPE = coreAssets.hyperliquid.WHYPE;

const MONETRIX_VAULT = '0x5586c2c8223C73Ec0B41D6352748e6c173372E11';
const INSTANT_REDEEM = '0xF4F03Bbfb6D314fD1D1E22012905d778f5B0adD2';
const INSTANT_UNSTAKE = '0x7592b9Fc42E000783d491739c77CcB86F19c4132';
const HYPE_VAULT = '0x270A9d32F893A5D3ff1878185010894dd890593D';
const HYPE_INSTANT_REDEEM = '0x80e9b092395fda5d4391aE03ACa6Afcf2bAe3051';
const HYPE_INSTANT_UNSTAKE = '0x930Ec4B9066fCDa704501CFEf286e6f095EF2450';

const YIELD_DISTRIBUTED_ABI = 'event YieldDistributed(uint256 totalYield, uint256 userShare, uint256 insuranceShare, uint256 foundationShare)';
const INSTANT_EXITED_ABI = 'event InstantExited(address indexed user, uint256 inputAmount, uint256 payout, uint256 fee)';

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const dailyUserFees = options.createBalances();

  // Yield generated by the USDM strategy and mxHYPE's borrowed-USDC overlay on
  // Hyperliquid Core. Each vault distributes the yield in its own base asset.
  const addYieldLogs = (logs: any[], token: string, stakerLabel: string) => logs.forEach((log: any) => {
    dailyFees.add(token, log.totalYield, 'Yield');
    dailySupplySideRevenue.add(token, log.userShare, stakerLabel);
    dailySupplySideRevenue.add(token, log.insuranceShare, 'Yield To Insurance Fund');
    dailyRevenue.add(token, log.foundationShare, 'Yield To Foundation');
    dailyProtocolRevenue.add(token, log.foundationShare, 'Yield To Foundation');
  });
  const usdmYieldLogs = await options.getLogs({ target: MONETRIX_VAULT, eventAbi: YIELD_DISTRIBUTED_ABI });
  addYieldLogs(usdmYieldLogs, USDC, 'Yield To sUSDM Stakers');
  const hypeYieldLogs = await options.getLogs({ target: HYPE_VAULT, eventAbi: YIELD_DISTRIBUTED_ABI });
  addYieldLogs(hypeYieldLogs, WHYPE, 'Yield To smxHYPE Stakers');

  // USDM-product fees are 6-decimal stablecoin amounts booked as USDC;
  // mxHYPE-product fees are native HYPE amounts booked as WHYPE for pricing.
  const addExitLogs = (logs: any[], token: string) => logs.forEach((log: any) => {
    dailyFees.add(token, log.fee, 'Instant Exit Fees');
    dailyRevenue.add(token, log.fee, 'Instant Exit Fees');
    dailyProtocolRevenue.add(token, log.fee, 'Instant Exit Fees');
    dailyUserFees.add(token, log.fee, 'Instant Exit Fees');
  });
  const usdmExitLogs = await options.getLogs({ targets: [INSTANT_REDEEM, INSTANT_UNSTAKE], eventAbi: INSTANT_EXITED_ABI });
  addExitLogs(usdmExitLogs, USDC);
  const hypeExitLogs = await options.getLogs({ targets: [HYPE_INSTANT_REDEEM, HYPE_INSTANT_UNSTAKE], eventAbi: INSTANT_EXITED_ABI });
  addExitLogs(hypeExitLogs, WHYPE);

  return { dailyFees, dailyRevenue, dailyProtocolRevenue, dailySupplySideRevenue, dailyUserFees };
};

const adapter: SimpleAdapter = {
  version: 2,
  chains: [CHAIN.HYPERLIQUID],
  fetch,
  start: '2026-06-10',
  pullHourly: true,
  methodology: {
    Fees: "Yield generated by the USDM strategy and mxHYPE's borrowed-USDC overlay on Hyperliquid Core, measured at distribution via each vault's YieldDistributed event, plus instant redeem/unstake fees paid by users.",
    Revenue: "Share of distributed yield routed to the foundation, plus instant redeem/unstake fees. The insurance-fund share is a protocol reserve that backstops the system and is booked as supply-side revenue rather than protocol revenue.",
    ProtocolRevenue: "Revenue kept by the protocol. Monetrix has no token holder distribution, so protocol revenue equals total revenue (foundation share plus instant redeem/unstake fees; the insurance-fund reserve is booked as supply-side, not revenue).",
    SupplySideRevenue: "Share of distributed yield paid to sUSDM and smxHYPE stakers, plus the insurance-fund reserves that backstop the system for stakers (cost of system security).",
    UserFees: "Instant redeem/unstake fees paid by users for skipping the delayed exit flow.",
  },
  breakdownMethodology: {
    Fees: {
      'Yield': "Total yield generated by the USDM strategy and mxHYPE's borrowed-USDC overlay on Hyperliquid Core, measured at distribution via each vault's YieldDistributed event.",
      'Instant Exit Fees': "Fees paid by users who take the instant redeem/unstake flow to skip the delayed exit.",
    },
    Revenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    ProtocolRevenue: {
      'Yield To Foundation': "Share of distributed yield routed to the foundation.",
      'Instant Exit Fees': "Instant redeem/unstake fees retained by the protocol.",
    },
    SupplySideRevenue: {
      'Yield To sUSDM Stakers': "Share of distributed yield paid to sUSDM stakers.",
      'Yield To smxHYPE Stakers': "Share of distributed yield paid to smxHYPE stakers.",
      'Yield To Insurance Fund': "Share of distributed yield routed to the insurance-fund reserve that backstops the system for stakers.",
    },
    UserFees: {
      'Instant Exit Fees': "Instant redeem/unstake fees paid by users.",
    },
  },
};

export default adapter;
