import ADDRESSES from '../helpers/coreAssets.json'
import { Dependencies, FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { queryDuneSql } from "../helpers/dune";

// source: https://dune.com/o1/o1-exchange
// source: volume and fees - https://dune.com/queries/6136041 

const O1_EXCHANGE_BASE_ADDRESS = '0x3f80f138221cd5aa201b41456f6400f379508433';
const O1_EXCHANGE_BASE_FEE_COLLECTOR = '0x1E493E7CF969FD7607A8ACe7198f6C02e5eF85A4';
const O1_EXCHANGE_BASE_FEE_COLLECTOR_2 = '0xc98218Df72975EE1472919d2685e5BD215Baaad4';
const O1_EXCHANGE_SOLANA_FEE_COLLECTOR = 'FUzZ2SPwLPAKaHubxQzRsk9K8dXb4YBMR6hTrYEMFFZc';
const O1_EXCHANGE_SOLANA_FEE_COLLECTOR_2 = 'HG73jy6opRQwgTaynUeT6MxX6h3mshNWLPGHme4HdiYy';

const fetch = async (_a: any, _b: any, options: FetchOptions) => {
  const dailyVolume = options.createBalances();
  const dailyFees = options.createBalances();

  const sql = `
    with base as (
        SELECT date_trunc('day', block_time) as day, SUM(amount_usd) as "Trading Fees", SUM(amount_usd)*100 as "Trading Volume" FROM tokens_base.transfers t
        WHERE to IN (${O1_EXCHANGE_BASE_FEE_COLLECTOR}, ${O1_EXCHANGE_BASE_FEE_COLLECTOR_2})
        AND block_number >= 34250174
        AND contract_address IN (0x0000000000000000000000000000000000000000, ${ADDRESSES.base.WETH})
        AND "from" NOT IN (${ADDRESSES.base.WETH}, ${O1_EXCHANGE_BASE_ADDRESS})
        GROUP BY 1
        ),

        solana AS (
        SELECT DAY, SUM("Trading Fees") as "Trading Fees", SUM("Trading Volume") as "Trading Volume" FROM (
        SELECT date_trunc('day', block_time) as day, SUM(amount_usd) as "Trading Fees", SUM(amount_usd)*100 as "Trading Volume" FROM tokens_solana.transfers
        WHERE to_owner = '${O1_EXCHANGE_SOLANA_FEE_COLLECTOR}'
        AND block_slot >= 345561824
        AND token_mint_address = '${ADDRESSES.solana.SOL}'
        AND token_version = 'native'
        GROUP BY 1
        UNION ALL 
        SELECT date_trunc('day', block_time) as day, SUM(amount_usd) as "Trading Fees", 0 as "Trading Volume" FROM tokens_solana.transfers
        WHERE to_owner = '${O1_EXCHANGE_SOLANA_FEE_COLLECTOR_2}'
        AND block_slot >= 345561824
        AND token_mint_address = 'So11111111111111111111111111111111111111111'
        AND token_version = 'native'
        GROUP BY 1
        )
        GROUP BY 1
        )

        SELECT
        COALESCE(s.day, b.day) AS "Date",
        COALESCE(s."Trading Fees", 0) + COALESCE(b."Trading Fees", 0) AS "Trading Fees",
        COALESCE(s."Trading Volume", 0) + COALESCE(b."Trading Volume", 0) AS "Trading Volume"
        FROM solana s
        FULL OUTER JOIN base b
        ON s.day = b.day
  `;
  const result = await queryDuneSql(options, sql);
  dailyVolume.addUSDValue(Number(result[0]["Trading Volume"]));
  dailyFees.addUSDValue(Number(result[0]["Trading Fees"]));

  return {
    dailyVolume,
    dailyFees,
    dailyUserFees: dailyFees,
  };
};

const methodology = {
  Volume: "All trading volume generated by users while using o1.exchange, tracked via on-chain Base and Solana transfers.",
  Fees: "All trading fees paid by users while using o1.exchange, tracked via on-chain Base and Solana transfers.",
  UserFees: "Trading fees are paid by users while using o1.exchange, tracked via on-chain Base and Solana transfers.",
};

const adapter: SimpleAdapter = {
  version: 1,
  fetch,
  chains: [CHAIN.BASE, CHAIN.SOLANA],
  start: "2025-06-09",
  methodology,
  isExpensiveAdapter: true,
  dependencies: [Dependencies.DUNE],
};

export default adapter;
