import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { METRIC } from "../helpers/metrics";
import ADDRESSES from "../helpers/coreAssets.json";

/**
 * OmniYield (https://omniyield.finance)
 *
 * OmniYield is an omnichain yield optimizer and aggregator deployed on Arbitrum One.
 * Capital is managed across high-performing DeFi yield venues by an automated execution
 * layer (solver) and reported to on-chain vault oracle contracts on Arbitrum.
 *
 * Deployed Vault Contracts (Arbitrum):
 * - omUSDT: 0xaB40809B0CA54CBA1aE682cbA2869441F5E6f8AE (USDT, 6 dec)
 * - omUSDC: 0xFC83A8234BFAAABa079B9f6ec34382e06fA4Cbd0 (USDC, 6 dec)
 * - omDAI:  0xD5Ec0723d5dcb14d56b8Dd1afDeE5c034DB72429 (DAI, 18 dec)
 * - omWETH: 0x47C8976B8258d15e318dbf0D184a2c5E8250Ad73 (WETH, 18 dec)
 * - omWBTC: 0x3A12220dDec131f26940FcC970F1cA97A95E32171 (WBTC, 8 dec)
 * - OmniPool (OMP): 0x1a0493c57704fb70bb3e6f0ee5fc637f998da762 (CAKE, 18 dec)
 *
 * Fee & Revenue Mechanics:
 * - Gross protocol yield generated by underlying structured DeFi yield strategies.
 * - OmniYield charges a 10% performance fee on generated yield profits (0% deposit/withdrawal fee).
 * - 90% of yield flows to vault depositors (Supply-Side Revenue).
 * - 10% of yield flows to Protocol Revenue.
 * - Tokenholders Revenue: Tokenomics reserves 50% of protocol fees for veOY voters once on-chain distribution is active.
 * - Strategy drawdowns are captured via exchange-rate / totalValue depreciation (allowNegativeValue: true).
 */

interface VaultConfig {
  name: string;
  vault: string;
  token: string;
}

const VAULTS: VaultConfig[] = [
  {
    name: "omUSDT",
    vault: "0xaB40809B0CA54CBA1aE682cbA2869441F5E6f8AE",
    token: ADDRESSES.arbitrum.USDT,
  },
  {
    name: "omUSDC",
    vault: "0xFC83A8234BFAAABa079B9f6ec34382e06fA4Cbd0",
    token: ADDRESSES.arbitrum.USDC_CIRCLE,
  },
  {
    name: "omDAI",
    vault: "0xD5Ec0723d5dcb14d56b8Dd1afDeE5c034DB72429",
    token: ADDRESSES.arbitrum.DAI,
  },
  {
    name: "omWETH",
    vault: "0x47C8976B8258d15e318dbf0D184a2c5E8250Ad73",
    token: ADDRESSES.arbitrum.WETH,
  },
  {
    name: "omWBTC",
    vault: "0x3A12220dEc131f26940FcC970F1cA97A95E32171",
    token: ADDRESSES.arbitrum.WBTC,
  },
  {
    name: "OMP",
    vault: "0x1a0493c57704fb70bb3e6f0ee5fc637f998da762",
    token: "0x1b896893dfc86bb67Cf57767298b9073D2c1bA2c", // CAKE
  },
];

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const vaultAddresses = VAULTS.map((v) => v.vault);

  // Query totalValue across all vault contracts at the start and end of the reporting window
  const [fromValues, toValues] = await Promise.all([
    options.fromApi.multiCall({
      abi: "function totalValue() view returns (uint256)",
      calls: vaultAddresses,
    }),
    options.api.multiCall({
      abi: "function totalValue() view returns (uint256)",
      calls: vaultAddresses,
    }),
  ]);

  for (let i = 0; i < VAULTS.length; i++) {
    const config = VAULTS[i];
    const fromVal = BigInt(fromValues[i] ?? 0);
    const toVal = BigInt(toValues[i] ?? 0);

    const delta = toVal - fromVal;
    if (delta === 0n) continue;

    if (delta > 0n) {
      // 10% performance fee on profits (docs.omniyield.finance / vault configuration)
      const protocolRevenue = (delta * 10n) / 100n;
      const supplySideYield = delta - protocolRevenue;

      dailySupplySideRevenue.add(config.token, supplySideYield, METRIC.ASSETS_YIELDS);
      dailyRevenue.add(config.token, protocolRevenue, METRIC.PERFORMANCE_FEES);
      dailyProtocolRevenue.add(config.token, protocolRevenue, METRIC.PERFORMANCE_FEES);
      dailyFees.add(config.token, supplySideYield, METRIC.ASSETS_YIELDS);
      dailyFees.add(config.token, protocolRevenue, METRIC.PERFORMANCE_FEES);
    } else {
      // Drawdown: full negative yield is absorbed by depositors; 0 protocol fee charged on losses
      dailySupplySideRevenue.add(config.token, delta, METRIC.ASSETS_YIELDS);
      dailyFees.add(config.token, delta, METRIC.ASSETS_YIELDS);
    }
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue,
    dailySupplySideRevenue,
    dailyHoldersRevenue: 0,
  };
};

const methodology = {
  Fees: "Total gross yield generated by OmniYield automated vaults across underlying DeFi strategies.",
  SupplySideRevenue: "Net yield distributed to vault depositors after deducting the 10% protocol performance fee.",
  Revenue: "10% performance fee charged on positive vault yield.",
  ProtocolRevenue: "All revenue from performance fees retained by the protocol treasury.",
  HoldersRevenue: "Currently 0. Tokenomics specifies 50% of protocol fees will be distributed to veOY voters once on-chain voting/staking distribution is active.",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]: "Gross returns generated by underlying vault yield strategies accruing to depositors.",
    [METRIC.PERFORMANCE_FEES]: "10% performance fee charged on positive yield profits.",
  },
  Revenue: {
    [METRIC.PERFORMANCE_FEES]: "10% performance fee on strategy profits collected by the protocol.",
  },
  ProtocolRevenue: {
    [METRIC.PERFORMANCE_FEES]: "10% performance fee on strategy profits collected by the protocol treasury.",
  },
  SupplySideRevenue: {
    [METRIC.ASSETS_YIELDS]: "Net yield distributed to vault depositors after performance fees.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  allowNegativeValue: true,
  adapter: {
    [CHAIN.ARBITRUM]: {
      fetch,
      start: "2025-01-17",
    },
  },
  methodology,
  breakdownMethodology,
};

export default adapter;
