import { FetchOptions, SimpleAdapter } from '../adapters/types';
import { CHAIN } from '../helpers/chains';

// Origami ERC4626 vaults on Ethereum (primary source of protocol yield)
const config: any = {
  [CHAIN.ETHEREUM]: [
    '0x07c5500359161b81eb0dfff83097d5025d3cf5a2',
    '0x0f90a6962e86b5587b4c11ba2b9697dc3ba84800',
    '0xb50201998b92d2e685432b90331bb5825415926e'
  ],
};

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailyProtocolRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const vaults = config[options.chain];

  const [totalAssetsBefore, totalAssetsAfter, assetTokens] = await Promise.all([
    options.fromApi.multiCall({
      abi: 'uint256:totalAssets',
      calls: vaults,
      permitFailure: true,
    }),
    options.toApi.multiCall({
      abi: 'uint256:totalAssets',
      calls: vaults,
      permitFailure: true,
    }),
    options.api.multiCall({
      abi: 'address:asset',
      calls: vaults,
      permitFailure: true,
    }),
  ]);

  for (let i = 0; i < vaults.length; i++) {
    const assetBefore = totalAssetsBefore[i];
    const assetAfter = totalAssetsAfter[i];
    const assetToken = assetTokens[i];

    if (!assetBefore || !assetAfter || !assetToken) {
      continue;
    }

    // NOTE: totalAssets may include deposits/withdrawals (positive deltas are treated as yield)
    const yieldAmount = BigInt(assetAfter) - BigInt(assetBefore);

    if (yieldAmount <= 0n) {
      continue;
    }

    dailyFees.add(assetToken, yieldAmount);

    const protocolFee = (yieldAmount * 5n) / 100n; // 5% performance fee assumption
    dailyProtocolRevenue.add(assetToken, protocolFee);
    dailyRevenue.add(assetToken, protocolFee);

    const supplySideFee = yieldAmount - protocolFee;
    dailySupplySideRevenue.add(assetToken, supplySideFee);
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: 'Total yield generated by Origami ERC4626 vaults, measured as the daily change in totalAssets before fee distribution.',
  Revenue:
    'Protocol performance fees taken as a percentage of vault yield and collected via share inflation.',
  ProtocolRevenue:
    'Performance fees minted as new vault shares to the protocol treasury.',
  SupplySideRevenue:
    'Remaining vault yield (after performance fees) that accrues to existing vault shareholders. This represents the net return earned by depositors.',
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.ETHEREUM]: {
      fetch,
      start: '2024-10-17',
    },
  },
  methodology,
};

export default adapter;
