import { FetchOptions, SimpleAdapter } from '../adapters/types';
import { CHAIN } from '../helpers/chains';

// PufferVault (pufETH token) - Main vault contract
// Source: https://docs.puffer.fi/yield/deployments/deployed-contracts
// Etherscan: https://etherscan.io/address/0xD9A442856C234a39a81a089C06451EBAa4306a72
const pufferVaultAddress = '0xD9A442856C234a39a81a089C06451EBAa4306a72';

// Vault holds assets in WETH/ETH
const WETH = '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2';

const abis = {
  totalAssets: 'uint256:totalAssets',
  convertToAssets:
    'function convertToAssets(uint256 shares) view returns (uint256)',
};

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();

  // Get total assets at start and end of day
  const [totalAssetsStart] = await options.fromApi.multiCall({
    abi: abis.totalAssets,
    calls: [pufferVaultAddress],
  });

  const [totalAssetsEnd] = await options.toApi.multiCall({
    abi: abis.totalAssets,
    calls: [pufferVaultAddress],
  });

  // Calculate total yield: change in vault's totalAssets over the day
  // Includes: staking rewards, restaking rewards, and withdrawal fees
  const totalYield = totalAssetsEnd - totalAssetsStart;

  if (totalYield > 0) {
    // Daily fees = total yields generated by the vault
    dailyFees.add(WETH, totalYield);

    // Protocol revenue: estimated at 10% based on documented performance fee
    // Note: 1% instant withdrawal fees also go to protocol treasury
    const estimatedRevenue = totalYield * 0.1;
    dailyRevenue.add(WETH, estimatedRevenue);
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
  };
};

// Fee structure sources:
// - 1% instant withdrawal fee (goes to protocol treasury): https://docs.puffer.fi/yield/stakers/withdraw
// - 10% performance fee on restaking rewards: https://github.com/PufferFinance/puffer-contracts
// - 0% fee on standard withdrawals (2-step, takes up to 14 days): https://docs.puffer.fi/yield/stakers/withdraw
const methodology = {
  Fees: 'Total yields generated from staking rewards, restaking rewards, instant withdrawal fees (1% to protocol treasury), and performance fees (10%). Puffer Vaults charges 1% on instant withdrawals (goes to protocol treasury for protocol improvements and PUFFER token buybacks) and 10% performance fee on restaking rewards.',
  Revenue:
    'Estimated protocol revenue from performance fees and instant withdrawal fees. Estimate of ~10% of total yields based on documented 10% performance fee. The 1% instant withdrawal fee is directed to the protocol treasury.',
  ProtocolRevenue:
    'Same as Revenue - protocol captures performance fees (10% on restaking rewards) and instant withdrawal fees (1%, sent to treasury).',
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.ETHEREUM]: {
      fetch,
      start: '2024-01-31',
    },
  },
  methodology,
};

export default adapter;
