import { FetchOptions, SimpleAdapter } from '../adapters/types';
import { CHAIN } from '../helpers/chains';

const WSRUSD_CONTRACT = '0xd3fd63209fa2d55b07a0f6db36c2f43900be3094';
const RUSD_CONTRACT = '0x31Eae643b679A84b37E3d0B4Bd4f5dA90fB04a61';

const abis = {
  convertToAssets:
    'function convertToAssets(uint256 shares) view returns (uint256)',
  totalSupply: 'uint256:totalSupply',
};

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const [totalSupplyStart, totalSupplyEnd] = await Promise.all([
    options.fromApi.call({
      target: WSRUSD_CONTRACT,
      abi: abis.totalSupply,
    }),
    options.toApi.call({
      target: WSRUSD_CONTRACT,
      abi: abis.totalSupply,
    }),
  ]);

  const [rateStart, rateEnd] = await Promise.all([
    options.fromApi.call({
      target: WSRUSD_CONTRACT,
      abi: abis.convertToAssets,
      params: ['1000000000000000000'],
    }),
    options.toApi.call({
      target: WSRUSD_CONTRACT,
      abi: abis.convertToAssets,
      params: ['1000000000000000000'],
    }),
  ]);

  const rateGrowth = BigInt(rateEnd) - BigInt(rateStart);

  if (rateGrowth > 0n) {
    const avgSupply = (BigInt(totalSupplyStart) + BigInt(totalSupplyEnd)) / 2n;
    const yieldAmount = (rateGrowth * avgSupply) / BigInt(1e18);

    // Exchange rate growth is treated as system yield, fully distributed to wsrUSD holders
    dailyFees.add(RUSD_CONTRACT, yieldAmount);
    dailySupplySideRevenue.add(RUSD_CONTRACT, yieldAmount);
  }

  return {
    dailyFees,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: 'Yield earned by wsrUSD holders as the exchange rate to rUSD increases over time.',
  SupplySideRevenue:
    'All yield generated by wsrUSD. The full amount is distributed to token holders and not retained by the protocol.',
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.ETHEREUM]: {
      fetch,
      start: '2025-04-15',
    },
  },
  methodology,
};

export default adapter;
