import { SimpleAdapter, FetchOptions } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { getERC4626VaultsYield } from "../helpers/erc4626";

// Cellar addresses - Sommelier cellars are ERC4626-compatible vaults
const CELLARS: Record<string, string[]> = {
  [CHAIN.ETHEREUM]: [
    "0x97e6e0a40a3d02f12d1cec30ebfbae04e37c119e", // Real Yield USD
    "0xb5b29320d2dde5ba5bafa1ebcd270052070483ec", // Real Yield ETH
    "0x0274a704a6d9129f90a62ddc6f6024b33ecdad36", // Real Yield BTC
    "0x03df2a53cbed19b824347d6a45d09016c2d1676a", // DeFi Stars
    "0x6c51041a91c91c86f3f08a72cb4d3f67f1208897", // ETH Growth
    "0x0c190ded9be5f512bd72827bdad4003e9cc7975c", // Turbo GHO
    "0xfd6db5011b171b05e1ea3b92f9eacaeeb055e971", // Turbo stETH
    "0xc7372Ab5dd315606dB799246E8aA112405abAeFf", // Turbo stETH Deposit
    "0xcf4b531b4cde95bd35d71926e09b2b54c564f5b6", // Morpho Maximizer
    "0x6c1edce139291Af5b84fB1e496c9747F83E876c9", // Turbo divETH
    "0x19B8D8FC682fC56FbB42653F68c7d48Dd3fe597E", // Turbo ETHX
    "0xdAdC82e26b3739750E036dFd9dEfd3eD459b877A", // Turbo eETH V2
    "0x1dffb366b5c5A37A12af2C127F31e8e0ED86BDbe", // Turbo rsETH
    "0x27500De405a3212D57177A789E30bb88b0AdbeC5", // Turbo ezETH
  ],
  [CHAIN.ARBITRUM]: [
    "0xC47bB288178Ea40bF520a91826a3DEE9e0DbFA4C", // Real Yield ETH ARB
    "0x392B1E6905bb8449d26af701Cdea6Ff47bF6e5A8", // Real Yield USD ARB
  ],
  [CHAIN.OPTIMISM]: [
    "0xC47bB288178Ea40bF520a91826a3DEE9e0DbFA4C", // Real Yield ETH OPT
  ],
};

const chainConfig: Record<string, {cellars: string[], start: string}> = {
  [CHAIN.ETHEREUM]: {
    cellars: CELLARS[CHAIN.ETHEREUM],
    start: '2023-01-01',
  },
  [CHAIN.ARBITRUM]: {
    cellars: CELLARS[CHAIN.ARBITRUM],
    start: '2024-01-01',
  },
  [CHAIN.OPTIMISM]: {
    cellars: CELLARS[CHAIN.OPTIMISM],
    start: '2024-02-01',
  },
};

const fetch = async (options: FetchOptions) => {
  const config = chainConfig[options.chain];
  
  // Get total yield from share price growth
  const totalYield = await getERC4626VaultsYield({
    options,
    vaults: config.cellars,
  });
  
  // Get strategist split from cellar feeData
  const feeData = await options.api.multiCall({
    abi: 'function feeData() view returns (uint64 strategistPlatformCut, uint64 platformFee, uint64 lastAccrual, address strategistPayoutAddress)',
    calls: config.cellars,
    permitFailure: true,
  });
  
  // Calculate average strategist cut
  let totalStrategistCut = 0;
  let count = 0;
  for (const fees of feeData) {
    if (fees?.strategistPlatformCut) {
      totalStrategistCut += Number(fees.strategistPlatformCut) / 1e18;
      count++;
    }
  }
  const avgStrategistCut = count > 0 ? totalStrategistCut / count : 0.5; // Default 50%
  
  // Sommelier fee structure (based on documentation):
  // - Management fees: ~1% annually
  // - Performance fees: ~10-20% on profits above high-watermark
  // - Combined effective rate: ~5-10% of yield
  // Since we can't get exact rates easily, using conservative 5% (could be changed if needed)
  const ESTIMATED_FEE_RATE = 0.05; // 5% of yield goes to fees
  
  const dailyFees = totalYield;  // Total yield (100%)
  const totalFeesCollected = totalYield.clone(ESTIMATED_FEE_RATE);  // ~5% as fees
  const dailyProtocolRevenue = totalFeesCollected.clone(avgStrategistCut);  // Protocol's share
  const dailyStrategistRevenue = totalFeesCollected.clone(1 - avgStrategistCut);  // Strategist's share
  const dailySupplySideRevenue = totalYield.clone(1 - ESTIMATED_FEE_RATE);  // ~95% to depositors
  
  // Strategists are supply side
  dailySupplySideRevenue.addBalances(dailyStrategistRevenue);
  
  return {
    dailyFees,
    dailyRevenue: dailyProtocolRevenue,
    dailyProtocolRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Total yield generated by Sommelier Cellars from deposited assets, calculated from daily share price growth across all vaults. Represents the total value created before any fees are extracted.",
  SupplySideRevenue: "Net yield distributed to vault depositors after fees, plus strategist compensation. Depositors receive approximately 95% of total yield.",
  Revenue: "Management fees (~1% annual on TVL) plus performance fees (~10-20% on profits above high-watermark) collected by Sommelier protocol. Estimated at ~5% of total yield. Fees are accrued via keeper system in FeesAndReserves contract.",
  ProtocolRevenue: "Sommelier protocol's share of collected fees after strategist split. Split ratio varies by cellar (typically 50-85% to protocol). These fees are bridged to Sommelier Chain for SOMM staker distribution and token buybacks/burns.",
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: Object.keys(chainConfig).reduce((acc, chain) => ({
    ...acc,
    [chain]: {
      fetch,
      start: chainConfig[chain].start,
    }
  }), {}),
  methodology,
};

export default adapter;