import { FetchOptions, SimpleAdapter } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { METRIC } from "../helpers/metrics";

/**
 * Syntropia (https://syntropia.ai)
 *
 * Automated delta-neutral trading strategies packaged into risk-tiered ERC-4626 vaults on Ethereum.
 * Vaults manage USDC collateral deployed across perpetual DEXs and RFQ market-making strategies.
 *
 * Deployed Vaults:
 * - synUSD (Syntropia USDC Core): 0x1b2cb79a4564206f53ba80b4d780f251b4ae6765
 * - synUSD+ (Syntropia USDC): 0xd17049ed25d8f99fe3bfd10cef2263da9995cfd8
 * - synUSDx (Syntropia Boosted): 0x8df3deba711ae4a9af16cbca5e4fbb1402f036d5
 *
 * Fee & Revenue Mechanics:
 * - Gross protocol yield generated by underlying delta-neutral market-making and perpetual funding arbitrage.
 * - Yield accrues to depositors via ERC-4626 share exchange-rate appreciation (convertToAssets).
 * - 100% of yield flows to vault depositors (Supply-Side Revenue); protocol currently charges 0% performance fees.
 * - Strategy losses and negative funding drawdowns reflect in exchange-rate depreciation (allowNegativeValue: true).
 */

/**
 * Note on Vault Independence & Accounting:
 * Each vault operates as an independent Lagoon ERC-7540 / ERC-4626 vault holding USDC
 * (0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48) directly. None of the vaults hold shares
 * of one another on-chain (synUSD balance in synUSD+ and synUSDx is 0). Strategy risk
 * tranching is managed across market-making venues, matching DefiLlama's TVL adapter
 * (projects/syntropia/index.js), which sums totalAssets across all three vaults.
 */
const VAULTS = [
  "0x1b2cb79a4564206f53ba80b4d780f251b4ae6765", // synUSD (Syntropia USDC Core)
  "0xd17049ed25d8f99fe3bfd10cef2263da9995cfd8", // synUSD+ (Syntropia USDC)
  "0x8df3deba711ae4a9af16cbca5e4fbb1402f036d5", // synUSDx (Syntropia Boosted)
];

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  // Query vault metadata (underlying asset and share token decimals)
  const [assets, decimals] = await Promise.all([
    options.api.multiCall({ abi: "address:asset", calls: VAULTS }),
    options.api.multiCall({ abi: "uint8:decimals", calls: VAULTS }),
  ]);

  // One share unit scaled to vault share token decimals (typically 18 decimals: 10^18)
  const oneShareCalls = VAULTS.map((vault, i) => ({
    target: vault,
    params: [(10n ** BigInt(decimals[i] ?? 18)).toString()],
  }));

  // Query share exchange rates and total supplies at start and end of the reporting window
  const [fromRates, toRates, fromSupplies, toSupplies] = await Promise.all([
    options.fromApi.multiCall({
      abi: "function convertToAssets(uint256) view returns (uint256)",
      calls: oneShareCalls,
    }),
    options.api.multiCall({
      abi: "function convertToAssets(uint256) view returns (uint256)",
      calls: oneShareCalls,
    }),
    options.fromApi.multiCall({ abi: "uint256:totalSupply", calls: VAULTS }),
    options.api.multiCall({ abi: "uint256:totalSupply", calls: VAULTS }),
  ]);

  for (let i = 0; i < VAULTS.length; i++) {
    const asset = assets[i];
    const dec = BigInt(decimals[i] ?? 18);
    const oneShare = 10n ** dec;

    const fromRate = BigInt(fromRates[i] ?? 0);
    const toRate = BigInt(toRates[i] ?? 0);
    const fromSupply = BigInt(fromSupplies[i] ?? 0);
    const toSupply = BigInt(toSupplies[i] ?? 0);

    // In batch-settlement vaults (Lagoon / ERC-7540), valuation updates at discrete settlement
    // points. The exchange-rate delta (toRate - fromRate) applies to the shares outstanding
    // prior to settlement (fromSupply). Using fromSupply ensures that newly minted shares
    // issued during the settlement do not retroactively claim past-epoch yield.
    const shares = fromSupply > 0n ? fromSupply : toSupply;

    if (shares === 0n || fromRate === 0n || toRate === 0n) continue;

    const rateDelta = toRate - fromRate;
    if (rateDelta === 0n) continue;

    // Net yield in underlying asset units: (shares * rateDelta) / 10^shareDecimals
    const netYield = (shares * rateDelta) / oneShare;

    dailyFees.add(asset, netYield, METRIC.ASSETS_YIELDS);
    dailySupplySideRevenue.add(asset, netYield, METRIC.ASSETS_YIELDS);
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue.clone(),
    dailySupplySideRevenue,
    // Explicit 0: Protocol does not distribute tokenholder dividends or execute buybacks
    dailyHoldersRevenue: 0,
  };
};

const methodology = {
  Fees: "Total gross returns generated across Syntropia delta-neutral market-making and perpetual funding arbitrage strategies.",
  SupplySideRevenue: "100% of strategy returns accrue to vault depositors through ERC-4626 share exchange-rate appreciation.",
  Revenue: "Protocol revenue is zero as Syntropia currently charges no management or performance fees.",
  ProtocolRevenue: "Protocol revenue is zero as Syntropia currently charges no management or performance fees.",
  HoldersRevenue: "No direct distributions or buybacks to token holders.",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]: "Strategy returns distributed to depositors via ERC-4626 exchange-rate appreciation.",
  },
  SupplySideRevenue: {
    [METRIC.ASSETS_YIELDS]: "100% of strategy returns accruing to vault stakers via share price appreciation.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  allowNegativeValue: true, // strategy losses and negative funding rates flow through exchange-rate depreciation
  fetch,
  chains: [CHAIN.ETHEREUM],
  start: "2025-10-15", // Syntropia mainnet launch with verified TVL
  methodology,
  breakdownMethodology,
};

export default adapter;
