import { Interface } from "ethers"
import { Adapter, FetchOptions, FetchResultV2 } from "../adapters/types"
import { CHAIN } from "../helpers/chains"
import * as sdk from '@defillama/sdk'

/**
 *
 * Veda reinvest staked assets into others platforms and earning yield
 * Yields are distributed to stakers and Veda protocol:.
 *
 * Veda takes these fees:
 * - Performance fees, a percentage amount of yield (config per vault)
 * - Platform fees, a basic percentage amount of total assets in the vault (config per vault)
 */

const methodology = {
  Fees: 'Total yields are generated by staking assets.',
  SupplySideRevenue: 'The amount of yields are distributed to stakers.',
  Revenue: 'The amount of yields are distributed to Veda Protocol.',
  ProtocolRevenue: 'The amount of yields are distributed to Veda Protocol.',
}

interface IBoringVault {
  vault: string;
  accountant: string;
}

const BoringVaults: { [key: string]: Array<IBoringVault> } = {
  [CHAIN.ETHEREUM]: [
    { vault: "0x08c6F91e2B681FaF5e17227F2a44C307b3C1364C", accountant: "0xc315D6e14DDCDC7407784e2Caf815d131Bc1D3E7" }, // Liquid USD
    { vault: "0x917ceE801a67f933F2e6b33fC0cD1ED2d5909D88", accountant: "0xbe16605B22a7faCEf247363312121670DFe5afBE" }, // Super Symbiotic
    { vault: "0x5401b8620E5FB570064CA9114fd1e135fd77D57c", accountant: "0x28634D0c5edC67CF2450E74deA49B90a4FF93dCE" }, // LBTCv
    { vault: "0xf0bb20865277aBd641a307eCe5Ee04E79073416C", accountant: "0x0d05D94a5F1E76C18fbeB7A13d17C8a314088198" }, // Liquid ETH
    { vault: "0x7223442cad8e9cA474fC40109ab981608F8c4273", accountant: "0x126af21dc55C300B7D0bBfC4F3898F558aE8156b" }, // Karak
    { vault: "0x86B5780b606940Eb59A062aA85a07959518c0161", accountant: "0x05A1552c5e18F5A0BB9571b5F2D6a4765ebdA32b" }, // Staked ETHFI
    { vault: "0x657e8C867D8B37dCC18fA4Caead9C45EB088C642", accountant: "0x1b293DC39F94157fA0D1D36d7e0090C8B8B8c13F" }, // eBTC
    { vault: "0xeDa663610638E6557c27e2f4e973D3393e844E70", accountant: "0x1D4F0F05e50312d3E7B65659Ef7d06aa74651e0C" }, // Liquid Usual
    { vault: "0x352180974C71f84a934953Cf49C4E538a6F9c997", accountant: "0xBae19b38Bf727Be64AF0B578c34985c3D612e2Ba" }, // Liquid Elixir
    { vault: "0x939778D83b46B456224A33Fb59630B11DEC56663", accountant: "0xEB440B36f61Bf62E0C54C622944545f159C3B790" }, // eUSD
    { vault: "0x42A03534DBe07077d705311854E3B6933dD6Af85", accountant: "0x1c217f17d57d3CCD1CB3d8CB16B21e8f0b544156" }, // Coinbase BTCv
    { vault: "0xE77076518A813616315EaAba6cA8e595E845EeE9", accountant: "0x075e60550C6f77f430B284E76aF699bC31651f75" }, // eEigen
    { vault: "0xE6829d9a7eE3040e1276Fa75293Bde931859e8fA", accountant: "0x6049Bd892F14669a4466e46981ecEd75D610a2eC" }, // Mantle cMETH
    { vault: "0xFE0C961A49E1aEe2AE2d842fE40157365C6d978f", accountant: "0xf1ecf4802C2b5Cf9c830A4AF297842Daa6D0f986" }, // Pump BTC-Fi
    { vault: "0xf6d71c15657A7f2B9aeDf561615feF9E05fE2cb3", accountant: "0x37e6e4526483D05711b8D6F92c27F2f3a16FC45b" }, // Bedrock Uni BTC-Fi
    { vault: "0x5f46d540b6eD704C3c8789105F30E075AA900726", accountant: "0xEa23aC6D7D11f6b181d6B98174D334478ADAe6b0" }, // Liquid BTC
    { vault: "0x1293b71644e7E55A692Cade85a0EDB381868AA7c", accountant: "0x6b2DF248202fd0D99EBFF5744285b403982BC35F" }, // Lombard Loop BTC
    { vault: "0x5E272ca4bD94e57Ec5C51D26703621Ccac1A7089", accountant: "0x9A22F5dC4Ec86184D4771E620eb75D52E7b9E043" }, // sBTCN
    { vault: "0xbc0f3B23930fff9f4894914bD745ABAbA9588265", accountant: "0x95fE19b324bE69250138FE8EE50356e9f6d17Cfe" }, // Ultra USD
    { vault: "0x165c62448015d96c920dDA001Ae27733AF2C36c7", accountant: "0x2E0e8cF5FE97423f6929403246eBa88de4b2811D" }, // Usual Bera
    { vault: "0xAF135099ab69024701CEC9D726f26F508bd05837", accountant: "0xB647Ed8F3292F3a53e0D451F5A9f8A2d89D80F95" }, // Hourglass BTC
    { vault: "0xca8711dAF13D852ED2121E4bE3894Dae366039E4", accountant: "0xb53244f7716dC83811C8fB1a91971dC188C1C5aA" }, // Liquid Move ETH
    { vault: "0x699e04F98dE2Fc395a7dcBf36B48EC837A976490", accountant: "0x58cD5e97ffaeA62986C86ac44bB8EF7092c7ff5B" }, // tacUSD
    { vault: "0x294eecec65A0142e84AEdfD8eB2FBEA8c9a9fbad", accountant: "0x1683870f3347F2837865C5D161079Dc3fDbf1087" }, // tacETH
    { vault: "0x6Bf340dB729d82af1F6443A0Ea0d79647b1c3DDf", accountant: "0xe4858a89d5602Ad30de2018C408d33d101F53d53" }, // tacBTC
    { vault: "0xef417FCE1883c6653E7dC6AF7c6F85CCDE84Aa09", accountant: "0xc873F2b7b3BA0a7faA2B56e210E3B965f2b618f5" }, // Golden Goose
    { vault: "0xf15351A0d66743E09457C45EaE88dF34FcEe8CB7", accountant: "0xE803d9283450189f168c825AC462dfe035345114" }, // Sentora Advanced Yields ETH
  ],
  [CHAIN.BASE]: [
    { vault: "0x42A03534DBe07077d705311854E3B6933dD6Af85", accountant: "0x1c217f17d57d3CCD1CB3d8CB16B21e8f0b544156" }, // Coinbase BTC
    { vault: "0x86B5780b606940Eb59A062aA85a07959518c0161", accountant: "0x05A1552c5e18F5A0BB9571b5F2D6a4765ebdA32b" }, // Staked ETHFI
    { vault: "0x5401b8620E5FB570064CA9114fd1e135fd77D57c", accountant: "0x28634D0c5edC67CF2450E74deA49B90a4FF93dCE" }, // Lombard BTC
    { vault: "0x657e8C867D8B37dCC18fA4Caead9C45EB088C642", accountant: "0x1b293DC39F94157fA0D1D36d7e0090C8B8B8c13F" }, // EBTC
    { vault: "0xf0bb20865277aBd641a307eCe5Ee04E79073416C", accountant: "0x0d05D94a5F1E76C18fbeB7A13d17C8a314088198" }, // Liquid ETH
  ],
  [CHAIN.OPTIMISM]: [
    { vault: "0xf0bb20865277aBd641a307eCe5Ee04E79073416C", accountant: "0x0d05D94a5F1E76C18fbeB7A13d17C8a314088198" }, // Liquid ETH
    { vault: "0x5f46d540b6eD704C3c8789105F30E075AA900726", accountant: "0xEa23aC6D7D11f6b181d6B98174D334478ADAe6b0" }, // Liquid BTC
    { vault: "0x08c6F91e2B681FaF5e17227F2a44C307b3C1364C", accountant: "0xc315D6e14DDCDC7407784e2Caf815d131Bc1D3E7" }, // Liquid USD
    { vault: "0x86B5780b606940Eb59A062aA85a07959518c0161", accountant: "0x05A1552c5e18F5A0BB9571b5F2D6a4765ebdA32b" }, // Staked ETHFI
  ],
  [CHAIN.HYPERLIQUID]: [
    { vault: "0x9BA2EDc44E0A4632EB4723E81d4142353e1bB160", accountant: "0x74392Fa56405081d5C7D93882856c245387Cece2" }, // KHYPE
  ],
  [CHAIN.BERACHAIN]: [
    { vault: "0x46fcd35431f5B371224ACC2e2E91732867B1A77e", accountant: "0x4faE50B524e0D05BD73fDF28b273DB7D4A57CCe9" }, // Prime Liquid Bera BTC
    { vault: "0xB83742330443f7413DBD2aBdfc046dB0474a944e", accountant: "0x0B24A469d7c155a588C8a4ee24020F9f27090B0d" }, // Prime Liquid Bera ETH
  ],
  [CHAIN.BSC]: [
    { vault: "0x5401b8620E5FB570064CA9114fd1e135fd77D57c", accountant: "0x28634D0c5edC67CF2450E74deA49B90a4FF93dCE" }, // Lombard BTC
  ],
  [CHAIN.BOB]: [
    { vault: "0x9998e05030Aee3Af9AD3df35A34F5C51e1628779", accountant: "0x22b025037ff1F6206F41b7b28968726bDBB5E7D5" }, // Hybrid BTC
  ],
  [CHAIN.SONIC]: [
    { vault: "0x3bcE5CB273F0F148010BbEa2470e7b5df84C7812", accountant: "0x3a592F9Ea2463379c4154d03461A73c484993668" }, // Sonic scETH
    { vault: "0xd3DCe716f3eF535C5Ff8d041c1A41C3bd89b97aE", accountant: "0xA76E0F54918E39A63904b51F688513043242a0BE" }, // Sonic scUSD
    { vault: "0xBb30e76d9Bb2CC9631F7fC5Eb8e87B5Aff32bFbd", accountant: "0xC1a2C650D2DcC8EAb3D8942477De71be52318Acb" }, // Sonic scBTC
    { vault: "0x309f25d839A2fe225E80210e110C99150Db98AAF", accountant: "0x0639e239E417Ab9D1f0f926Fd738a012153930A7" }, // Sonic LBTC Vault
  ],
  [CHAIN.SCROLL]: [
    { vault: "0xf0bb20865277aBd641a307eCe5Ee04E79073416C", accountant: "0x0d05D94a5F1E76C18fbeB7A13d17C8a314088198" }, // Liquid ETH
    { vault: "0x08c6F91e2B681FaF5e17227F2a44C307b3C1364C", accountant: "0xc315D6e14DDCDC7407784e2Caf815d131Bc1D3E7" }, // Liquid USD
    { vault: "0x5f46d540b6eD704C3c8789105F30E075AA900726", accountant: "0xEa23aC6D7D11f6b181d6B98174D334478ADAe6b0" }, // Liquid BTC
    { vault: "0x657e8C867D8B37dCC18fA4Caead9C45EB088C642", accountant: "0x1b293DC39F94157fA0D1D36d7e0090C8B8B8c13F" }, // eBTC
    { vault: "0x939778D83b46B456224A33Fb59630B11DEC56663", accountant: "0xEB440B36f61Bf62E0C54C622944545f159C3B790" }, // eUSD
  ],
  [CHAIN.PLASMA]: [
    { vault: "0xd1074E0AE85610dDBA0147e29eBe0D8E5873a000", accountant: "0x737f2522d09E58a3Ea9dcCFDB127dD0dF5eB3F18" }, // Plasma USD
  ],
  [CHAIN.INK]: [
    { vault: "0x63D124cF1afC22F0CCEa376168200508d2A0868E", accountant: "0x8C9C454C51eCc717eA03eC03B904565f405DEAF7" }, // Sentora Advanced Yields USD
    { vault: "0x9761DDF8e79930b334f1Be1BD93aBE3695061CcA", accountant: "0x427a3c091F09fa6212d177060bb7456Abf538b22" }, // Advanced Strategies USDC
    { vault: "0xcaae49fb7f74cCFBE8A05E6104b01c097a78789f", accountant: "0x0C4dF79d9e35E5C4876BC1aE4663E834312DDc67" }, // Balanced Yield USDC
    { vault: "0xDbD87325D7b1189Dcc9255c4926076fF4a96A271", accountant: "0x9c2477D4Ea17d3cCC45e6b1087c94d14926F54C9" }, // Boosted Yield USDC
    { vault: "0x7Dee0120739b7ec048B469939EFB178ADbbB19B2", accountant: "0x4Bb6C416a00561ad6657110b76552c42d55Ff1d6" }, // Advanced Strategies BTC
  ],
  [CHAIN.ARBITRUM]: [
    { vault: "0x86B5780b606940Eb59A062aA85a07959518c0161", accountant: "0x05A1552c5e18F5A0BB9571b5F2D6a4765ebdA32b" }, // Staked ETHFI
    { vault: "0x657e8C867D8B37dCC18fA4Caead9C45EB088C642", accountant: "0x1b293DC39F94157fA0D1D36d7e0090C8B8B8c13F" }, // EBTC
  ],
}

const BoringVaultAbis = {
  //vault
  decimals: 'uint8:decimals',
  totalSupply: 'uint256:totalSupply',

  // accountant
  base: 'address:base',
  exchangeRateUpdated: 'event ExchangeRateUpdated(uint96 oldRate, uint96 newRate, uint64 currentTime)',
  accountantState: {
    1: 'function accountantState() view returns(address,uint128,uint128,uint96,uint16,uint16,uint64,bool,uint32,uint16)',
    2: 'function accountantState() view returns(address,uint96,uint128,uint128,uint96,uint16,uint16,uint64,bool,uint24,uint16,uint16)',
  },
}

const AccountantFeeRateBase = 1e4

interface ExchangeRateUpdatedEvent {
  blockNumber: number;
  oldRate: bigint;
  newRate: bigint;
}

// accountantState() field layout differs by version:
//   v1: [_, _, _, exchangeRate(3), ..., platformFee(9)]            (no performance fee)
//   v2: [_, _, _, _, exchangeRate(4), ..., platformFee(10), performanceFee(11)]
function readAccountantState(state: any, version: 1 | 2) {
  if (version === 2) {
    return {
      exchangeRate: Number(state[4]),
      platformFeeRate: Number(state[10]) / AccountantFeeRateBase,
      performanceFeeRate: Number(state[11]) / AccountantFeeRateBase,
    }
  }
  return {
    exchangeRate: Number(state[3]),
    platformFeeRate: Number(state[9]) / AccountantFeeRateBase,
    performanceFeeRate: 0,
  }
}

async function fetch(options: FetchOptions): Promise<FetchResultV2> {
  const dailyFees = options.createBalances()
  const dailySupplySideRevenue = options.createBalances()
  const dailyProtocolRevenue = options.createBalances()

  const vaults = BoringVaults[options.chain]

  if (vaults) {
    const accountants = vaults.map(vault => vault.accountant)

    const getTokens: Array<string | null> = await options.api.multiCall({
      abi: BoringVaultAbis.base, calls: accountants, permitFailure: true,
    })
    const getDecimals: Array<string | null> = await options.api.multiCall({
      abi: BoringVaultAbis.decimals, calls: vaults.map(vault => vault.vault), permitFailure: true,
    })
    // v2 decode succeeds only on v2 accountants; null => v1
    const getStatesV2: Array<any> = await options.api.multiCall({
      abi: BoringVaultAbis.accountantState[2], calls: accountants, permitFailure: true,
    })
    const getStatesV1: Array<any> = await options.api.multiCall({
      abi: BoringVaultAbis.accountantState[1], calls: accountants, permitFailure: true,
    })
    const getTotalSupplies: Array<string | null> = await options.api.multiCall({
      abi: BoringVaultAbis.totalSupply, calls: vaults.map(vault => vault.vault), permitFailure: true,
    })

    for (let i = 0; i < vaults.length; i++) {
      const vault = vaults[i]
      const token = getTokens[i]
      const decimals = getDecimals[i]
      const currentState = getStatesV2[i] !== null ? getStatesV2[i] : getStatesV1[i]
      const totalSupply = getTotalSupplies[i]

      // skip vaults that don't resolve on this chain (e.g. accountant has no code)
      if (token === null || decimals === null || currentState === null || totalSupply === null) {
        continue
      }

      const version: 1 | 2 = getStatesV2[i] !== null ? 2 : 1
      const accountant = accountants[i]
      const vaultRateBase = Number(10 ** Number(decimals))

      // get vaults rate updated events
      const lendingPoolContract: Interface = new Interface([
        BoringVaultAbis.exchangeRateUpdated,
      ])
      const events: Array<ExchangeRateUpdatedEvent> = (await options.getLogs({
        eventAbi: BoringVaultAbis.exchangeRateUpdated,
        entireLog: true,
        target: accountant,
      }))
        .map(log => {
          const decodeLog: any = lendingPoolContract.parseLog(log)

          const event: any = {
            blockNumber: Number(log.blockNumber),
            oldRate: decodeLog.args[0],
            newRate: decodeLog.args[1],
          }

          return event
        })

      for (const event of events) {
        // newRate - oldRate
        const growthRate = event.newRate > event.oldRate ? Number(event.newRate - event.oldRate) : 0

        // don't need to make calls if there isn't rate growth
        if (growthRate > 0) {

          // supply/state at the event block
          const totalSupplyAtUpdated = await sdk.api2.abi.call({
            chain: options.chain,
            abi: BoringVaultAbis.totalSupply,
            target: vault.vault,
            block: event.blockNumber,
          })
          const stateAtUpdated = await sdk.api2.abi.call({
            chain: options.chain,
            abi: BoringVaultAbis.accountantState[version],
            target: accountant,
            block: event.blockNumber,
          })

          const { exchangeRate, performanceFeeRate } = readAccountantState(stateAtUpdated, version)

          // rate is always greater than or equal 1
          const totalDeposited = Number(totalSupplyAtUpdated) * Number(exchangeRate) / vaultRateBase

          const supplySideYield = totalDeposited * growthRate / vaultRateBase
          const totalYield = supplySideYield / (1 - performanceFeeRate)
          const protocolFee = totalYield - supplySideYield

          dailyFees.add(token, totalYield)
          dailySupplySideRevenue.add(token, supplySideYield)
          dailyProtocolRevenue.add(token, protocolFee)
        }
      }

      // platform fees charged by Veda per year of total assets in vault
      const { exchangeRate, platformFeeRate } = readAccountantState(currentState, version)
      const totalDeposited = Number(totalSupply) * Number(exchangeRate) / vaultRateBase

      const yearInSecs = 365 * 24 * 60 * 60
      const timespan = options.fromTimestamp && options.toTimestamp ? Number(options.toTimestamp) - Number(options.fromTimestamp) : 3600
      const platformFee = totalDeposited * platformFeeRate * timespan / yearInSecs

      dailyFees.add(token, platformFee)
      dailyProtocolRevenue.add(token, platformFee)
    }
  }

  return {
    dailyFees,
    dailyRevenue: dailyProtocolRevenue,
    dailySupplySideRevenue,
    dailyProtocolRevenue,
  }
}

const adapter: Adapter = {
  version: 2,
  methodology,
  pullHourly: true,
  fetch,
  adapter: {
    [CHAIN.ETHEREUM]: {
      start: '2024-4-16',
    },
    [CHAIN.SONIC]: {
      start: '2025-02-07',
    },
    [CHAIN.BASE]: {
      start: '2024-09-06',
    },
    [CHAIN.INK]: {
      start: '2025-09-15'
    },
    [CHAIN.SCROLL]: {
      start: '2024-12-01'
    },
    [CHAIN.PLASMA]: {
      start: '2025-09-25'
    },
    [CHAIN.ARBITRUM]: {
      start: '2024-09-19'
    },
    [CHAIN.OPTIMISM]: {
      start: '2024-07-23'
    },
    [CHAIN.HYPERLIQUID]: {
      start: '2025-07-15'
    },
    [CHAIN.BERACHAIN]: {
      start: '2025-01-24'
    },
    [CHAIN.BSC]: {
      start: '2024-09-10'
    },
    [CHAIN.BOB]: {
      start: '2025-02-12'
    },
  }
}

export default adapter
