import { Adapter, FetchOptions } from "../adapters/types";
import { CHAIN } from "../helpers/chains";
import { httpGet } from "../utils/fetchURL";

async function fetch(_options: FetchOptions) {
  const data = await httpGet("https://yusan.fi/daily_metrics");

  return {
    dailyUserFees: data.daily_user_fees,
    dailyFees: data.daily_fees,
    dailyRevenue: data.daily_revenue,
    dailyProtocolRevenue: data.daily_protocol_revenue,
  };
}

const adapter: Adapter = {
  version: 2,
  adapter: {
    [CHAIN.ICP]: {
      fetch,
      start: '2026-01-01',
    },
  },
  methodology: {
    UserFees: "Interest paid by borrowers on loans, plus fees from liquidations, deposits, and withdrawals.",
    Fees: "Total fees generated by the protocol including borrower interest, liquidation fees, and user action fees.",
    Revenue: "Yusan DAO takes a variable fee on the interest paid by borrowers, as well as fees from liquidations, and from users actions like deposits and withdrawals to prevent dos attacks.",
    ProtocolRevenue: "Yusan DAO treasury's share of all protocol fees.",
  },
};

export default adapter;
