import { FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { queryDuneSql } from "../../helpers/dune";
import ADDRESSES from "../../helpers/coreAssets.json";

const FEE_COLLECTOR_ADDRESS = "Bk2qhUpf3hHZWwpYSudZkbrkA9DVKrNNhQfnH7zF67Ji";

const fetch = async (_a:any, _b:any, options: FetchOptions) => {
  const managementRevenue = await queryDuneSql(options, `
    SELECT 
      SUM(amount) / POW(10, 9) as daily_management_fees
    FROM spl_token_solana.spl_token_call_mintTo
    WHERE account_mint = '${ADDRESSES.solana.VSOL}'
      AND account_account = '${FEE_COLLECTOR_ADDRESS}'
      AND call_block_time >= from_unixtime(${options.startTimestamp})
      AND call_block_time < from_unixtime(${options.endTimestamp});
  `);

  const dailyFees = options.createBalances();
  dailyFees.addCGToken("the-vault-staked-sol", managementRevenue[0].daily_management_fees * 20);

  const otherRevenue = await queryDuneSql(options, `
    SELECT
      SUM(amount) / POW(10, 9) as other_revenue
    FROM spl_token_solana.spl_token_call_transferChecked
    WHERE account_mint = '${ADDRESSES.solana.VSOL}'
      AND account_destination = '${FEE_COLLECTOR_ADDRESS}'
      AND call_block_time >= from_unixtime(${options.startTimestamp})
      AND call_block_time < from_unixtime(${options.endTimestamp});
  `);
  
  const totalRevenue = managementRevenue[0].daily_management_fees + otherRevenue[0].other_revenue;
  const dailyRevenue = options.createBalances();
  dailyRevenue.addCGToken("the-vault-staked-sol", totalRevenue);

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue: dailyFees.subtract(dailyRevenue),
  };
};

const meta = {
  methodology: {
    Fees: 'staking yield rewards generated by the vault',
    Revenue: 'Includes 0.1% fee for delayed unstaking, 5% fee on staking rewards and a 0.1% fee applies when burning LST tokens created through the LST Creator program',
    ProtocolRevenue: 'Includes 0.1% fee for delayed unstaking, 5% fee on staking rewards and a 0.1% fee applies when burning LST tokens created through the LST Creator program',
    SupplySideRevenue: 'Staking yield rewards earned by VSOL holders',
  }
}

export default {
  version: 1,
  adapter: {
    [CHAIN.SOLANA]: {
      fetch,
      start: "2024-05-02",
      meta
    }
  },
  isExpensiveAdapter: true
};