import fetchURL from "../../utils/fetchURL";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";

const methodology = {
    Fees: 'LP fees generated by the swap transactions on Haedal AMM.',
    SupplySideRevenue: '50% percent of fees tot LPs.',
    Revenue: '50% percent of fees are revenue.',
    ProtocolRevenue: 'All revenue (50% fees) are collected by protocol.',
};

const fetch = async ({ startTimestamp, endTimestamp, startOfDay }: FetchOptions) => {
    const res = (await fetchURL(`https://haedal.xyz/api/v1/hmm/fees_revenue?poolObjectId=&fromTimestamp=${startTimestamp}&toTimestamp=${endTimestamp}`)).data;

    return {
        dailyFees: res.fee,
        dailyRevenue: res.revenue,
        dailySupplySideRevenue: Number(res.fee) - Number(res.revenue),
        dailyProtocolRevenue: res.revenue,
    };
}

const adapter: SimpleAdapter = {
    version: 2,
    fetch,
    chains: [CHAIN.SUI],
    start: '2024-12-17',
    methodology,
};

export default adapter;