import { CHAIN } from "../../helpers/chains";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import fetchURL from "../../utils/fetchURL";

// Foxify contract addresses
const contracts: any = {
    [CHAIN.SONIC]: {
        foxifyProxy: "0x6DB7d4B3Db759446Df89951149fC88088a0Ab2c3",
        fox: "0x261DFA2528dfa19011F10B168c856E02baaF0eb6",
        ebFox: "0xBD87A909F9A40FdaD6D9BE703E89A0383064D0Ab",
        foxiMaxi: "0x3725B740b33E75898e4e2E616E9BB519884edd37",
    },
};

// Foxify methodology
const methodology = {
    UserFees:
        "Trading fees paid by users when swapping tokens on Foxify DEX on Sonic blockchain.",
    Fees: "All trading fees collected by the Foxify protocol from token swaps.",
    Revenue: "Revenue generated by Foxify protocol from trading activities.",
    ProtocolRevenue:
        "Protocol share of trading fees retained by Foxify treasury.",
    SupplySideRevenue:
        "Portion of trading fees distributed to liquidity providers and stakers.",
};

// Foxify API-based fetch implementation using existing Foxify API
const fetch = async (options: FetchOptions) => {
    // Fetch data from Foxify's existing API endpoint
    const apiResponse = await fetchURL("https://api.foxify.trade/FoxifyStats");

    return {
        dailyVolume: apiResponse.volume?.daily || 0,
        totalVolume: apiResponse.volume?.alltime || 0,
    };
};

const adapter: SimpleAdapter = {
    version: 2,
    methodology,
    adapter: {
        [CHAIN.SONIC]: {
            fetch,
            start: "2025-04-24",
        },
    },
};

export default adapter;
