import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { addGasTokensReceived } from "../../helpers/token";

// World is Flat (WIF) — meme token on Robinhood Chain
// Coingecko: https://www.coingecko.com/en/coins/world-is-flat (id: world-is-flat)
// Contract (token): 0x5173b8eA6923c2d40267890D45C46a3480954773

// All fees/revenue generated by the protocol are collected as native ETH
// into this single treasury/fee-collector address on Robinhood Chain.
const FEE_ADDRESS = "0x311B0Cd65dc9b492b2A2Ae9b351d96614eb7eb8a";

const fetch = async (options: FetchOptions) => {
  // Tracks all native ETH transferred into FEE_ADDRESS during the period.
  const dailyFees = await addGasTokensReceived({
    options,
    multisigs: [FEE_ADDRESS],
  });

  // All collected ETH is assumed to be kept entirely by the protocol
  // (no supply-side/LP split known at this time).
  return {
    dailyFees,
    dailyRevenue: dailyFees,
    dailyProtocolRevenue: dailyFees,
  };
};

const methodology = {
  Fees: "All ETH received by the World is Flat protocol fee/treasury address on Robinhood Chain.",
  Revenue: "100% of collected ETH is retained by the protocol; there is currently no known supply-side (LP/staker) split.",
  ProtocolRevenue: "All collected ETH flows to the protocol treasury.",
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  fetch,
  chains: [CHAIN.ROBINHOOD],
  // Approximate — WIF's earliest recorded price activity (all-time low) was Aug 22, 2026.
  // Adjust to the fee address's actual first-received-ETH date if different.
  start: "2026-08-22",
  methodology,
  // NOTE: breakdownMethodology intentionally omitted. addGasTokensReceived applies its
  // own internal label to the balances it returns, and every label used in code must
  // exactly match an entry in breakdownMethodology or `npm test` will fail. Run the
  // adapter locally first (see below), check what label(s) show up in the output, and
  // add a breakdownMethodology object with matching labels before submitting the PR —
  // reviewers expect one even for a single fee source.
};

export default adapter;
