import { FetchOptions, SimpleAdapter, FetchResultV2 } from "../../adapters/types";
import { getConfig } from "../../helpers/cache";
import { CHAIN } from "../../helpers/chains";
import { getERC4626VaultsYield } from "../../helpers/erc4626";

const IPOR_GITHUB_ADDRESSES_URL = "https://raw.githubusercontent.com/IPOR-Labs/ipor-abi/refs/heads/main/mainnet/addresses.json";
const methodology = {
    Fees: 'Total yield generated by PlasmaVaults.',
    Revenue: 'Total fees collected by the protocol.',
    SupplySideRevenue: 'Revenue earned by PlasmaVault liquidity providers.'
};

const fetch = async (options: FetchOptions): Promise<FetchResultV2> => {
    const dailyRevenue = options.createBalances()
    const config = await getConfig('ipor/assets', IPOR_GITHUB_ADDRESSES_URL);

    const chainConfig = config[options.chain];
    if (!chainConfig || !chainConfig.vaults) {
        return { dailyFees: dailyRevenue, dailyRevenue, dailySupplySideRevenue: dailyRevenue };
    }

    const vaults = chainConfig.vaults.map((vault: any) => vault.PlasmaVault);

    const dailyFees = await getERC4626VaultsYield({ options, vaults });

    const logs = await options.getLogs({
        targets: vaults,
        onlyArgs: false,
        eventAbi: "event ManagementFeeRealized(uint256 unrealizedFeeInUnderlying, uint256 unrealizedFeeInShares)",
    })

    const assetCalls = await options.api.multiCall({
        abi: 'function asset() view returns (address)',
        calls: vaults,
        permitFailure: true,
    })

    const vaultToToken: Record<string, string> = {}
    vaults.forEach((v: string, i: number) => {
        if (assetCalls[i]) {
            vaultToToken[v.toLowerCase()] = assetCalls[i]
        }
    })

    logs.forEach((log: any) => {
        const token = vaultToToken[log.address.toLowerCase()]
        if (token) {
            dailyRevenue.add(token, log.args[0])
        }
    })

    const dailySupplySideRevenue = dailyFees.clone();
    dailySupplySideRevenue.subtract(dailyRevenue);

    return { dailyFees, dailyRevenue, dailySupplySideRevenue }
}

const adapter: SimpleAdapter = {
    version: 2,
    adapter: {
        [CHAIN.ETHEREUM]: {
            fetch,
            start: "9-29-2024",
        },
        [CHAIN.ARBITRUM]: {
            fetch,
            start: "9-3-2024",
        },
        [CHAIN.BASE]: {
            fetch,
            start: "11-8-2024",
        },
        [CHAIN.UNICHAIN]: {
            fetch,
            start: "6-18-2025",
        },
        [CHAIN.TAC]: {
            fetch,
            start: "7-11-2025",
        },
    },
    methodology
}

export default adapter;