import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import fetchURL from "../../utils/fetchURL";
import { getEnv } from "../../helpers/env";
import { METRIC } from "../../helpers/metrics";

const config = {
  WTGXX: {
    holders: [
      '0x4FA39D8Bd268aa07A3C441F04E07c8825E2ab163', // Bitgo Trust Account
      '0x860cc723935fc9a15ff8b1a94237a711dfef7857', // Redemption Contract
      '0xB1748C79709f4Ba2Dd82834B8c82D4a505003f27', // Main wallet
    ],
    tokenContract: '0x1feCF3d9d4Fee7f2c02917A66028a48C6706c179'
  },
  USTB: {
    holders: [
      '0x5fbAa3A3B489199338fbD85F7E3D444dc0504F33', // Redemption Contract
      '0xB1748C79709f4Ba2Dd82834B8c82D4a505003f27', // Main wallet
    ],
    tokenContract: '0x43415eB6ff9DB7E26A15b704e7A3eDCe97d31C4e'
  },
  BUIDL: {
    holders: [
      '0xE827ABf9F462Ac4f147753D86bc5f91E186E4E9c', // Redemption Contract
      '0xB1748C79709f4Ba2Dd82834B8c82D4a505003f27', // Main wallet
    ],
    tokenContract: '0x7712c34205737192402172409a8F7ccef8aA2AEc'
  },
}

const ONE_YEAR_IN_SECONDS = 365 * 24 * 60 * 60;

async function fetch(options: FetchOptions) {
  const FRED_API_KEY = getEnv("FRED_API_KEY");
  if (!FRED_API_KEY) {
    throw new Error("FRED_API_KEY is not set");
  }

  const yieldTokensBalances = options.createBalances();

  const calls = Object.values(config).flatMap(({ holders, tokenContract }) =>
    holders.map(holder => ({ target: tokenContract, params: [holder] }))
  )
  const tokenContracts = Object.values(config).flatMap(({ holders, tokenContract }) =>
    holders.map(() => tokenContract)
  )

  const balances = await options.api.multiCall({
    abi: 'function balanceOf(address) view returns (uint256)',
    calls,
  })

  balances.forEach((balance, i) => {
    if (balance) yieldTokensBalances.add(tokenContracts[i], balance)
  })

  const oneMonthAgo = new Date((options.fromTimestamp * 1000) - 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0];
  const tbillYieldData = await fetchURL(`https://api.stlouisfed.org/fred/series/observations?series_id=DTB3&observation_start=${oneMonthAgo}&observation_end=${options.dateString}&api_key=${FRED_API_KEY}&file_type=json`)
  const latestObservation = tbillYieldData.observations.findLast((obs: any) => obs.value !== '.');

  if (!latestObservation) {
    throw new Error("No valid tbill yield data found");
  }

  const tbillYield = Number(latestObservation.value);
  const tbillYieldAfterFees = tbillYield - 0.25 // (approx fees charged by money market funds used to back yield tokens)

  const yieldForPeriodMultiplier = tbillYieldAfterFees * (options.toTimestamp - options.fromTimestamp) / (ONE_YEAR_IN_SECONDS * 100);
  const dailyFees = yieldTokensBalances.clone(yieldForPeriodMultiplier, METRIC.ASSETS_YIELDS)

  return {
    dailyFees,
    dailySupplySideRevenue: dailyFees
  }
}

const methodology = {
  Fees: "Yields generated by onchain money market funds used to back FRX-USD tokens",
  SupplySideRevenue: "Yields distributed to FRX-USD holders on fraxnet and FRX-USD stakers onchain"
}

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]: "Yields generated by onchain money market funds used to back FRX-USD tokens"
  },
  SupplySideRevenue: {
    [METRIC.ASSETS_YIELDS]: "Yields distributed to FRX-USD holders on fraxnet and FRX-USD stakers onchain"
  }
}

const adapter: SimpleAdapter = {
  version: 1,
  fetch,
  start: '2025-02-06',
  methodology,
  breakdownMethodology,
  chains: [CHAIN.ETHEREUM],
}

export default adapter;