import { CHAIN } from "../../helpers/chains";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { queryEvents } from "../../helpers/sui";
import { METRIC } from "../../helpers/metrics";

// api.flowx.finance (exchangeTotalFeesInPeriod, exchangeStats) has returned 0 for every day since
// at least 2026-08 while the v2 AMM keeps swapping, so fees are read from the on-chain Swapped events.
const SWAPPED_EVENT = "0xba153169476e8c3114962261d1edc70de5ad9781b83cc617ecc8c1923191cae0::pair::Swapped";
const FEE_BPS = 30n; // 0.3% swap fee
const PROTOCOL_SHARE = 6n; // protocol fees = swap fees / 6

const methodology = {
  Fees: "Swap fees generated by the swap transactions on FlowX AMM (0.3% of the input amount).",
  Revenue: "Protocol fees charged from the swap fees. All pair charge this fee. Protocol fees = Swap Fees / 6",
  ProtocolRevenue:
    "Protocol fees charged from the swap fees. All pair charge this fee. Protocol fees = Swap Fees / 6",
  SupplySideRevenue: "Remaining 5/6 of swap fees go to liquidity providers.",
};

const breakdownMethodology = {
  Fees: { [METRIC.SWAP_FEES]: "0.3% swap fee on the input token of every FlowX v2 swap." },
  Revenue: { [METRIC.PROTOCOL_FEES]: "1/6 of swap fees kept by the protocol." },
  ProtocolRevenue: { [METRIC.PROTOCOL_FEES]: "1/6 of swap fees kept by the protocol." },
  SupplySideRevenue: { [METRIC.LP_FEES]: "5/6 of swap fees paid to liquidity providers." },
};

const withPrefix = (coin: string) => (coin.startsWith("0x") ? coin : "0x" + coin);

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const events: any[] = await queryEvents({ eventType: SWAPPED_EVENT, options });

  for (const e of events) {
    const xIn = BigInt(e.amount_x_in ?? 0);
    const yIn = BigInt(e.amount_y_in ?? 0);
    const [coin, amountIn] = xIn > 0n ? [e.coin_x, xIn] : [e.coin_y, yIn];
    if (amountIn <= 0n) continue;
    const fee = (amountIn * FEE_BPS) / 10000n;
    const protocolFee = fee / PROTOCOL_SHARE;
    const token = withPrefix(coin);
    dailyFees.add(token, fee, METRIC.SWAP_FEES);
    dailyRevenue.add(token, protocolFee, METRIC.PROTOCOL_FEES);
    dailySupplySideRevenue.add(token, fee - protocolFee, METRIC.LP_FEES);
  }

  return {
    dailyFees,
    dailyUserFees: dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.SUI]: {
      fetch: fetch,
      start: "2023-01-13",
    },
  },
  methodology,
  breakdownMethodology,
  pullHourly: true,
};

export default adapter;
