import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getPools, processLogs } from "../../dexs/rain-one";
import ADDRESSES from '../../helpers/coreAssets.json'


const PlatformFeeClaimEvent = "event PlatformClaim(address indexed wallet, uint256 amount)"; // USDT burnt as fees
const CreatorFeeClaimEvent = "event CreatorClaim(address indexed wallet, uint256 amount)"; // USDT paid to pool creators
const ReferrerFeeClaimEvent = "event RefererClaim(address indexed wallet, uint256 amount)"; // USDT paid to referer
const ResolverFeeClaimEvent = "event ResolverClaim(address indexed wallet, uint256 amount)"; // USDT paid to resolver
const ClaimEvent = "event Claim(address indexed wallet, uint256 winnerOption, uint256 amount, uint256 reward, uint256 totalReward)"; // USDT claimed by users (also includes pool liquidity incentive rewards)

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances(); // overall fees of each pool from protocol
  const dailyRevenue = options.createBalances(); // revenue generated by the protocol from platformFees

  const pools: any[] = await getPools(options)
  const addLogFees = (logs: any[]) => {
    if (!logs || logs.length === 0) return;
    console.log("Processing logs:", logs.length);
    logs.forEach((log: any) => {
      dailyFees.add(ADDRESSES.arbitrum.USDT, log.amount);
    })
  }

  await processLogs({
    options, pools, eventAbi: PlatformFeeClaimEvent, processor: async (logs: any) => {
    if (!logs || logs.length === 0) return;
      console.log("Processing PlatformFeeClaimEvent logs:", logs.length);
      logs.forEach((log: any) => {
        dailyFees.add(ADDRESSES.arbitrum.USDT, log.amount);
        dailyRevenue.add(ADDRESSES.arbitrum.USDT, log.amount);
      })
    }
  })

  await processLogs({ options, pools, eventAbi: CreatorFeeClaimEvent, processor: addLogFees })
  await processLogs({ options, pools, eventAbi: ReferrerFeeClaimEvent, processor: addLogFees })
  await processLogs({ options, pools, eventAbi: ResolverFeeClaimEvent, processor: addLogFees })
  // await processLogs({ options, pools, eventAbi: ClaimEvent, processor: addLogFees })

  return { dailyFees, dailyUserFees: dailyFees, dailyRevenue, dailyHoldersRevenue: dailyRevenue };
};

const methodology = {
  Fees: 'All fees paid by users for each pool in USDT via Rain Protocol Markets.',
  Revenue: 'Platform Fees are used to buy back and burn RAIN Token.',
  ProtocolRevenue: 'Protocol doesnt earn any revenue.',
  HoldersRevenue: 'Platform Fees are used to buy back and burn RAIN Token.',
}

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.ARBITRUM],
  start: "2025-02-17",
  methodology
}

export default adapter;