import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import { fetchURLAutoHandleRateLimit } from "../../utils/fetchURL";

const API = "https://api.doppler.finance/api/v1/analytics";
const chainConfig: Record<string, { start: string; vaults: { token: string; blockchain: string }[] }> = {
  [CHAIN.RIPPLE]: {
    start: "2025-03-24",
    vaults: [
      { token: "XRP", blockchain: "xrpl" },
      { token: "RLUSD", blockchain: "xrpl" },
    ],
  },
  [CHAIN.ETHEREUM]: {
    start: "2026-02-06",
    vaults: [
      { token: "RLUSD", blockchain: "ethereum" },
    ],
  },
};

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();
  const timestamp = options.startOfDay * 1000;

  const vaults = chainConfig[options.chain].vaults;
  const responses = await Promise.all(vaults.flatMap(({ token, blockchain }) => [
    fetchURLAutoHandleRateLimit(`${API}/tvl?token=${token}&blockchain=${blockchain}&period=all`),
    fetchURLAutoHandleRateLimit(`${API}/apr?token=${token}&blockchain=${blockchain}&period=all`),
  ]));

  for (let i = 0; i < vaults.length; i++) {
    const { token } = vaults[i];
    const tvlData = responses[i * 2][token]?.data ?? [];
    const aprData = responses[i * 2 + 1][token]?.data ?? [];
    const tvl = tvlData.find((item: any) => item.timestamp === timestamp)?.value;
    const apr = aprData
      .sort((a: any, b: any) => Number(a.timestamp) - Number(b.timestamp))
      .filter((item: any) => Number(item.timestamp) <= timestamp)
      .at(-1)?.value;

    if (tvl === undefined || apr === undefined) continue;

    const yieldUsd = tvl * apr / 365;
    dailyFees.addUSDValue(yieldUsd, METRIC.ASSETS_YIELDS);
    dailySupplySideRevenue.addUSDValue(yieldUsd, METRIC.ASSETS_YIELDS);
  }

  return { dailyFees, dailySupplySideRevenue, dailyRevenue: 0 };
};

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  adapter: chainConfig,
  methodology: {
    Fees: "Estimated yield generated by Doppler's XRP and RLUSD vaults, calculated from Doppler's published daily TVL and latest APR for each vault.",
    SupplySideRevenue: "Vault yield accrued to depositors.",
    Revenue: "No protocol revenue is counted because Doppler's docs do not disclose a protocol fee.",
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: "Estimated vault yield calculated as daily TVL * latest APR / 365 for the XRP and RLUSD vaults.",
    },
    SupplySideRevenue: {
      [METRIC.ASSETS_YIELDS]: "Estimated vault yield accrued to depositors.",
    },
  },
};

export default adapter;
