import { FetchOptions, SimpleAdapter } from "../../adapters/types"
import { CHAIN } from "../../helpers/chains"

const HUB = '0x8880b95E1a056d537FA7469D1a26C3875e85f0e7'
const ORDER_EXECUTED_EVENT = 'event OrderExecuted(bytes32 indexed orderKey, uint128 liquidity, uint256 fee0, uint256 fee1, uint256 returned0, uint256 returned1)'
const VAULT_HUB_ABI = 'function hub() view returns (address)'

const GET_ORDER_ABI = {
  inputs: [{ internalType: 'bytes32', name: 'orderKey', type: 'bytes32' }],
  name: 'getOrder',
  outputs: [{
    components: [
      { internalType: 'address', name: 'vault', type: 'address' },
      { internalType: 'address', name: 'adapter', type: 'address' },
      { internalType: 'address', name: 'token0', type: 'address' },
      { internalType: 'address', name: 'token1', type: 'address' },
      { internalType: 'uint256', name: 'capital', type: 'uint256' },
      { internalType: 'bool', name: 'isSell', type: 'bool' },
      { internalType: 'int24', name: 'targetTick', type: 'int24' },
      { internalType: 'uint24', name: 'triggerTicks', type: 'uint24' },
      { internalType: 'bytes', name: 'adapterData', type: 'bytes' },
      { internalType: 'address', name: 'referrer', type: 'address' },
      { internalType: 'bool', name: 'keepBalancesInVault', type: 'bool' },
      { internalType: 'bool', name: 'unwrapOut', type: 'bool' },
      { internalType: 'bool', name: 'closed', type: 'bool' },
      { internalType: 'uint32', name: 'rerangeCount', type: 'uint32' },
      { internalType: 'uint40', name: 'createdAt', type: 'uint40' },
      { internalType: 'uint40', name: 'lastRerangeAt', type: 'uint40' },
      { internalType: 'uint256', name: 'accruedFee0', type: 'uint256' },
      { internalType: 'uint256', name: 'accruedFee1', type: 'uint256' },
      { internalType: 'uint256', name: 'idle0', type: 'uint256' },
      { internalType: 'uint256', name: 'idle1', type: 'uint256' },
    ],
    internalType: 'struct RerangeTypes.Order',
    name: '',
    type: 'tuple',
  }],
  stateMutability: 'view',
  type: 'function',
} as const

const getOrderToken = (order: any, key: 'token0' | 'token1', index: 2 | 3): string | null => {
  if (!order) return null
  return order[key] ?? order[index] ?? null
}

const addFee = (token: string | null, amount: bigint, balances: ReturnType<FetchOptions['createBalances']>) => {
  if (!token || amount === 0n) return
  balances.add(token, amount)
}

const fetch = async ({ createBalances, getLogs, api }: FetchOptions) => {
  const dailyFees = createBalances()

  const logs = await getLogs({
    noTarget: true,
    entireLog: true,
    eventAbi: ORDER_EXECUTED_EVENT,
  })

  if (!logs.length) {
    return {
      dailyFees,
    }
  }

  const vaultAddresses = [...new Set(logs.map((log: any) => String(log.address).toLowerCase()))]
  const vaultHubs = await api.multiCall({
    abi: VAULT_HUB_ABI,
    calls: vaultAddresses,
    permitFailure: true,
  })

  const rerangeVaultSet = new Set(
    vaultAddresses.filter((vault, index) => String(vaultHubs[index] ?? '').toLowerCase() === HUB.toLowerCase())
  )

  const rerangeLogs = logs.filter((log: any) => rerangeVaultSet.has(String(log.address).toLowerCase()))

  if (!rerangeLogs.length) {
    return {
      dailyFees,
    }
  }

  const orders = await api.multiCall({
    abi: GET_ORDER_ABI,
    calls: rerangeLogs.map((log: any) => ({ target: HUB, params: [log.args.orderKey] })),
    permitFailure: true,
  })

  rerangeLogs.forEach((log: any, index: number) => {
    const order = orders[index]
    if (!order) return

    const token0 = getOrderToken(order, 'token0', 2)
    const token1 = getOrderToken(order, 'token1', 3)
    const fee0 = BigInt(log.args.fee0)
    const fee1 = BigInt(log.args.fee1)

    addFee(token0, fee0, dailyFees)
    addFee(token1, fee1, dailyFees)
  })

  return {
    dailyFees,
  }
}

const methodology = {
  Fees: 'Total LP fees generated during Rerange order execution, measured onchain from vault OrderExecuted events as fee0 + fee1 across reranges and closes.',
  UserFees: 'Users do not pay fees to Rerange. Fees are generated by the underlying AMM during execution.',
}

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.ETHEREUM]: {
      fetch,
      start: '2026-01-01',
    },
    [CHAIN.BASE]: {
      fetch,
      start: '2026-01-01',
    },
  },
  methodology,
}

export default adapter
