import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

const LAUNCHPAD = "0x778F7b2d844B7C366b386d8Ce62110ceA301C777";
const WETH = "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73";
const LAUNCHPAD_DEPLOYMENT_BLOCK = 6990219;

const BPS = 10_000n;
const POOL_FEE_BPS = 100n;
const PLATFORM_SHARE_BPS = 6_000n;
const COMMUNITY_SHARE_BPS = 3_000n;

const LAUNCH_CREATED =
  "event LaunchCreated(uint256 indexed launchId, address indexed token, address indexed creator, address pool, uint256 positionTokenId, uint256 initialBuyWeth, uint256 initialTokensOut, string name, string symbol)";
const DEPLOY_FEE_PAID =
  "event DeployFeePaid(uint256 indexed launchId, address indexed payer, uint256 amount)";
const SWAP =
  "event Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)";

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  const [launchFeeLogs, launchLogs] = await Promise.all([
    options.getLogs({ target: LAUNCHPAD, eventAbi: DEPLOY_FEE_PAID }),
    options.getLogs({
      target: LAUNCHPAD,
      eventAbi: LAUNCH_CREATED,
      fromBlock: LAUNCHPAD_DEPLOYMENT_BLOCK,
      cacheInCloud: true,
    }),
  ]);

  for (const log of launchFeeLogs) {
    dailyFees.addGasToken(log.amount, "Token Launch Fees");
    dailyRevenue.addGasToken(log.amount, "Token Launch Fees to Protocol");
  }

  const pools = launchLogs.map((log) => log.pool);
  if (pools.length) {
    const swapLogs = await options.getLogs({ targets: pools, eventAbi: SWAP });

    for (const log of swapLogs) {
      // HoodPump enforces WETH as token0 for every launched pool. The absolute
      // WETH leg is the canonical value basis for both buys and sells.
      const amount0 = BigInt(log.amount0);
      const wethLeg = amount0 < 0n ? -amount0 : amount0;
      const swapFee = (wethLeg * POOL_FEE_BPS) / BPS;
      const platformShare = (swapFee * PLATFORM_SHARE_BPS) / BPS;
      const communityShare = (swapFee * COMMUNITY_SHARE_BPS) / BPS;
      const creatorShare = swapFee - platformShare - communityShare;

      dailyFees.add(WETH, swapFee, METRIC.SWAP_FEES);
      dailyRevenue.add(WETH, platformShare, "Swap Fees to Protocol");
      dailySupplySideRevenue.add(WETH, communityShare, "Swap Fees to Community Treasuries");
      dailySupplySideRevenue.add(WETH, creatorShare, "Swap Fees to Creators");
    }
  }

  return {
    dailyFees,
    dailyUserFees: dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  UserFees: "Users pay a fixed 0.002 ETH token-launch fee and a 1% Uniswap V3 pool fee on swaps in HoodPump-launched pools.",
  Fees: "The fixed token-launch fees plus the 1% swap fees generated by pools created through the HoodPump Launchpad.",
  Revenue: "HoodPump receives the full token-launch fee and 60% of swap fees.",
  ProtocolRevenue: "The full token-launch fee and HoodPump's 60% share of swap fees.",
  SupplySideRevenue: "30% of swap fees accrue to each token's Community Treasury and 10% accrue to the token creator.",
};

const breakdownMethodology = {
  Fees: {
    "Token Launch Fees": "Fixed 0.002 ETH fee paid when a token is launched.",
    [METRIC.SWAP_FEES]: "1% Uniswap V3 pool fee on swaps in pools created by the HoodPump Launchpad.",
  },
  Revenue: {
    "Token Launch Fees to Protocol": "The full 0.002 ETH token-launch fee received by HoodPump.",
    "Swap Fees to Protocol": "HoodPump's 60% share of swap fees.",
  },
  ProtocolRevenue: {
    "Token Launch Fees to Protocol": "The full 0.002 ETH token-launch fee received by HoodPump.",
    "Swap Fees to Protocol": "HoodPump's 60% share of swap fees.",
  },
  SupplySideRevenue: {
    "Swap Fees to Community Treasuries": "30% of swap fees allocated to the launched token's Community Treasury.",
    "Swap Fees to Creators": "10% of swap fees allocated to the launched token's creator.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  pullHourly: true,
  chains: [CHAIN.ROBINHOOD],
  start: "2026-07-11",
  fetch,
  methodology,
  breakdownMethodology,
  doublecounted: true, // Swap fees are also attributed to Uniswap V3.
};

export default adapter;
