import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import fetchURL from "../../utils/fetchURL";

const BASE_URL = "https://www.polymarketexchange.com/files/time-and-sales";

interface Trade {
    transactionTime: Date;
    symbol: string;
    lastPrice: number;
    lastQuantity: number;
}

function parseTradeCSV(csv: string): Trade[] {
    const lines = csv.trim().split('\n');
    const trades: Trade[] = [];

    for (let i = 1; i < lines.length; i++) {
        const [time, symbol, price, quantity] = lines[i].split(',');
        trades.push({
            transactionTime: new Date(time),
            symbol,
            lastPrice: parseFloat(price),
            lastQuantity: parseFloat(quantity),
        });
    }

    return trades;
}

async function fetch(_a: any, _b: any, options: FetchOptions) {

    const manifestData = await fetchURL(`${BASE_URL}/manifest.json`);
    const todaysData = manifestData.files.find((item: any) => item.filename === `${options.dateString.replaceAll('-', '')}-time-and-sales.csv`);

    if (!todaysData) {
        throw new Error(`No data found for ${options.dateString}`);
    }

    const csvResponse = await fetchURL(`${BASE_URL}/${todaysData.filename}`);
    const tradesData = parseTradeCSV(csvResponse);

    const dailyVolume = options.createBalances();
    const dailyNotionalVolume = options.createBalances();
    const dailyFees = options.createBalances();
    const dailySupplySideRevenue = options.createBalances();
    const dailyRevenue = options.createBalances();

    for (const trade of tradesData) {
        dailyVolume.addUSDValue(trade.lastQuantity * trade.lastPrice);
        dailyNotionalVolume.addUSDValue(trade.lastQuantity);

        let fee = 0;

        if (options.dateString < '2026-01-09') {
            // no fees
        }
        else if (options.dateString <= '2026-04-03') {
            fee = Math.round(trade.lastQuantity * trade.lastPrice * 0.01 * 100) / 100;
            dailyFees.addUSDValue(fee, 'Taker Fees');
            dailyRevenue.addUSDValue(fee, 'Protocol Revenue');
        }
        else {
            const theta = 0.05;
            fee = Math.round(theta * trade.lastQuantity * trade.lastPrice * (1 - trade.lastPrice) * 100) / 100;
            dailyFees.addUSDValue(fee, 'Taker Fees');
            dailySupplySideRevenue.addUSDValue(fee * 0.25, 'Maker Rebates');
            dailySupplySideRevenue.addUSDValue(fee * 0.5, 'Taker Rebates');
            dailyRevenue.addUSDValue(fee * 0.25, 'Protocol Revenue');
        }
    }

    return {
        dailyVolume,
        dailyNotionalVolume,
        dailyFees,
        dailyUserFees: dailyFees,
        dailyRevenue,
        dailyProtocolRevenue: dailyRevenue,
        dailySupplySideRevenue,
    };
}

const methodology = {
    Volume: 'The total volume of trades on Polymarket US',
    NotionalVolume: 'The total notional volume of trades on Polymarket US',
    Fees: 'Users pay fees when they trade binary options on Polymarket US',
    UserFees: 'Users pay fees when they trade binary options on Polymarket US',
    Revenue: 'The total revenue generated by Polymarket US after rebates are distributed',
    ProtocolRevenue: 'All the revenue goes to protocol',
    SupplySideRevenue: 'Part of fees distributed to traders',
}

const breakdownMethodology = {
    Fees: {
        'Taker Fees': 'Users pay fees when they trade binary options on Polymarket US',
    },
    Revenue: {
        'Protocol Revenue': 'All the revenue goes to protocol post rebates are distributed',
    },
    SupplySideRevenue: {
        'Maker Rebates': 'Part of fees distributed to market makers',
        'Taker Rebates': 'Part of fees distributed to takers',
    },
}

const adapter: SimpleAdapter = {
    fetch,
    start: "2025-10-30",
    chains: [CHAIN.OFF_CHAIN],
    methodology,
    breakdownMethodology,
}

export default adapter;