import fetchURL from "../../utils/fetchURL";
import { FetchOptions, FetchResult, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";

const API_BASE = "https://api-v1.overpass.ag/v1/stats/history";
const START_DATE = "2026-05-04";

interface HistoryResponse {
  items: Array<{
    totalInterestUsd?: number;
    totalVolumeUsd?: number;
  }>;
}

async function fetchMetric(
  metric: "interest" | "volume",
  options: FetchOptions,
): Promise<HistoryResponse> {
  const from = new Date(options.startTimestamp * 1000).toISOString();
  const to = new Date(options.endTimestamp * 1000 - 1).toISOString();
  return fetchURL(
    `${API_BASE}?metric=${metric}&interval=1h&from=${from}&to=${to}&limit=5000`,
  );
}

const sum = (values: Array<number | undefined>) =>
  values.reduce((total, value) => total + (Number(value) || 0), 0);

const fetch = async (options: FetchOptions): Promise<FetchResult> => {
  const [interest, volume] = await Promise.all([
    fetchMetric("interest", options),
    fetchMetric("volume", options),
  ]);

  const interestUsd = sum(interest.items.map((item) => item.totalInterestUsd));
  const volumeUsd = sum(volume.items.map((item) => item.totalVolumeUsd));

  const dailyFees = options.createBalances();
  dailyFees.addUSDValue(interestUsd, METRIC.ASSETS_YIELDS);

  const dailySupplySideRevenue = options.createBalances();
  dailySupplySideRevenue.addUSDValue(interestUsd, METRIC.ASSETS_YIELDS);

  const dailyVolume = options.createBalances();
  dailyVolume.addUSDValue(volumeUsd);

  return {
    dailyFees,
    dailySupplySideRevenue,
    dailyRevenue: 0,
    dailyProtocolRevenue: 0,
    dailyVolume,
  };
};

const methodology = {
  Fees: "Yield generated by Overpass wrapper tokens, measured as interest/NAV growth in USD over the requested period.",
  SupplySideRevenue: "All currently tracked Overpass wrapper yield is passed through to wrapper token holders.",
  Revenue: "Zero until Overpass activates a protocol-retained fee share.",
  ProtocolRevenue: "Zero until Overpass activates a protocol-retained fee share.",
  Volume: "Successful Overpass deposit and withdrawal flow volume, priced in USD.",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.ASSETS_YIELDS]:
      "Interest and NAV growth generated by the underlying source protocols for Overpass wrappers.",
  },
  SupplySideRevenue: {
    [METRIC.ASSETS_YIELDS]:
      "Yield distributed to Overpass wrapper token holders.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.SOLANA],
  start: START_DATE,
  methodology,
  breakdownMethodology,
};

export default adapter;
