import { FetchOptions } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import coreAssets from "../../helpers/coreAssets.json";

const btcb = coreAssets.avax.BTC_b
const avBtc = '0xfd2c2A98009d0cBed715882036e43d26C4289053'
const savBtc = '0x649342c6bff544d82DF1B2bA3C93e0C22cDeBa84'
const MINT_AND_REDEEM_CONTRACT = '0x58C32c34fd4Ae48A7D45EC4b3C940b41D676cC04'

const REDEEM_ABI = 'event Redeem(address indexed redeemer,address indexed benefactor,address indexed beneficiary,address collateral_asset,uint256 collateral_amount,uint256 avantcoin_amount)'

const fetch = async (_t: number, _c: any, options: FetchOptions) => {
    const dailyFees = options.createBalances();
    const dailyRewards = options.createBalances();
    const dailyRevenue = options.createBalances();
    const dailyRedeemFees = options.createBalances();
    const logs = await options.getLogs({
        eventAbi: REDEEM_ABI,
        target: MINT_AND_REDEEM_CONTRACT,
    })
    logs.forEach((log) => {
        const fee = Number(log.avantcoin_amount) / 1e10 - Number(log.collateral_amount);
        if (fee > 0) {
            dailyRedeemFees.add(btcb, fee);
        }
  });
    dailyFees.addBalances(dailyRedeemFees, METRIC.MINT_REDEEM_FEES);
    const daily_rewards = await options.getLogs({
      eventAbi: 'event RewardsReceived (uint256 amount)',
      topic: '0xbb28dd7cd6be6f61828ea9158a04c5182c716a946a6d2f31f4864edb87471aa6',
      target: savBtc,
    })
    daily_rewards.forEach((log) => {
      dailyRewards.add(avBtc, log.amount);
      dailyRevenue.add(avBtc, Number(log.amount) / 9)
    });
    dailyFees.addBalances(dailyRewards, METRIC.ASSETS_YIELDS);

    return {
        dailyFees,
        dailyRevenue: dailyRevenue,
        dailyUserFees: dailyRedeemFees,
        dailySupplySideRevenue: dailyRewards
    }
}
const adapters = {
  adapter: {
    [CHAIN.AVAX]: {
      fetch: fetch,
      start: '2025-04-30',
    }
  },
  methodology: {
    Fees: "Redeem fees + yield distribution",
    Revenue: "10% of the net profits generated by the protocol strategies",
    UserFees: "Redeem fees from users",
  },
  breakdownMethodology: {
    Fees: {
      [METRIC.ASSETS_YIELDS]: 'The net profits generated by the protocol strategies.',
      [METRIC.MINT_REDEEM_FEES]: 'Users pay a 0.05% fee when redeeming avBTC.',
    }
  },
};
export default adapters;