import { FetchOptions, IJSON, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import { filterPools } from "../../helpers/uniswap";
import ADDRESSES from "../../helpers/coreAssets.json";

const GOON = "0x80ea4cd0e33f8323cd3d33d7006f247733177a9e";
const USDG = ADDRESSES.robinhood.USDG;
const FROM_BLOCK = 15102260; // Goon deploy block
const MIN_TVL = 100;
const MAX_POOLS = 5000;

const LAUNCHED =
  "event Launched(address token, uint256 supply, string name, string symbol, string image, address creator, address pool, address lock)";
const SWAP_EVENT =
  "event Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)";

const SWAP_FEES_TO_PROTOCOL = "Token Swap Fees to Protocol";
const SWAP_FEES_TO_CREATOR = "Token Swap Fees to Creators";

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const dailyRevenue = options.createBalances();
  const dailySupplySideRevenue = options.createBalances();

  // Full history of launches, needed to know every pool that could still be trading.
  const allLaunches = await options.getLogs({
    target: GOON,
    eventAbi: LAUNCHED,
    fromBlock: FROM_BLOCK,
    cacheInCloud: true,
  });

  const pairObject: IJSON<string[]> = {};
  for (const launch of allLaunches) {
    pairObject[launch.pool.toLowerCase()] = [USDG.toLowerCase(), launch.token.toLowerCase()];
  }

  const filteredPools = await filterPools({
    api: options.api,
    pairs: pairObject,
    createBalances: options.createBalances,
    minUSDValue: MIN_TVL,
    maxPairSize: MAX_POOLS,
  });
  const pools = Object.keys(filteredPools);

  if (pools.length) {
    const feeTiers = await options.api.multiCall({
      abi: "function fee() view returns (uint24)",
      calls: pools,
      permitFailure: true,
    });

    const swapLogsByPool = await options.getLogs({
      targets: pools,
      eventAbi: SWAP_EVENT,
      flatten: false,
    });

    swapLogsByPool.forEach((logs: any[], i: number) => {
      if (!logs.length) return;
      const feeTier = Number(feeTiers[i] ?? 0) / 1e6;
      if (!feeTier) return;

      for (const log of logs) {
        const usdgRaw = Number(log.amount0);
        const usdgIn = usdgRaw > 0;
        const usdgLeg = Math.abs(usdgRaw);

        if (usdgIn) {
          // USD was the input, fee is charged directly in USD and goes to the protocol.
          const protocolFee = usdgLeg * feeTier;
          dailyFees.add(USDG, protocolFee, METRIC.SWAP_FEES);
          dailyRevenue.add(USDG, protocolFee, SWAP_FEES_TO_PROTOCOL);
        } else {
          // The launch token was the input, fee is charged in that token and goes to the
          // creator. We can't reliably price the arbitrary launch token itself, but we can
          // value the fee in USD-equivalent terms using this same swap's implied exchange
          // rate (grossing up the USD output by the fee rate).
          const creatorFee = (usdgLeg * feeTier) / (1 - feeTier);
          dailyFees.add(USDG, creatorFee, METRIC.SWAP_FEES);
          dailySupplySideRevenue.add(USDG, creatorFee, SWAP_FEES_TO_CREATOR);
        }
      }
    });
  }

  return {
    dailyFees,
    dailyRevenue,
    dailyProtocolRevenue: dailyRevenue,
    dailySupplySideRevenue,
  };
};

const methodology = {
  Fees: "Uniswap V3 swap fees generated by Goon-launched pools (pools with under $100 TVL are excluded as dust).",
  Revenue: "The USD share of swap fees accrue to the protocol treasury.",
  ProtocolRevenue: "Same as Revenue.",
  SupplySideRevenue: "The Token share of swap fees accrue to the token creator .",
};

const breakdownMethodology = {
  Fees: {
    [METRIC.SWAP_FEES]: "Uniswap V3 swap fees generated by Goon-launched pools, split by which side of the swap was the input: USD-input fees (to protocol) and Token-input fees (to creator). Pools with under $100 TVL are excluded as dust.",
  },
  Revenue: {
    [SWAP_FEES_TO_PROTOCOL]: "Swap fees charged when USD was the input token always accrue to the protocol treasury.",
  },
  ProtocolRevenue: {
    [SWAP_FEES_TO_PROTOCOL]: "Swap fees charged when USD was the input token always accrue to the protocol treasury.",
  },
  SupplySideRevenue: {
    [SWAP_FEES_TO_CREATOR]: "Swap fees charged when the Token was the input token accrue to the token creator",
  },
};


const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.ROBINHOOD],
  start: "2026-07-20",
  pullHourly: true,
  methodology,
  breakdownMethodology,
  doublecounted: true, // Goon pools are Uniswap V3 pools
};

export default adapter;
