export const METRICS = {
  ASSET_YIELDS_WRAPPED_M : 'Asset yields - Wrapped M',
  ASSET_YIELDS_WRAPPED_M_TO_PROTOCOL : 'Asset yields - Wrapped M to protocol',
  ASSET_YIELDS_WRAPPED_M_TO_SUSDAI : 'Asset yields - Wrapped M to staked USDai',
  ASSET_YIELDS_PYUSD : 'Asset yields - PYUSD',
  ASSET_YIELDS_PYUSD_TO_PROTOCOL : 'Asset yields - PYUSD to protocol',
  ASSET_YIELDS_PYUSD_TO_SUSDAI : 'Asset yields - PYUSD to staked USDai',
  ASSET_YIELDS_GPU_FINANCING : 'Asset yields - GPU-financing',
  ASSET_YIELDS_GPU_FINANCING_TO_PROTOCOL : 'Asset yields - GPU-financing to protocol',
  ASSET_YIELDS_GPU_FINANCING_TO_SUSDAI : 'Asset yields - GPU-financing to staked USDai',
  GPU_FINANCING_ORIGINATION_FEE : 'GPU-financing origination fee',
  GPU_FINANCING_ORIGINATION_FEE_TO_PROTOCOL : 'GPU-financing origination fee to protocol',
  GPU_FINANCING_EXIT_FEE : 'GPU-financing exit fee',
  GPU_FINANCING_EXIT_FEE_TO_PROTOCOL : 'GPU-financing exit fee to protocol',
  GPU_FINANCING_LIQUIDATION_FEE : 'GPU-financing liquidation fee',
  GPU_FINANCING_LIQUIDATION_FEE_TO_PROTOCOL : 'GPU-financing liquidation fee to protocol',
  GPU_FINANCING_LENDER_LIQUIDATION_REPAID : 'GPU-financing lender liquidation repaid',
  GPU_FINANCING_LENDER_LIQUIDATION_REPAID_TO_SUSDAI : 'GPU-financing lender liquidation repaid to staked USDai',
}