import { SimpleAdapter, FetchOptions } from "../../adapters/types"
import { CHAIN } from "../../helpers/chains"
import { addTokensReceived } from "../../helpers/token"
import ADDRESSES from "../../helpers/coreAssets.json"

const FEE_WALLET = '0x0B8f593C41C4CeeF6A2490861F7636C5CD19C078'

const TOKENS: Record<string, string> = {
    [CHAIN.BASE]: ADDRESSES.base.USDC,
    [CHAIN.ARBITRUM]: ADDRESSES.arbitrum.USDC_CIRCLE,
    [CHAIN.PLASMA]: ADDRESSES.plasma.USDT0,
    [CHAIN.HYPERLIQUID]: ADDRESSES.hyperliquid.USDT0,
}

const fetch = async (options: FetchOptions) => {
    const dailyFees = await addTokensReceived({
        options,
        target: FEE_WALLET,
        tokens: [TOKENS[options.chain]],
    })

    return {
        dailyFees,
        dailyRevenue: dailyFees,
        dailyProtocolRevenue: dailyFees,
    }
}

const adapter: SimpleAdapter = {
    version: 2,
    fetch,
    chains: Object.keys(TOKENS),
    start: "2025-02-01",
    methodology: {
        Fees: "10% performance fee charged on yields generated by the protocol.",
        Revenue: "All performance fees are collected by the protocol.",
        ProtocolRevenue: "All performance fees are collected by the protocol."
    },
}

export default adapter
