/**
 * GroypFi — Multi-product trading platform on TON
 *
 * Volume is generated by every GroypFi product:
 *   - DEX Aggregator (DeDust, STON.fi, Tonco, Bidask)
 *   - Trading Terminal
 *   - Cross-Chain Swap
 *   - NFT Aggregator
 *   - Token Launchpad (topblast.lol)
 *   - Perpetuals Platform
 *   - Gbot Telegram Trading Bot (@groypfi_bot)
 *
 * All products charge a 1% platform fee settling into the GroypFi house
 * fee wallets, so volume is reverse-calculated: volume = fees / 0.01
 *
 * Website: https://groypfi.io
 * Twitter: https://x.com/groypfi
 * Contact: zeuraph7@gmail.com
 */

import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { httpGet } from "../../utils/fetchURL";
import PromisePool from "@supercharge/promise-pool";

// House fee wallets (all inflows are protocol fees)
const FEE_WALLETS: string[] = [
  // UQDu4AiT__JKuqT0Znje0RoXIQMPcj4uIGYZme3UK4hFlE_Q
  "0:eee00893fff24abaa4f46678ded11a1721030f723e2e20661999edd42b884594",
  // UQCvlNDUcVJq55xVNV9BvCC1KUaMVUetnUkr_sSovHTLmTsj
  "0:af94d0d471526ae79c55355f41bc20b529468c5547ad9d492bfec4a8bc74cb99",
  // UQAuMfZUcQoiOt-S4vWJhlT2Qlewgrmi99AQ4ISEjDCAIR-i
  "0:2e31f654710a223adf92e2f5898654f64257b082b9a2f7d010e084848c308021",
  // UQDz_6Hyrq2AgMIWw4S5xPH9OBMcaerRp14y94T-cRJistBx
  "0:f3ffa1f2aead8080c216c384b9c4f1fd38131c69ead1a75e32f784fe711262b2",
];

const TON_API = "https://tonapi.io/v2";

// TonAPI public tier allows ~1 request / 4s without authorization.
const REQUEST_INTERVAL_MS = 4_100;
let nextSlot = 0;

async function rateLimitedGet<T>(url: string): Promise<T> {
  const now = Date.now();
  const runAt = Math.max(now, nextSlot);
  nextSlot = runAt + REQUEST_INTERVAL_MS;
  const wait = runAt - now;
  if (wait > 0) await new Promise((r) => setTimeout(r, wait));
  return httpGet(url);
}

interface TonMessage {
  value?: number | string;
  msg_type?: string;
  source?: { address: string };
  destination?: { address: string };
}

interface TonTransaction {
  hash: string;
  lt: string;
  utime: number;
  success: boolean;
  in_msg?: TonMessage;
  out_msgs?: TonMessage[];
}

interface TxPage {
  transactions: TonTransaction[];
}

function normalize(addr?: string): string {
  return (addr ?? "").toLowerCase();
}

async function fetchWindowTransactions(
  account: string,
  startTs: number,
  endTs: number,
): Promise<TonTransaction[]> {
  const collected: TonTransaction[] = [];
  let beforeLt: string | undefined;
  const limit = 256;

  // eslint-disable-next-line no-constant-condition
  while (true) {
    let url = `${TON_API}/blockchain/accounts/${account}/transactions?limit=${limit}&sort_order=desc&start_date=${startTs}&end_date=${endTs}`;
    if (beforeLt) url += `&before_lt=${beforeLt}`;

    const page: TxPage = await rateLimitedGet(url);
    const txs = page.transactions ?? [];
    if (txs.length === 0) break;

    for (const tx of txs) {
      if (tx.utime < startTs) return collected;
      if (tx.utime < endTs && tx.utime >= startTs) collected.push(tx);
    }

    beforeLt = txs[txs.length - 1].lt;
    if (txs.length < limit) break;
  }

  return collected;
}

const fetch = async (options: FetchOptions) => {
  const { startTimestamp, endTimestamp, createBalances } = options;

  const dailyVolume = createBalances();

  // Sequential, rate-limited collection. Any failure propagates so the period
  // is retried instead of being published as zero volume.
  const { results, errors } = await PromisePool.withConcurrency(1)
    .for(FEE_WALLETS)
    .process((wallet: string) =>
      fetchWindowTransactions(wallet, startTimestamp, endTimestamp),
    );

  if (errors.length)
    throw new Error(`groypfi: TonAPI transaction fetch failed: ${errors[0]}`);

  let feeNano = 0n;

  for (const txs of results) {
    for (const tx of txs) {
      if (!tx.success) continue;
      if (tx.in_msg && Number(tx.in_msg.value) > 0) {
        const from = normalize(tx.in_msg.source?.address);
        // Ignore internal transfers between our own wallets (no new fee).
        if (FEE_WALLETS.some((w) => normalize(w) === from)) continue;
        feeNano += BigInt(tx.in_msg.value ?? 0);
      }
    }
  }

  // Volume = fee / 0.01  (1% fee → multiply by 100)
  dailyVolume.addGasToken(
    feeNano * 100n,
    "Volume reverse-calculated from platform fees",
  );

  return { dailyVolume };
};

const methodology = {
  Volume:
    "Trading volume reverse-calculated from the 1% platform fee collected at the GroypFi house fee wallets (volume = fees / 0.01). Covers all revenue-generating products: DEX Aggregator, Trading Terminal, Cross-Chain Swap, NFT Aggregator, Token Launchpad, Perpetuals Platform and the Gbot Telegram Trading Bot. Transfers between the house wallets themselves are excluded.",
};

const breakdownMethodology = {
  Volume: {
    "Volume reverse-calculated from platform fees":
      "Sum of successful TON inflows to the four GroypFi house fee wallets (excluding transfers between those wallets) multiplied by 100, since every product charges a 1% platform fee.",
  },
};

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.TON],
  start: "2025-11-01",
  pullHourly: true,
  methodology,
  breakdownMethodology,
};

export default adapter;
