import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { METRIC } from "../../helpers/metrics";
import coreAssets from "../../helpers/coreAssets.json";

const distributor = '0xbD647dbcCae38A49149C4f3152b26d2a6Ba1EE6E'
const whype = coreAssets.hyperliquid.WHYPE
const distributionCreatedAbi = 'event DistributionCreated(uint256 indexed _distributionId, bytes32 indexed _merkleRoot, uint256 indexed _rewardAmount)'

const fetch = async (options: FetchOptions) => {
  const dailyFees = options.createBalances();
  const distributionLogs = await options.getLogs({
    target: distributor,
    eventAbi: distributionCreatedAbi
  })
  distributionLogs.forEach(log => {
    dailyFees.add(whype, log._rewardAmount, METRIC.ASSETS_YIELDS) 
  })

  return {
    dailyFees,
    dailyRevenue: 0,
    dailySupplySideRevenue: dailyFees,
    dailyProtocolRevenue: 0,
  }
}

const methodology = {
  Fees: "The yield generated by M, a wholesale dollar collateralized by short-term U.S Treasuries",
  Revenue: "100% of the fees collected are distributed to users in WHYPE tokens, with allocations proportional to their activity on eligible venues, such as trading volume or LP provision, rather than simply holding USDHL.",
  ProtocolRevenue: "Protocol takes no direct fees",
  SupplySideRevenue: "User rewards require activity such as trading or LPing in designated venues with USDHL; holding alone does not earn distributions."
}

const adapter: SimpleAdapter = {
  version: 2,
  fetch,
  chains: [CHAIN.HYPERLIQUID],
  start: '2025-06-25',
  methodology,
}

export default adapter;
