
import { FetchOptions, SimpleAdapter } from "../../adapters/types"
import { CHAIN } from "../../helpers/chains"
import { getSqlFromFile, queryDuneSql } from "../../helpers/dune"

const fetchRevenue = async (options: FetchOptions) => {
  // Jito Restaking Related revenue

  // https://dune.com/queries/4908531
  const sql = getSqlFromFile("helpers/queries/jito-restaking.sql", {
    start: options.startTimestamp,
    end: options.endTimestamp
  });

  const data: any[] = (await queryDuneSql(options, sql));
  if (data[0] == undefined) {
    return {
      dailyProtocolRevenue: 0,
    }
  }
  
  return {
      dailyProtocolRevenue: data[0].usd_amt,
    }
}

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.SOLANA]: {
      fetch: fetchRevenue,
      start: '2024-04-01',
      meta:{
        methodology: {
            ProtocolRevenue: "All DAO Revenue generated by the Jito Restaking protocol",
        },
      }
    }
  },
  isExpensiveAdapter: true
}

export default adapter
