name: Alert

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      with:
        persist-credentials: false
    - name: Update unlisted
      run: |
        curl --fail https://born-to-llama.herokuapp.com/refresh
        exit $?
    - name: Deploy to server
      run: |
        curl --fail https://born-to-llama.herokuapp.com/rebuild-server
        exit $?
