name: Build dimensionModules and upload artifact

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run buildImports script
        run: pnpm run build

      - name: Publish dimensionModules.json as "latest" release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          tag: latest
          name: Latest dimensionModules
          artifacts: cli/dimensionModules.json
          allowUpdates: true
