name: Check ts

on: [pull_request]

permissions:
  contents: read

jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js with pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Checking adapters
        run: pnpm run ts-check

      - name: Checking cli
        run: pnpm run ts-check-cli
